### PR TITLE
Make it possible to run on OpenBSD

### PR DESCRIPTION
**Pull request by viq**
Mostly just simple changes fixing finding `bash`, and system detection for `date` which I believe should work as well for FreeBSD.

The `seq` changes are quick and dirty and spit out warnings about not finding `seq` which I currently don't mind, but can try to fix the way that `date` was dealt with if it's preferred.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Thanks.  Have you already confirmed this still works and doesn't introduce any weirdness on Raspbian/Debian, or do we need someone to do that?

**Comment by viq** [comment]
I did not yet test on Debian, so testing there would be a good idea.

Having said that, `#!/usr/bin/env bash` is a pretty standard way to do it, and already at least a couple of scripts in there use `#!/usr/bin/env node` from what I've seen.

**Comment by PieterGit** [comment]
@viq I think a syntax of `seq || gseq` is quite ugly and should be fixed in the same way as `date` vs `gdate` (with an alias). Gitter link: https://gitter.im/openaps/oref0?at=5c2c98def6166a3027a8e236

**Comment by scottleibrand** [comment]
I’ve found the alias approach to be somewhat brittle. I don’t mind “ugly” if it prevents failure modes.

**Pull request merged**
