### PR TITLE
Changed suspend_zeros_iob default to true.

### PR DESCRIPTION
**Pull request by jpcunningh**
After successfully using this feature for a while, I recommend we make it the default behavior.

### CODE REVIEW

**Comment by jpcunningh** [comment]
Before merging this, we need to get the suspends handled all the way through nightscout db and autotune so autotune doesn't account for more IOB thanks really there due to a suspend.

**Comment by jpcunningh** [comment]
I verified it makes it all the way through NS and is handled correctly by Autotune. No changes were necessary.

**Comment by inventor96** [comment]
@jpcunningh Should this show up in Nightscout as a 0 temp basal?

**Comment by jpcunningh** [comment]
No, Nightscout's basal rendering code does not recognize the pump suspend events as a 0 temp basal.

**Pull request merged**
