### PR TITLE
find last BG from before a meal, and interpolate any gaps

### PR DESCRIPTION
**Pull request by scottleibrand**
This should fix the issue where a CGM restart or other data gap overlaps a meal entry, thereby causing carb absorption for that time period to be missed/ignored.

I've simulated that scenario by deleting CGM values out of glucose.json, but we'll also need to test it with real receiver data where the receiver was off, calibrating, or out of range around the meal time.

### CODE REVIEW

**Comment by scottleibrand** [comment]
TODO: once testing is completed, remove extra debug statements.

**Comment by Kdisimone** [comment]
Worked GREAT!  Ate 23 g carbs right before sensor session stopped. Started up new session about three hours later and cob was zero. Perfect!  So nice!!

**Comment by Kdisimone** [comment]
img_4471

img_4473

**Comment by scottleibrand** [comment]
We'll also want to test the scenario where the carb entry occurs after the sensor data stops, as that is the part that I changed in the code.

**Comment by scottleibrand** [comment]
We haven't seen any regressions with this, and it seems to help with COB calculations, so I'm going to merge this to dev for further testing there.  If anyone testing this still wants to compare this to the old behavior, you can check out the `zombie-carbs` branch.

**Pull request merged**
