### PR TITLE
mmtune 25% of the time; remove unless() loop

### PR DESCRIPTION
**Pull request by scottleibrand**
This might help with #522 somewhat, but doesn't address the root cause.

### CODE REVIEW

**Comment by Bender1061** [comment]
Can't get this to install
```
upload ! bash -c "echo -n Upload && ( openaps upload-bg; openaps upload-ns-status; openaps upload-recent-treatments ) 2>/dev/null >/dev/null && echo ed"
first-upload ! bash -c "cat nightscout/glucose.json | json 1 > nightscout/recent-missing-entries.json && openaps report invoke nightscout/uploaded-entries.json"
Traceback (most recent call last):
  File "/usr/local/bin/openaps-import", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/src/openaps/bin/openaps-import", line 89, in <module>
    app( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 52, in __call__
    self.epilog( )
  File "/root/src/openaps/bin/openaps-import", line 50, in epilog
    super(ImportToolApp, self).epilog( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 75, in epilog
    self.create_git_commit( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 82, in create_git_commit
    self.git_repo( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 78, in git_repo
    self.repo = getattr(self, 'repo', Repo(os.getcwd( ), odbt=GitCmdObjectDB))
  File "/home/.rootfs/usr/local/lib/python2.7/dist-packages/git/repo/base.py", line 158, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /root/johnopenaps
Could not import mdt-cgm.json
root@johnyfive:~#
```
I've tried this a couple times

**Comment by scottleibrand** [comment]
You might want to `rm -rf /root/johnopenaps/.git/` and try again.

**Comment by Bender1061** [comment]
false alarm, I had to do a crontab -r and it ran now, so I'm currently testing

**Comment by Bender1061** [comment]
So far, I'm getting the same issue. 
I reran everything, and this is what I found while doing the oref0-setup
```
Running: openaps report add enact/suggested.json text determine-basal shell monitor/iob.json monitor/temp_basal.json monitor/glucose.json settings/profile.json settings/autosens.json monitor/meal.json
added determine-basal://text/shell/enact/suggested.json
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jq : Depends: libjq1 (= 1.5+dfsg-1.3~bpo8+1) but it is not going to be installed
      Depends: libonig2 (>= 5.9.5) but it is not installable
E: Unable to correct problems, you have held broken packages.
importing autotune file
get-profile://text/shell/settings/pumpprofile.json
get-profile://text/shell/settings/profile.json
get-settings report invoke settings/model.json settings/bg_targets_raw.json settings/bg_targets.json settings/insulin_sensitivities_raw.json settings/insulin_sensitivities.json settings/basal_profile.json settings/settings.json settings/carb_ratios.json settings/pumpprofile.json settings/profile.json
Reading package lists... Done
Building dependency tree
Reading state information... Done
bc is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jq : Depends: libjq1 (= 1.5+dfsg-1.3~bpo8+1) but it is not going to be installed
      Depends: libonig2 (>= 5.9.5) but it is not installable
E: Unable to correct problems, you have held broken packages.
importing supermicrobolus file
determine-basal://JSON/shell/enact/smb-suggested.json
pump://JSON/set_temp_basal/enact/smb-enacted.json
pump://JSON/bolus/enact/bolused.json
Adding OpenAPS log shortcuts
Add NIGHTSCOUT_HOST and API_SECRET to /root/.bash_profile
sed: can't read .profile: No such file or directory
sed: can't read .profile: No such file or directory

Resetting spi_serial
Schedule openaps in cron? y/[N] y
```

**Comment by Bender1061** [comment]
Now when the loop is running I get 
```
Starting supermicrobolus pump-loop at Tue Jul 4 18:48:03 EDT 2017 with 30 second wait_for_silence:
MDT CGM configured; not waiting
Radio ok. Listening: .No pump comms detected from other rigs
mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low?
Checking pump status (suspended/bolusing): mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low?
grep: monitor/status.json: No such file or directory
Error, retrying
Waiting for 30s silence before mmtuning
Radio ok. Listening: .No pump comms detected from other rigs
Listening for 30s silence before mmtuning: .No pump comms detected from other rigs
mmtune:   stderr: 'fatal: Not a git repository (or any of the parent directories): .git'
"916.636", 5, -52 Sleeping 2;

Starting supermicrobolus pump-loop a
```

**Comment by Bender1061** [comment]
Ok we can forget about the above problems, I believe one of my rigs (the one I've been playing with most of the day) is bad, I believe its going to need a re flash of the edison. so testing with a different rig now

**Comment by PieterGit** [comment]
@scottleibrand : this fixes the problem and calls mmtune at the right time! I had a hanging rig-pump communication and changed the oref0-pump-loop.sh on the rig with todays version.

The mmtune calls ends with
`Unsuccessful supermicrobolus pump-loop at Wed Jul 5 22:58:24 CEST 2017`
but the next supermicrobolus pump-loop is succesful!

Please merge to dev.

**Comment by PieterGit** [comment]
To be exact. I tested with these commits: 
image

**Pull request merged**
