### PR TITLE
Deprecate and remove profile.carbratio_adjustmentratio

### PR DESCRIPTION
**Pull request by alimhassam**
This could have surprising or dangerous effects when used with autotune or smb.

### CODE REVIEW

**Comment by scottleibrand** [comment]
What's the use case for keeping carbratio_adjustmentratio at all?  In what situations would you want to set it > 1?

**Comment by scottleibrand** [comment]
If no one is successfully using it on an ongoing basis, I'm inclined to deprecate/remove carbratio_adjustmentratio entirely.  It seems to be a knob people try, unsuccessfully, to use before moving on to doing things another way.

**Comment by alimhassam** [comment]
I thought it might be good to keep it for safe measure, i just wanted to make it difficult to set it lower than 1 as it's now dangerous, specially since there are old documentation suggesting to do so and that it might only apply to the pump CR which is not true. 

This also adjusts the autotuned CR.

i don't personally needed right now, but it might possibly be a useful advanced tweaking point once i re-enable autotune in case it suggest CR that are still too low for any reason.

**Comment by alimhassam** [comment]
thought about this a little more, I guess you're right that there are too many parameters, so it if you prefer i'll remove it, and if needed again it could easily be re-added, maybe with a different name somethnig like `autotune_carbratio_multiplier` to make it clear.

**Comment by alimhassam** [comment]
i removed the parameter completely have the code on my rig, but didn't test a re-install

**Comment by alimhassam** [comment]
oops, didn't mean to close it, was supposed to just be a comment.

**Comment by Bender1061** [comment]
I use this, I have it set to 1.2 making it more aggressive with meals. tends to do a great job for me.

**Comment by scottleibrand** [comment]
That sounds backwards. 1.2 makes what more aggressive? Also, are you running autotune?

**Comment by scottleibrand** [comment]
All:  If you've used carbratio_adjustmentratio in the past, or are using it currently, I'd like to know how you used / are using it, and what your experience has been with it. If anyone is using it successfully I'd like to understand exactly how you're using it so we can decide whether to keep it, and if so how to make it safer for new users and those using autotune. And if you used it but gave up on it, we'd also like to understand why you tried it originally and why you stopped using it.

**Comment by Bender1061** [comment]
I started using this when I was having issues with SMB, this helped me at least during that transition. But I've for the past week set it as 1 so yeah it's no longer needed for me, so I'm OK with this.

**Comment by scottleibrand** [comment]
Ok.  If no one else thinks this needs to be kept, I'm planning to merge this PR as-is.

**Pull request merged**
