### PR TITLE
cherrypicks of the devww branch for the next oref0-release.

### PR DESCRIPTION
**Pull request by PieterGit**
Fixes: Consistent use of $HOME isntead of ~
Fixes: Installs $HOME/src/subg_rfspy for ww pump users, if it's not
there. Otherwise WW-pumps won't work.

### CODE REVIEW

**Comment by PieterGit** [comment]
as discussed on https://gitter.im/nightscout/intend-to-bolus?at=58c41b96dd08b4b859b7af26
@libxmike will give these fixes a test

**Comment by libxmike** [comment]
@PieterGit I installed this devww branch and get following errors
`
Starting pump-loop at Sat Mar 11 17:28:38 CET 2017:
Radio ok, Listening: .No pump comms detected from other rigs
Old pumphistory: 
Error, retrying
Listening: .No pump comms detected from other rigs
subg-ww-radio-parameters:running /usr/local/bin/oref0-subg-ww-radio-parameters for max 30 seconds
Your TI-stick is located at /dev/ttyACM0
+ cd /home/pi/src/subg_rfspy/tools
+ ./reset.py /dev/ttyACM0
RileyLink OK
Version: subg_rfspy 0.9
OK
+ sleep 2
+ ./change_setting.py /dev/ttyACM0 0x06 0x00
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x0C 0x59
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x0D 0x66
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x0E 0x33
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x0F 0x62
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x10 0x1A
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x11 0x13
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x09 0x24
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x0A 0x2E
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ ./change_setting.py /dev/ttyACM0 0x0B 0x38
RileyLink OK
Version: subg_rfspy 0.9
SUCCESS
+ sleep 0.5
+ exit 0
/usr/local/bin/oref0-subg-ww-radio-parameters-timeout: 8: kill: No such process

mmtune: monitor/mmtune.json  raised  Could not get subg_rfspy state or version. Have you got the right port/device and radio_type?
pump://JSON/mmtune/monitor/mmtune.json
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/pi/src/openaps/bin/openaps-report", line 82, in <module>
    app( )
  File "/home/pi/src/openaps/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/home/pi/src/openaps/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/home/pi/src/openaps/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/home/pi/src/openaps/openaps/reports/invoke.py", line 40, in main
    output = task.method(args, app)
  File "/home/pi/src/openaps/openaps/uses/use.py", line 44, in __call__
    self.before_main(args, app)
  File "/home/pi/src/openaps/openaps/vendors/medtronic.py", line 62, in before_main
    self.setup_medtronic( )
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/mmeowlink.py", line 92, in setup_medtronic
    setup_medtronic_link(self)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/mmeowlink.py", line 75, in setup_medtronic_link
    link = builder.build(radio_type, port)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/link_builder.py", line 16, in build
    return SubgRfspyLink(port)
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/subg_rfspy_link.py", line 55, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/serial_interface.py", line 32, in open
    self.check_setup()
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/subg_rfspy_link.py", line 72, in check_setup
    self.serial_rf_spy.sync()
  File "/usr/local/lib/python2.7/dist-packages/mmeowlink/vendors/serial_rf_spy.py", line 121, in sync
    raise CommsException("Could not get subg_rfspy state or version. Have you got the right port/device and radio_type?")
mmeowlink.exceptions.CommsException: Could not get subg_rfspy state or version. Have you got the right port/device and radio_type?
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Starting pump-loop at Sat Mar 11 17:30:57 CET 2017:
Radio ok, Listening: .No pump comms detected from other rigs
Old pumphistory: 
Error, retrying
Starting pump-loop at Sat Mar 11 17:32:10 CET 2017:
Radio ok, Listening: .No pump comms detected from other rigs
Old pumphistory: 
Error, retrying
Starting pump-loop at Sat Mar 11 17:33:23 CET 2017:
Radio ok, Listening: .No pump comms detected from other rigs
Old pumphistory: 
Error, retrying
Starting pump-loop at Sat Mar 11 17:34:35 CET 2017:
Radio ok, Listening: .No pump comms detected from other rigs
Old pumphistory: 
Error, retrying
Listening: .No pump comms detected from other rigs
subg-ww-radio-parameters:running /usr/local/bin/oref0-subg-ww-radio-parameters for max 30 seconds
/usr/local/bin/oref0-find-ti: 35: [: /dev/[: unexpected operator
Your TI-stick is located at /dev/[ 1631.632995] cdc_acm 1-1.5:1.0: failed to set dtr/rts
+ cd /home/pi/src/subg_rfspy/tools
+ ./reset.py '/dev/[' '1631.632995]' cdc_acm 1-1.5:1.0: failed to set dtr/rts
Traceback (most recent call last):
  File "./reset.py", line 13, in <module>
    rl = SerialRfSpy(sys.argv[1])
  File "/home/pi/src/subg_rfspy/tools/serial_rf_spy.py", line 24, in __init__
    self.ser = serial.Serial(serial_port, 19200, rtscts=rtscts, timeout=1)
  File "build/bdist.linux-armv7l/egg/serial/serialutil.py", line 236, in __init__
  File "build/bdist.linux-armv7l/egg/serial/serialposix.py", line 268, in open
serial.serialutil.SerialException: [Errno 2] could not open port /dev/[: [Errno 2] No such file or directory: '/dev/['
/usr/local/bin/oref0-subg-ww-radio-parameters-timeout: 8: kill: No such process
`

**Comment by PieterGit** [comment]
About the errors:
- `/usr/local/bin/oref0-subg-ww-radio-parameters-timeout: 8: kill: No such process`  is a non-issue (extraneous logging). It's caused by the 0.4.1 and it's fixed in my devww branch.
- `failed to set dtr/rts` indicates some problems with your TI USB . Nice to have somebody else experience this. Temporary solution: use `sudo oref0-reset-usb` when this occurs

Best solution for now:
Handfix line 5 and 6 of `/usr/local/bin/oref0-find-ti` to bypass automatically detection via `dmesg`. Uncomment it, so that it will echo the same pump device as you use in `pump.ini`. For example: 
```
echo /dev/ttyACM0
exit 0
```

I assume that get's the stuff up and running (or new/better errors)

These tracebacks look ugly, but it's an improvement over non working WW-pumps on 0.4.1 and current dev I suppose. @scottleibrand what's your opinion. This helps making WW-pumps work, but it's not there yet. The current cherry picks fix some issues for all users and I can't think of problems for non-WW-pumps users.

For debug purposes could past the output of `oref0-find-ti` and check what is happening with your USB system in `dmesg` (e.g. `dmesg | grep -i usb `)

**Comment by libxmike** [comment]
pi@Rpi3-2:~ $ dmesg | grep -i usb
[    0.145321] usbcore: registered new interface driver usbfs
[    0.145434] usbcore: registered new interface driver hub
[    0.145553] usbcore: registered new device driver usb
[    0.331204] usbcore: registered new interface driver smsc95xx
[    0.777768] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.780111] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.782473] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.789430] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.791737] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.794033] usb usb1: Product: DWC OTG Controller
[    0.796274] usb usb1: Manufacturer: Linux 4.4.50-v7+ dwc_otg_hcd
[    0.798541] usb usb1: SerialNumber: 3f980000.usb
[    0.801602] hub 1-0:1.0: USB hub found
[    0.806805] usbcore: registered new interface driver usb-storage
[    0.946603] usbcore: registered new interface driver usbhid
[    0.948918] usbhid: USB HID core driver
[    1.179114] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.379438] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.381790] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.384865] hub 1-1:1.0: USB hub found
[    1.669110] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.769434] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.772015] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.842509] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:49:44:19
[    2.339146] usb 1-1.5: new full-speed USB device number 4 using dwc_otg
[    2.451980] usb 1-1.5: New USB device found, idVendor=1d50, idProduct=8001
[    2.455550] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.459025] usb 1-1.5: Product: subg_rfspy
[    2.462423] usb 1-1.5: Manufacturer: Nightscout
[    2.465691] usb 1-1.5: SerialNumber: 000002
[    3.769265] cdc_acm 1-1.5:1.0: ttyACM0: USB ACM device
[    3.770303] usbcore: registered new interface driver cdc_acm
[    3.770318] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[    3.927476] usbcore: registered new interface driver brcmfmac
[  200.529956] usb 1-1.5: USB disconnect, device number 4
[  201.281939] usb 1-1.5: new full-speed USB device number 5 using dwc_otg
[  201.394855] usb 1-1.5: New USB device found, idVendor=1d50, idProduct=8001
[  201.394869] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  201.394877] usb 1-1.5: Product: subg_rfspy
[  201.394885] usb 1-1.5: Manufacturer: Nightscout
[  201.394894] usb 1-1.5: SerialNumber: 000002
[  201.396409] cdc_acm 1-1.5:1.0: ttyACM0: USB ACM device

and 

pi@Rpi3-2:~ $ oref0-find-ti
/dev/ttyACM0

**Comment by libxmike** [comment]
getting some errors

+ ./change_setting.py /dev/ttyACM0 0x09 0x24
retry 0 
retry 0 
retry 0 
retry 0 
retry 0 
retry 0 
retry 0 
retry 1 bb
RileyLink OK
retry 2 4f4b
Version: subg_rfspy 0.9
Traceback (most recent call last):
  File "./change_setting.py", line 22, in <module>
    if ord(resp) == 1:
TypeError: ord() expected a character, but string of length 14 found
/usr/local/bin/oref0-subg-ww-radio-parameters-timeout: 8: kill: No such process

mmtune: pump://JSON/mmtune/monitor/mmtune.json
reporting monitor/mmtune.json
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/pi/src/openaps/bin/openaps-report", line 82, in <module>
    app( )
  File "/home/pi/src/openaps/openaps/cli/__init__.py", line 52, in __call__
    self.epilog( )
  File "/home/pi/src/openaps/bin/openaps-report", line 69, in epilog
    super(ReportToolApp, self).epilog( )
  File "/home/pi/src/openaps/openaps/cli/__init__.py", line 75, in epilog
    self.create_git_commit( )
  File "/home/pi/src/openaps/openaps/cli/__init__.py", line 83, in create_git_commit
    if self.repo.is_dirty( ) or self.repo.index.diff(None):
  File "/usr/local/lib/python2.7/dist-packages/GitPython-2.1.1-py2.7.egg/git/repo/base.py", line 587, in is_dirty
    len(self.git.diff('--cached', *default_args)):
  File "/usr/local/lib/python2.7/dist-packages/GitPython-2.1.1-py2.7.egg/git/cmd.py", line 424, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-2.1.1-py2.7.egg/git/cmd.py", line 873, in _call_process
    return self.execute(call, **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-2.1.1-py2.7.egg/git/cmd.py", line 687, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git diff --cached --abbrev=40 --full-index --raw
  stderr: 'error: object file .git/objects/d3/beaddae66a0b057a16a4e6948c6aa0931a1814 is empty
error: object file .git/objects/d3/beaddae66a0b057a16a4e6948c6aa0931a1814 is empty
fatal: loose object d3beaddae66a0b057a16a4e6948c6aa0931a1814 (stored in .git/objects/d3/beaddae66a0b057a16a4e6948c6aa0931a1814) is corrupt'
"868.534", 5, -87 Starting pump-loop at Sat Mar 11 20:15:08 CET 2017:
R

**Comment by PieterGit** [comment]
@libxmike You should look for strings like `USB disconnect` (e.g. `[ 200.529956] usb 1-1.5: USB disconnect, device number 4`  or `failed to set dtr/rts` in the `dmesg`. That should not happen and causes problems with TI USB. 

Let's move the discussion to: https://github.com/openaps/oref0/pull/357 because this pull request is merged to dev and closed.

**Pull request merged**
