### PR TITLE
Initial version of command-behavior.tests.sh

### PR DESCRIPTION
**Pull request by jpcunningh**
This adds a unit tests to valid OpenAPS commands operate as expected. It provides dummy data to the commands, and test the output values to ensure the commands incorporated the test data correctly.

This is not intended to test the function of libraries the commands rely on to process the data.  Rather, it only test the commands process arguments correctly and provides representative samples of the expected data.  It doesn't test the validity of the data since that is accomplished in unit test for the processing libraries.

### CODE REVIEW

**Comment by jpcunningh** [comment]
@scottleibrand,

This has a test function now for each of the javascript commands in oref0.  It's ready for review and comment.

**Comment by jpcunningh** [comment]
Rebased onto dev to resolve merge conflict.

**Comment by scottleibrand** [comment]
Can you merge dev to master now that I've merged all the yargs PRs and clean up the resulting conflicts?

**Comment by jpcunningh** [comment]
@scottleibrand, rebased onto updated dev and resolved the merge conflicts.

**Pull request merged**
