### PR TITLE
Prep for 0.6.2 dev release to master

### PR DESCRIPTION
**Pull request by danamlewis**
0.6.2 - minor changes including a Carelink fix. This version supports both Edison/Explorer and Raspberry Pi-based rigs.

Important fixes:
- Fixes mraa for raspbian users with kernel 4.10+ (mostly affecting new Explorer HAT setups)

New functionality:
- Automates a setup step that was previously manual for Carelink users
- Ability for Enlite CGM users, particularly those using Carelink USB, to better control loop timing
- New /sgv.json route/endpoint, similar to xdrip+, for offline use with watchfaces, etc.

Minor fixes:
- Retries 3 times to get a Bluetooth IP address
- Avoids trying to set xdripaps "CGM" time, as it doesn't have a clock
- Autosens IOB calculations use the basal in effect at the time, not the current basal

Note: full support for use of Explorer HAT display is a WIP in 0.7.0-dev.

### CODE REVIEW

**Comment by danamlewis** [comment]
FYI - realizing we may need to release an 0.6.2 with some minor tweaks including a carelink fix, before heading to 0.7.0 (which doesn't yet support carelink). So, changing this next release PR to 0.6.2.

**Comment by scottleibrand** [comment]
Since master is currently broken for new Raspberry Pi based installs (with the latest raspbian), I'd like to get this merged and released ASAP.  If no one with a Carelink / Enlite is available to test, I'm OK merging it based on a 👍 from someone who's done a full install and verified it works with a Pi rig, and someone who can confirm it still looks good with Edison.

**Comment by tynbendad** [comment]
strangely, i just installed dev branch oref0 and even though it says it is 0.6.2-dev, it acts older... there's no flask in cron (so no offline webpage), and autotune runs very slow again.

**Comment by mwilliams** [comment]
Just got my PiZero headers soldered and the new Pi Hat installed.  Will attempt to run the setup this afternoon and get it going with my Enlite sensors and report back.  All will depend on how crazy work is, but I'll try to keep it cranking in the background, anxious to get running with the new hardware!

**Comment by mwilliams** [comment]
No luck looping on a fresh 0.6.2 install on a RPiZero with an explorer hat running MDT CGM.

```
Starting oref0-pump-loop at Mon 11 Jun 17:37:12 EDT 2018 with 8 second wait_for_silence:
MDT CGM configured; not waiting
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight grep: settings/model.json: No such file or directory
grep: settings/model.json: No such file or directory
fail. Retrying preflight
Preflight grep: settings/model.json: No such file or directory
grep: settings/model.json: No such file or directory
fail. Couldn't preflight
oref0-pump-loop failed. pump_loop_completed more than 15m old; waiting for 40s silence before mmtuning
```

I saw it trying to get invoked during the setup:

```
importing autotune file
get-profile://text/shell/settings/pumpprofile.json
get-profile://text/shell/settings/profile.json
get-settings report invoke settings/model.json settings/bg_targets_raw.json settings/bg_targets.json settings/insulin_sensitivities_raw.json settings/insulin_sensitivities.json settings/basal_profile.json settings/settings.json settings/carb_ratios.json settings/pumpprofile.json settings/profile.json
```

**Comment by scottleibrand** [comment]
@mwilliams it looks like the `openaps report invoke settings/model.json` is failing.  can you run that manually, (or `export OREF0_DEBUG=1 && oref0-pump-loop`) to see why?  Also, what pump model are you testing with?

**Comment by mwilliams** [comment]
Testing with a 723. I’ll run it after I get the kids down to bed and dump
the output here. I’ll likely have time to test any fixes as well tonight if
necessary.

(Really digging the menu system on the Pi hat too btw!)

**Comment by scottleibrand** [comment]
You have to stop your loop before running commands manually, as described here: https://openaps.readthedocs.io/en/latest/docs/Troubleshooting/Pump-rig-communications-troubleshooting.html#how-can-you-see-the-results-of-your-pump-tuning

**Comment by mwilliams** [comment]
Bah, sorry.

That said - ran without a problem...

```
openaps report invoke settings/model.json
pump://JSON/model/settings/model.json
reporting settings/model.json
root@mattspancreas:~/myopenaps# cat settings/model.json
"723"
```
I'm also watching a successful loop happen now (and verified cron was killed on my Edison rig, no active looping from that rig - though could that have warmed things up when it pushed data to NS that my Pi and 0.6.2 may have pulled down and been happy with?  Or maybe I just needed to give it a few more initial loop cycles?  ).

```
Starting oref0-pump-loop at Mon 11 Jun 20:43:03 EDT 2018 with 3 second wait_for_silence:
MDT CGM configured; not waiting
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight OK.
Attempting to retrieve MDT CGM data from pump
MDT CGM data retrieved
MDT New cgm data reformatted
Profile less than 60m old; Profile valid. Refreshed pumphistorySkipping bolus wizard entry 0 in the pump history with 0 g carbs and no insulin.
This is caused by a BolusWizard without carbs. If you specified insulin, it will be noted as a seperate Bolus
Timestamp of bolus wizard: 2018-06-11T20:28:20-04:00
Warning: clock input Invalid Date is unzoned; please pass clock-zoned.json instead
Warning: clock input Invalid Date is unzoned; please pass clock-zoned.json instead
 and meal.json
Checking pump clock: "2018-06-11T20:45:20-04:00" is within 90s of current time: Mon 11 Jun 20:45:47 EDT 2018
Temp refreshed
Warning: Autotune has not been run. All microboluses will be disabled until you manually run autotune or add it to run nightly in your loop.
{"carbs":60,"nsCarbs":60,"bwCarbs":0,"journalCarbs":0,"mealCOB":0,"currentDeviation":-2.67,"maxDeviation":3.01,"minDeviation":-1.81,"slopeFromMaxDeviation":-1.359,"slopeFromMinDeviation":0,"allDeviations":[-2,3,2,-1],"lastCarbTime":1528756563000,"bwFound":false}
{"iob":3.177,"activity":0.0442,"basaliob":-0.216,"bolusiob":3.393,"netbasalinsulin":-0.65,"bolusinsulin":12,"time":"2018-06-12T00:45:27.000Z","iobWithZeroTemp":{"iob":3.177,"activity":0.0442,"basaliob":-0.216,"bolusiob":3.393,"netbasalinsulin":-0.65,"bolusinsulin":12,"time":"2018-06-12T00:45:27.000Z"},"lastBolusTime":1528756563000,"lastTemp":{"rate":5.7,"timestamp":"2018-06-11T20:36:45-04:00","started_at":"2018-06-12T00:36:45.000Z","date":1528763805000,"duration":10.19}}
{"delta":3.25,"glucose":142,"noise":null,"short_avgdelta":-0.04,"long_avgdelta":-3.05,"date":1528763640000}
Autosens ratio: 1; Basal unchanged: 2.5; ISF unchanged: 16; CR: 8.5
currenttemp: { duration: 22, rate: 5.7, temp: 'absolute' } lastTempAge: 9 m tempModulus: 1 m
SMB disabled (!microBolusAllowed)
Last carbs 130 minutes ago; remainingCATime: 6.3 hours; 100% carbs absorbed
Carb Impact: 3.5 mg/dL per 5m; CI Duration: 0 hours; remaining CI (~2h peak): 0 mg/dL per 5m
UAM Impact: 3.5 mg/dL per 5m; UAM Duration: 0.3 hours
minPredBG: 98 minIOBPredBG: 108 minZTGuardBG: 103 minUAMPredBG: 92 avgPredBG: 103 COB: 0 / 60
BG projected to remain above 90 for 240 minutes
naive_eventualBG: 91 bgUndershoot: -26 zeroTempDuration: 240 zeroTempEffect: 160 carbsReq: -99
undefined 46
2018-06-12T00:46:02.471Z
Checking deliverAt: 2018-06-12T00:46:02.471Z is within 1m of current time: Mon 11 Jun 20:46:04 EDT 2018
and that smb-suggested.json is less than 1m old
enact/smb-suggested.json: {"temp":"absolute","bg":142,"tick":"+3","eventualBG":112,"insulinReq":0.5,"reservoir":"247.5","deliverAt":"2018-06-12T00:46:02.471Z","sensitivityRatio":1,"predBGs":{"IOB":[142,142,141,141,140,139,138,136,135,133,132,130,128,126,124,122,121,119,118,117,116,115,114,113,112,112,111,111,110,110,110,110,109,109,109,109,109,109,109,109,109,109,109,108],"ZT":[142,138,135,132,129,126,123,120,118,116,114,112,110,109,107,106,105,105,104,104,103,103,103,104,104,104],"UAM":[142,141,138,135,132,129,126,123,120,118,116,113,111,109,108,106,104,103,102,100,99,98,98,97,96,95,95,95,94,94,93,93,93,93,93,93,93,93,93,92]},"COB":0,"IOB":3.177,"reason":"COB: 0, Dev: 21, BGI: -4, ISF: 16, CR: 8.5, Target: 90, minPredBG 98, minGuardBG 92, IOBpredBG 108, UAMpredBG 92; Eventual BG 112 >= 90, 22m@5.70 > 2 * insulinReq. Setting temp basal of 3.5U/hr. ","duration":30,"rate":3.5}
Temp refreshed: monitor/temp_basal.json: {"duration":22,"rate":5.7,"temp":"absolute"}
enact/smb-enacted.json: "Rate: 3.5 Duration: 30"
Temp refreshed: monitor/temp_basal.json: {"duration":30,"rate":3.5,"temp":"absolute"}
No bolus needed. Pump profile refreshed; Could not parse autotune_data
No temptargets found.
Settings refreshed; Edison battery at 100% is charged (>= 98%) or likely charging (60-70%). pumphistory-24h refreshed
Settings less than 3 minutes old. Refreshed pumphistorySkipping bolus wizard entry 0 in the pump history with 0 g carbs and no insulin.
This is caused by a BolusWizard without carbs. If you specified insulin, it will be noted as a seperate Bolus
Timestamp of bolus wizard: 2018-06-11T20:28:20-04:00
Warning: clock input Invalid Date is unzoned; please pass clock-zoned.json instead
Warning: clock input Invalid Date is unzoned; please pass clock-zoned.json instead
 and meal.json
IOB: null
Completed oref0-pump-loop at Mon 11 Jun 20:48:40 EDT 2018
```

**Comment by N3FM** [comment]
I see the following issues. None of them appear to be fatal.  (My system is 722/Enlite/Edison/explorer). 
1) "Checking pump clock" works fine much of the time. Sometimes, however, it suddenly shows a time that is several minutes old, and system immediately tries to set time. Setting time results in a 'bytearray index out of range" for the pump (or a mmeowlink exception), and "Invalid Choice" error for the CGM. Scott mentioned that something is inappropriately trying to set MDT pump and Enlite CGM clocks.  I also see an issue where the pump clock suddenly drifts 40 seconds (or, the value is not refreshed before being compared to system time.) 
bootst
Otherwise, 0.6.2 installed cleanly (re-flashed Jubilinux for other issues - bootstrap - git dev - setup.sh) 

```
Warning: setting mealCOB to 0 because currentDeviation is null/undefined
Not enough glucose data to calculate carb absorption; found: 2
 and meal.json
Checking pump clock: "2018-06-11T22:12:52-04:00" is within 90s of current time: Mon Jun 11 22:13:12 EDT 2018
Temp refreshed
Warning: Autotune has not been run. All microboluses will be disabled until you manually run autotune or add it to run nightly in your loop.
{"carbs":0,"nsCarbs":0,"bwCarbs":0,"journalCarbs":0,"mealCOB":0,"currentDeviation":null,"maxDeviation":0,"minDeviation":999,"slopeFromMaxDeviation":0,"slopeFromMinDeviation":999,"allDeviations":[],"lastCarbTime":0,"bwFound":false,"reason":"not enough glucose data to calculate carb absorption"}
{"iob":0.582,"activity":0.0023,"basaliob":0.582,"bolusiob":0,"netbasalinsulin":0.6,"bolusinsulin":0,"time":"2018-06-12T02:12:52.000Z","iobWithZeroTemp":{"iob":0.582,"activity":0.0023,"basaliob":0.582,"bolusiob":0,"netbasalinsulin":0.6,"bolusinsulin":0,"time":"2018-06-12T02:12:52.000Z"},"lastBolusTime":0,"lastTemp":{"rate":6.6,"timestamp":"2018-06-11T21:55:26-04:00","started_at":"2018-06-12T01:55:26.000Z","date":1528768526000,"duration":8.32}}
{"delta":0,"glucose":171,"noise":null,"short_avgdelta":0.77,"long_avgdelta":0,"date":1528768260000}
null
No deliverAt found.
{"reason":"If current system time Mon Jun 11 2018 22:13:23 GMT-0400 (EDT) is correct, then BG data is too old. The last BG data was read 22.4m ago at Mon Jun 11 2018 21:51:00 GMT-0400 (EDT). Temp 0 <= current basal 2.2U/hr; doing nothing. "}
Couldn't smb_verify_suggested
oref0-pump-loop failed. MDT CGM configured; not waiting
Unsuccessful oref0-pump-loop (BG too old) at Mon Jun 11 22:13:23 EDT 2018


Starting oref0-pump-loop at Mon Jun 11 22:14:02 EDT 2018 with 4 second wait_for_silence:
MDT CGM configured; not waiting
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)
Preflight OK.
Attempting to retrieve MDT CGM data from pump
MDT CGM data retrieved
MDT New cgm data reformatted
Profile less than 60m old; Profile valid. Refreshed pumphistoryWarning: could not parse monitor/carbhistory.json

Warning: setting mealCOB to 0 because currentDeviation is null/undefined
Not enough glucose data to calculate carb absorption; found: 2
 and meal.json
Checking pump clock: "2018-06-11T22:14:31-04:00" is within 90s of current time: Mon Jun 11 22:15:35 EDT 2018
Pump clock is more than 55s off: attempting to reset it
Waiting for ntpd to synchronize... OK!
Setting pump time to Mon Jun 11 22:15:35 EDT 2018
mmeowlink.exceptions.InvalidPacketReceived
Setting CGM time to Mon Jun 11 22:15:54 EDT 2018
openaps-use cgm: error: argument USAGE: invalid choice: 'UpdateTime' (choose from 'bolus', 'config', 'filter_glucose_date', 'filter_isig_date', 'iter_glucose', 'iter_glucose_hours', 'iter_pump', 'iter_pump_hours', 'mmtune', 'model', 'mytest', 'press_keys', 'read_basal_profile_A', 'read_basal_profile_B', 'read_basal_profile_std', 'read_battery_status', 'read_bg_targets', 'read_carb_ratios', 'read_clock', 'read_current_glucose_pages', 'read_current_history_pages', 'read_glucose_data', 'read_history_data', 'read_insulin_sensitivies', 'read_insulin_sensitivities', 'read_selected_basal_profile', 'read_settings', 'read_status', 'read_temp_basal', 'reservoir', 'resume_pump', 'set_clock', 'set_temp_basal', 'settings', 'status', 'suspend_pump', 'test_oref0_compat_menu')
Temp refreshed
'''

**Comment by mwilliams** [comment]
@N3FM RR on the update, 73 de W2MDW :)

**Comment by Kdisimone** [comment]
For pi0Hat...this version should come with some release notes that 
1. the HAT screen isn't showing the whole bit of info (the temp basal rates, duration, etc.) that would display above the BG graph are not showing. 
2. The status screen on HAT also isn't refreshing automatically

**Comment by Kdisimone** [comment]
also on pi0, the rig does not disconnect from bt tether when it moves back onto a known wifi network

**Comment by scottleibrand** [comment]
@Kdisimone what does the network.log say?

**Comment by Kdisimone** [comment]
Starting oref0-online at Tue 12 Jun 18:07:03 PDT 2018.
UID        PID  PPID  C STIME TTY          TIME CMD
root       389     1  0 11:07 ?        00:00:01 /usr/lib/bluetooth/bluetoothd
At Tue 12 Jun 18:07:03 PDT 2018 my wifi network name is NETGEAR05
At Tue 12 Jun 18:07:03 PDT 2018 my local wifi IP is: 192.168.1.3 192.168.1.22
At Tue 12 Jun 18:07:04 PDT 2018 my Bluetooth is connected to iPhone
At Tue 12 Jun 18:07:04 PDT 2018 my local Bluetooth IP is: 172.20.10.7
At Tue 12 Jun 18:07:04 PDT 2018 my public IP is: 71.84.21.132
At Tue 12 Jun 18:07:05 PDT 2018 my local hotspot is not running (and not enabled in preferences.json)
Finished oref0-online at Tue 12 Jun 18:07:05 PDT 2018.

**Comment by Kdisimone** [comment]
It did finally unhook...nearly over an hour after it stayed connected to both.  FYI

**Comment by scottleibrand** [comment]
`my local wifi IP is: 192.168.1.3 192.168.1.22` is probably what was preventing it from disconnecting: somehow your router gave the rig two different IP addresses, and it didn't know what to do until one of the leases expired.  Not sure if that's a corner case worth coding around, as people can just manually kill the hotspot on their phone, or wait for it.

**Comment by scottleibrand** [comment]
https://gitter.im/nightscout/intend-to-bolus?at=5b26b4529a211e26bb6a421b from @mhaeberli: "late 👍 thx on 0.6.2 beta status"

**Comment by scottleibrand** [comment]
https://gitter.im/nightscout/intend-to-bolus?at=5b264235f3e3007371b903db from @juehv: "After running 0.6.2 with 754+enlite+pi0+carelink for around a day I can conclude its working as good as 0.6.1 for me. I had some issues with 0.6.1 when it's not connected to the internet it stops working after some time. I didn't investigate the problem yet and I didn't test with 0.6.2."

**Comment by scottleibrand** [comment]
Based on the feedback we've received, I think 0.6.2 is ready for release.

**Pull request merged**
