### PR TITLE
Fix mdt trend comparison order

### PR DESCRIPTION
**Pull request by efidoman**

### CODE REVIEW

**Comment by efidoman** [comment]
I can't seem to isolate the changes for the MDT trend if comparison fix. It pulls in my other changes from the glances PR

**Comment by scottleibrand** [comment]
You’ll want to do something like:

git checkout dev
git checkout -b mdt-trend-fix
git cherry-pick db426c1bcebeaec1d83a3a224cfc6137b225f217
git push

**Comment by efidoman** [comment]
Having trouble once I get tot he cherry pick step
Switched to a new branch 'mdt-trend-fix'
root@eddie2:~/src/oref0# git cherry-pick db426c1
fatal: bad revision 'db426c1'

**Comment by scottleibrand** [comment]
If you don’t have a local copy of that commit it might be easiest to just re-do your changes on the clean branch.

**Comment by efidoman** [comment]
Did it locally on the rig, but still getting stuck. Sorry for all the troubles.

root@eddie2:~/src/oref0# git config --global push.default simple
root@eddie2:~/src/oref0# git push
fatal: The current branch fix-mdt-trend has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin fix-mdt-trend

root@eddie2:~/src/oref0# git push --set-upstream origin fix-mdt-trend
fatal: remote error:
  ****You can't push to git://github.com/openaps/oref0.git
  Use https://github.com/openaps/oref0.git****
root@eddie2:~/src/oref0# git branch
  dev
* fix-mdt-trend
  master
  mdt-trend-fix
root@eddie2:~/src/oref0#

**Comment by scottleibrand** [comment]
You don’t have perms to push directly to openaps/oref0 - you have to push to your own fork instead.

**Comment by efidoman** [comment]
I finally cleaned this simple change and got it on its own branch. Closing this one.

**Pull request closed without merging**
