### PR TITLE
Advanced meal assist

### PR DESCRIPTION
**Pull request by amazaheri**
Removed percentile and percentRank as they are already in cob-autosense.js

### CODE REVIEW

**Comment by scottleibrand** [comment]
Now that I've fixed the failing unit tests in AMA, can you rebase or merge that so we can make sure this change doesn't break anything?

**Comment by amazaheri** [comment]
Will do 😀

**Comment by amazaheri** [comment]
Just merged and my branch is all up-to-date, will push to RasPi remotely and test and let you know.

**Comment by amazaheri** [comment]
Test all went well, all my rigs are running on this as we speak.

**Comment by amazaheri** [comment]
on a second thought, may be we should refactor this as a separate lib so as we add more helper functions we can use that.

**Comment by scottleibrand** [comment]
@amazaheri do you want me to keep this open?

**Comment by amazaheri** [comment]
nah, removed the duplicate code awhile back.

**Pull request closed without merging**
