### PR TITLE
Adding xdrip offline support

### PR DESCRIPTION
**Pull request by colinlennon**
Added support for xdrip as cgm source, using xDripAPS microservice.

### CODE REVIEW

**Comment by colinlennon** [comment]
Thanks! As soon as I have time, I'll pull the docs and add some details. Should I pull the dev docs, or master?

**Comment by PieterGit** [comment]
Hi Colin,

Looks good. Might also be usefull for my dex usb branch, see 
https://github.com/openaps/oref0/pull/282

I noticed a possible security issue on lines 
https://github.com/colinlennon/xDripAPS/blob/master/xDripAPS.py#L79 and 
https://github.com/colinlennon/xDripAPS/blob/master/xDripAPS.py#L123
You don't do any input checking as far as a I see, see
https://www.owasp.org/index.php/Testing_for_SQL_Injection_%28OTG-INPVAL-005%29

**Comment by scottleibrand** [comment]
Most docs PRs go to master. We save dev for major restructurings that we need to preview in RTD and collaborate on.

**Comment by sulkaharo** [comment]
Did xDrip support multiple REST upload targets? Wondering what the optimal setup for this would be. We have three active loops and sync everything to Nightscout, so what could work is xDrip pushing locally to all three if they're present (using .local domains) as well as Nightscout. @scottleibrand what's the default loop behavior if SGV data is available from multiple sources? Or was the script single-source as is?

**Comment by jasoncalabrese** [comment]
You should be able to give xdrip space separated URIs, but at least with some old uploader versions if an upload failed to one of the destinations it would prevent/slow uploads to the others.

**Comment by scottleibrand** [comment]
@sulkaharo we have updated oref0 to support multiple CGM sources uploading to NS, and routinely have both a rig and Dexcom Share data being uploaded there, sometimes from differently calibrated receivers. @jasoncalabrese has also tested using different sensors. When the readings are off by more than about 1 mmol, you can get weird oscillations depending on the timing of uploads, any upload gaps, and the timing of oref0 runs. But even then it tends to all average out to do the right thing. If they're pretty close it works great.

**Comment by libxmike** [comment]
installing fresh with xdrip and getting error and exit:
Checking /home/pi/myopenaps: /home/pi/src/oref0/bin/oref0-setup.sh: line 231: openaps: command not found
Can't init /home/pi/myopenaps

**Comment by colinlennon** [comment]
@libxmike Is it a completely fresh install? Looks like you might not have the OpenAPS toolset installed. If you're not sure, you could check by creating a test directory, cd into it and see if 'openaps init' works or not.

**Comment by colinlennon** [comment]
@PieterGit Thanks Pieter. Yes, you're correct, I should add checks for SQL injection attacks to the code, that's on my to-do list.

**Comment by libxmike** [comment]
@colinlennon you right, I did not run on this rig openaps install. now I can install. Got confused with many of my SD Card images I have.

**Pull request merged**
