### PR TITLE
Pass the "BG data out of date" message on to nightscout

### PR DESCRIPTION
**Pull request by cjo20**
NS wasn't giving a reason for loop not running and it turned out to be the "BG data out of date" case that was causing it. This change allows the error message to be passed to Nightscout.

### CODE REVIEW

**Comment by scottleibrand** [comment]
I installed this branch on one of my rigs and confirmed it doesn't break anything, and that the reason field gets uploaded to the NS devicestatus.json.  But at least with multiple rigs it's just saying "Looping" for the one that is getting BG too old, not showing me anything in the OpenAPS pill.  Have you tested that part and confirmed whether it displays something useful there about BG too old when no enacts are occurring?

**Comment by cjo20** [comment]
I have had the "BG data out of date" message passed on NS and displayed in the OpenAPS pill - it should be part of the "Suggested" upload in the status. i don't know if this is because I'm running this change on NS: https://github.com/nightscout/cgm-remote-monitor/pull/1856

**Comment by jasoncalabrese** [comment]
Should we even upload status when determine-basal fails because of stale data like this?  I see it with my rigs and have considered it a bug in loop.

**Comment by cjo20** [comment]
I'm not sure how else to tell why a loop is failing without console/ssh'ing to the rig.

**Comment by cjo20** [comment]
image
How it looks on my nightscout

**Pull request merged**
