### PR TITLE
Offline xdrip

### PR DESCRIPTION
**Pull request by scottleibrand**
Cleaned-up version of https://github.com/openaps/oref0/pull/1139, in an openaps/oref0 branch for easier testing.

We'll need some folks who use xDrip to test.  To do so, follow the https://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/update-your-rig.html#alternative-step-1b-test-a-feature-branch-not-recommended-for-initial-setup instructions to test the offline-xdrip feature branch.

### CODE REVIEW

**Comment by sulkaharo** [comment]
Yay @scottleibrand thanks. Commenting here too - we've had this on our production rig from the first commits and after the latest fixes in Jan, I haven't had any issues + the offline looping has worked in a plane & boat & underground. I'll have access to the xDrip phone in the evening and can post shots of where to configure this in xDrip.

**Comment by PedanticAvenger** [comment]
Ok, I've experienced a repeated problem moving between dev and offline-xdrip branches.  While on dev system operates correctly, but once I move to offline-xdrip looping ceases.  The errors in ns-loop.log show as..
```
Starting oref0-ns-loop at Wed May 1 21:03:02 MDT 2019:
module.js:550
    throw err;
    ^

Error: Cannot find module 'network'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/src/oref0/bin/oref0-get-ns-entries.js:27:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by PedanticAvenger** [comment]
edison/explorer and I haven't tested deeply to see if the offline aspect works.  I had xdrip forwarding to the appropriate port but still wouldn't loop.  Switching back to dev immediately resolved.

**Comment by p5nbTgip0r** [comment]
The only issues I saw were that the node packages `network`, `yargs`, and `request` did not seem to get installed. After setting up and installing the branch I saw in the ns-loop.log there were errors about missing the `network` and `request` modules and I also saw errors about missing `yargs` in the pump loop logs. 

Navigating to `/root/src/oref0/node_modules` and running the command `npm install network request yargs` seemed to fix the errors. I'm not entirely sure why this is necessary, but I'm hoping it was just from me having an old node_modules folder from my installation on the dev branch.

The functionality added in this branch seems to work well. I haven't had a chance to test in day to day life yet, however I forced BT tethering by disabling Wi-Fi on the rig and disabled networking on my phone to simulate being offline and the `ns-loop.log` pulls from xDrip's local server with no issue. When it is able to pull from Nightscout, it tries that first and then resorts to xDrip's server if necessary.

To make testing this branch a little easier I would suggest merging the changes in `oref0-setup.sh` on the dev branch into this branch as the Go pump binaries not downloading made setting up this branch a little more difficult than necessary. 

Other than the setup hiccups I had, which I'm hoping were my fault due to an old node_modules folder, I would say it looks good to me. I will try this out for a few days and report back if any issues arise.

**Comment by scottleibrand** [comment]
Just merged dev back into offline-xdrip and resolved the merge conflict.

**Comment by rkresha** [comment]
So this is `pulling` the xdrip bg's from the phone, instead of the current xdrip on phone `pushing` to the rig's xdrip component (if you'd picked xdrip for your cgm)?

**Comment by p5nbTgip0r** [comment]
@rkresha Yes, it relies on xDrip's local webserver feature when you're tethering to the rig

**Comment by sulkaharo** [comment]
@rkresha Yes basically this allows users to choose between using CGM logic that runs on their rig or using the xDrip Android application and having the rig pull the CGM data directly from the phone without going online. I personally prefer the "xDrip on the phone" solution due to the CGM UI being more accessible on the phone, especially for the rest of the family. Plus this allows offline looping using any CGM source the phone xDrip supports.

**Comment by scottleibrand** [comment]
Has anyone had a chance to test this?

**Comment by PedanticAvenger** [comment]
I've used this branch over a 5 day fishing trip, but I can't verify the pull vs push, still not clear on the configuration parameters to set.  It certainly introduces no errors when running in online mode.

**Comment by scottleibrand** [comment]
@sulkaharo are you confident that the level of testing we've done so far is sufficient to identify any regressions, and allow us to merge this to dev?

**Comment by scottleibrand** [comment]
If we can get someone to test this, it might be a candidate for 0.7.0 release.  If not, it'll need to be pushed to 0.7.1, or we can close the PR if no one is using it.

**Comment by sulkaharo** [comment]
I'll upgrade our test rig to this today and test

**Comment by sulkaharo** [comment]
I merged this to the latest dev and installed to our test rig and this seems to work as expected. Data is loaded from xDrip if it's available and Nightscout if xDrip is not present.

**Comment by sulkaharo** [comment]
Tested on Edison, both with 1) not connected to xDrip hotspot, 2) connected to Android with xDrip share disabled and 3) connected to Android with xDrip share enabled and this works as expected (data is loaded from Nightscout when xDrip is not available and xDrip when it is available).

**Comment by scottleibrand** [comment]
We don't use xDrip at all, so running this on one of our rigs for regression testing. In the ns-loop.log, I now see this scary error:

```
Load from xDrip failed { Error: connect ECONNREFUSED 10.0.1.1:17580
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.0.1.1',
  port: 17580 }
Got Not Changed response from Nightscout, assuming no new data is available
My router IP is 10.0.1.1
Trying to load CGM data from local xDrip
Load from xDrip failed { Error: connect ECONNREFUSED 10.0.1.1:17580
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.0.1.1',
  port: 17580 }
Got CGM results from Nightscout
```

We should change that to not show that error for people not using xDrip.

**Comment by sulkaharo** [comment]
Doh, yes ECONNREFUSED should be also caught in the error statement. Sec

**Comment by scottleibrand** [comment]
Better, but still getting a bunch of unnecessary logging:
```
Starting oref0-ns-loop at Sun Oct 27 12:48:02 PDT 2019:
My router IP is 10.0.1.1
Trying to load CGM data from local xDrip
Load from local xDrip timed out, likely not connected to xDrip hotspot
Got CGM results from Nightscout
My router IP is 10.0.1.1
Trying to load CGM data from local xDrip
Load from local xDrip timed out, likely not connected to xDrip hotspot
Got Not Changed response from Nightscout, assuming no new data is available
Found recent valid BG:
{"glucose":96,"dateString":"2019-10-27T19:42:48.000Z"}
```

I think if we got rid of the newline after `My router IP` to join that line with `Trying to load CGM data from local xDrip`, and then get rid of the duplicate logging on the second attempt at hitting xDrip, we'd be down to a non-concerning level of logging for non-xDrip users.

**Comment by scottleibrand** [comment]
With those fixes, this now LGTM. If anyone else wants to test anything before we merge this to dev, please speak up. Otherwise I'll do so sometime after running it for the rest of the day and confirming it doesn't cause any issues for non-xDrip users.

**Comment by scottleibrand** [comment]
Still looks good on one rig.  Merging to dev for more folks to test more broadly.

**Pull request merged**
