### PR TITLE
Remove unnecessary verbose logging of the oref0-subg-ww-radio-paramet…

### PR DESCRIPTION
**Pull request by alimhassam**
…ers.

This logs every line being executed, which is probably overkill and in most cases adds too much noise to  the pump loop logs.

### CODE REVIEW

**Comment by alimhassam** [comment]
Feel free to decline this if this is actually needed, but i just thought it was not necessary, so i decided to clean it up.

**Comment by PieterGit** [comment]
Nope, I agree the amount of logging can/should be minimized, but we shouldn't ignore it and sent it to `/dev/null`. Best way is to integrate the ww init packet stuff into the openaps layer (e.g. `openaps use pump init`).  There used to be a situation in which the pump-rig communication failed, see 
https://github.com/oskarpearson/mmeowlink/issues/60 and the comments at the top of https://github.com/openaps/oref0/blob/a492c5eb04f8d70888b7c672321edac1736c8471/bin/oref0-radio-reboot.sh . The radio-reboot was a workaround if the ww init stuff hanged. I don't see a lot of those radio reboot errors anymore, so maybe this was caused by a oref0 situations where two processes both tried to communicate to the pump.

**Comment by mgranberryto** [comment]
@PieterGit For my own rig I run a patched mmeowlink that causes processes to block until the device is free when multiple devices try to access a radio.  I haven't submitted it in a PR because I didn't know if it would be generally useful and it introduces another dependency for mmeowlink but if it's fixing something it might be worth dusting it off.  Should I go ahead and make a PR?

**Comment by PieterGit** [comment]
Please let's dust the stuff off. I also have a branch somewhere with some openaps changes of proper integration of oref0-subg-ww-radio-parameters.sh into openaps which are unfinished. Not showing the commands that are sent makes it quite impossible/hard to debug oref0 ww init failures. The output of mmtune is still too verbose by the way.

```
# openaps mmtune

The CC111x is located at /dev/spidev5.1
RileyLink OK
Version: subg_rfspy 0.8
OK

The CC111x is located at /dev/spidev5.1
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
RileyLink OK
Version: subg_rfspy 0.8
SUCCESS
mmtune: pump://JSON/mmtune/monitor/mmtune.json
reporting monitor/mmtune.json
```

**Comment by scottleibrand** [comment]
@mgranberryto 👍 for dusting off your mmeowlink locking code: that would be useful to have in place for interactive troubleshooting.

@PieterGit I made your suggested comment-out change.  So I think this is good to merge if no objections.

**Comment by PieterGit** [comment]
No objections.

**Pull request merged**
