### PR TITLE
Prep for eventual 0.6.0 dev to master release

### PR DESCRIPTION
**Pull request by danamlewis**
**Note**: this next release will be a big release (from 0.5.3 to 0.6.0 to match the significant changes).

**WARNING:** This code is highly experimental and has many changes compared to 0.5.3. Do not implement this branch for testing unless you review the diff and plan to watch it closely. Also, do not change behaviors until you test the defaults of this branch. *There may be some things not yet documented here that need to be documented; please comment on this thread or in channel to help note what needs documenting.* **Make sure you follow this PR so you will get notifications about changes to this branch. It is still changing feature-wise, so you will want to update as new features and bug fixes are added in.**

**See the bottom-most comment for how to install and run 0.6.0.**

### CHANGED: **Default behavior change for carb absorption**
In 0.6.0, carb absorption now uses a `/\` shaped bilinear carb absorption model (replacing the previous `---` shaped constant model for predicting the future absorption of newly entered carbs that haven't shown any effect on BG yet.  As a result, the COB predBG purple prediction line immediately after entering carbs shows an S-curve shaped rise that starts out flat (in line with current BG trends), and then rises sharply after about an hour before flattening out.  

* A typical meal absorption time of 3h is assumed when carbs are first entered, which is then extended over time, so that oref0 gradually relies more on actual observed carb absorption as carbs are absorbed. When the carbs are first entered, remainingCATime is set to 3 hours. When 50% of carbs have absorbed, the remainder (that aren't seen to be absorbing already) are predicted to take another 4.5h. And as COB approaches zero, remainingCATime will approach 6 hours.
* As in 0.5.3, any actual observed carb absorption will be predicted to continue into the future.  The predCI assumed carb absorption described above only kicks in for carbs would not be absorbed within the current carb absorption time if the current carb absorption rate decreases linearly over that time.

### **Exponential Curves**
The code now supports three new configuration variables in preferences.json to allow exponential curves that better reflect the effects of insulin:

- curve, with legal values of blank, "bilinear", "rapid-acting" and "ultra-rapid"

1. if left blank or set to "bilinear", OpenAPS uses the old insulin activity model

2. If set to "ultra-rapid", the new curve model analyzed from publicly available data for Fiasp from Novo Nordisk is used, set to reach activity peak at 55 minutes
3. If set to "rapid-acting", the new curve model analyzed from publicly available data for Novorapid (Novolog) from Novo Nordisk is used. This curve should match well to Novorapid, Novolog, Humalog and Apidra and is set to peak at 75 minutes

- insulinPeakTime, with legal values from 35 to 120. The value defines the minutes from bolus to peak. Note if you don't set it, the above mentioned peak defaults are used.
- useCustomPeakTime, which must be set to "true" for the customized insulinPeakTime value to take effect

In order to use the rapid-acting or ultra-rapid curves, your pump must be set to 5 hour DIA, or longer. 6 hours is recommended as the starting point.

The details of the curve calculations and discussions can be found PR #568 

### **Enhanced SMB (eSMB)**

**Note**: for folks with tiny basals (in this case, say <0.5u/hr), exercise even more caution, as additional tweaks may need to be made to SMB-related portions of the code.

The default behaviour for SMB is that the max bolus that can be delivered is no greater than 30 mins of basal insulin. An additional preferences value, "maxSMBBasalMinutes", has been added to allow SMB to deliver a different amount of insulin as an SMB. This gives the ability to make SMB more aggressive if you choose. As with standard SMB, it is triggered by temp targets, carb entries and a pump bolus.

Increasing "maxSMBBasalMinutes" will allow the SMB functionality to deliver more insulin, earlier in the SMB process. 

"maxSMBBasalMinutes" can be added into `myopenaps/preferences.json`. It is recommended that the value is set to start at 30, in line with the default, and if you choose to increase this value, do so in no more than 15 minute increments, keeping a close eye on the effects of the changes. 

It is not recommended to set this value higher than 90 mins, as this may affect the ability for the algorithm to safely zero temp. It is also recommended that pushover is used when setting the value to be greater than default, so that alerts are generated for any predicted lows or highs.

**Other SMB adjustments include**: The preference of enabling SMB to always be on. (Leaving this as false (off) means the existing SMB toggles for carbs, temp targets, etc. will be what drives SMB behaviors.)

### Autotune adjustments

Autotune now tunes carb ratio directly, eliminating the previously known upward bias on ISF and carb ratio. This also smooths out mealtime basals based on surrounding hours when there's no data for tuning a particular hour due to meals.

**Behavior change recommended as a result**: You should be logging rescue carbs (carbs eaten for lows or predicted lows) so that Autotune knows about them. (Rescue carbs can be entered into Nightscout directly (i.e. NS website care portal, IFTTT buttons, etc.) or via the pump as long as they are accompanied by a 0.1 bolus. Any carb entry on the pump without a bolus is ignored by OpenAPS). 

## Troubleshooting

1. Make sure you've fully installed (see next section), including remembering to re-set your preferences.
2. If you're getting "not enacted" in Nightscout but are looping fine, update your Nightscout to the latest dev.

### No-git to reduce git-related errors (recommended install process)
0.6.0 also has support for no-git-based-flow, to reduce errors for most users. Moving forward, it'll default to no git. In order to install, you'll want to first move a copy of your old myopenaps directory, then run oref0-setup. So to install 0.6.0 with nogit, do the following:
1. `cd ~/src/oref0 && git checkout dev && git pull`
2. `npm run global-install`
3. `cd && mv myopenaps/ backupmyopenaps/`
4. `cd && backupmyopenaps/oref0-runagain.sh`
*(Note - if you call your copy something other than `backupmyopenaps`, you'll want to also match that name in step 4.)*
5. Update your preferences.
*As always, after an update/runagain, you'll also want to go in and [edit your preferences](http://openaps.readthedocs.io/en/latest/docs/While%20You%20Wait%20For%20Gear/preferences-and-safety-settings.html) as well. Check the code diff here to see what the optional preferences are for 0.6.0 - they are not in the main docs yet.*

### Testing list before release
- [ ] different time zones
- [ ] PI/TI stick rig
- [ ] WW pumps

### Release checklist
- [ ] Doc changes
- [ ] Release notes

### CODE REVIEW

**Comment by pampopcorn** [comment]
A note about proper naming (with or without quotes?) for the new preferences would be helpful.  Also, it would be nice to have a note that explicitly says... add this to preferences below last line (I assume?  does it matter where it comes in the list of preferences?

**Comment by scottleibrand** [comment]
https://github.com/openaps/oref0/pull/658 should make this moot as soon as we merge it, but until then, you'll need to add a preference line (anywhere in the list) that looks like `"curve": "rapid-acting"`.  Make sure that all of your preferences except the last one have commas after them.

**Comment by danamlewis** [comment]
@scottleibrand reminder about https://github.com/openaps/oref0/pull/534.

**Comment by scottleibrand** [comment]
Historical note: * *In an early version (now outdated) of the dev branch, the duration of this predicted carb absorption was modified by setting temp targets ( predicted carb absorption time for not-yet-absorbing COB was 4h; (low) temp target and have carbs on board or entered, expedited the carb absorption time to be 3 hours.; n "activity mode" (higher) temp target changed the remainingCI time to be >4 hours (as well as temporarily disabling SMB, as it does in 0.5.3); )*
* **This behavior of controlling carb absorption time via temp targets has since been replaced with more automatic heuristics described in the issue summary above.**

**Comment by danamlewis** [comment]
(Please move comments and activity over to https://github.com/openaps/oref0/pull/694 for the 0.6.0 dev testing notes)

**Comment by sjolundjohn** [comment]
I am running "oref0@0.6.0-dev1" on a WW rig that is using a TI stick, connected via USB to an Intel Development Board.

1) WW works no problem
2) TI Stick working with no issues.

**Pull request merged**
