### PR TITLE
DO NOT USE enableSMB_always or enableSMB_after_carbs with xDrip+, Libre, or similar

### PR DESCRIPTION
**Pull request by scottleibrand**
This PR adds a warning to lib/profile.index.js (the only place enableSMB_always is currently defined that people using DIY CGM receivers like xDrip+, LimiTTer, etc. should not enable enableSMB_always (or enableSMB_after_carbs), as there is a small risk of serious hypoglycemia if the sensor generates a long series of false high readings that do not come down normally as BG comes down.  The official Dexcom receivers and apps properly filter out such readings with a ??? when they're accompanied by a high noise level (as they almost always are).  Until such behavior is added to the DIY receiver options, they should not be trusted to trigger SMBs overnight.  The enableSMB_with_COB and similar options are safer with potentially erroneous CGM data, as they're self-limiting: high BGs will decay COB more quickly and shut off SMBs.  And of course enableSMB_with_temptarget can be used with temporary targets set to expire at bedtime.

### CODE REVIEW

**Comment by scottleibrand** [comment]
If we agree that these configurations should not be used with DIY CGM receivers, we should update the https://github.com/openaps/oref0/pull/650 PR notes as well, and make sure these warnings show up in any documentation we add for these new flags.

**Comment by sulkaharo** [comment]
Is the ??? behavior documented somewhere? My experience is Dexcom goes to ??? mode when there’s significant noise from the sensor, not when it’s been high for a long period.

**Comment by scottleibrand** [comment]
The ??? behavior is indeed for significant sensor noise.  I haven't seen any reports where the Dexcom receiver displays a high false reading for a significant amount of time, except in the cases of acetaminophen use.  However, there was a recent report (https://gitter.im/nightscout/intend-to-bolus?at=59d2bbb1b59d55b82365bed8) of xDrip+ reporting falsely high (>300 mg/dL) values for at least 15m with high noise, which would've been filtered by Dexcom's algorithms.  @drnoname82 has discussed this with @jamorham and was going to open an issue about adding this safety check to xDrip+, but I don't know if that has been opened yet.

**Comment by scottleibrand** [comment]
And it looks like it has now been opened: https://github.com/NightscoutFoundation/xDrip/issues/191

**Comment by tim2000s** [comment]
xDrip+ does generate a "High Noise" warning when it sees jumps to high levels and higher noise, I'm just not sure whether that gets into the xDrip+ data that OpenAPS receives.

**Comment by scottleibrand** [comment]
Per https://github.com/NightscoutFoundation/xDrip/issues/191 I think that's the problem: we just need that noise information to be communicated in the glucose.json file, ideally in a way similar to what Dexcom does.  (But if they choose to communicate it some other way, we should be able to adjust oref0 to handle that as well.)

**Comment by drnoname82** [comment]
Exactly. As far as I understand, there is currently no way to judge the quality of BG data from the MongoDB entries XDrip+ generates. However, the required information (noise level) is available locally within the XDrip app. So in my opinion XDrip should be changed to either a) upload high-noise readings as raw instead of SGV and provide the noise level or b) only upload low-noise readings

**Comment by sulkaharo** [comment]
Does someone have the appropriate json field names and value ranges for the noise information?

**Comment by sulkaharo** [comment]
Did AAPS also pull G5 info direct from the transmitter? I recall there’s no Dex receiver involved

**Comment by tim2000s** [comment]
It uses xdrip too.

**Comment by tim2000s** [comment]
This is the data:

[                                                  
  {                                                
    "direction": "Flat",                           
    "noise": 1,                                    
    "dateString": "2017-10-04T06:36:58.286000+01:00
",                                                 
    "sgv": 131,                                    
    "device": "xDrip-DexcomG5",                    
    "unfiltered": 138016,                          
    "filtered": 139904,                            
    "date": 1507095418286,                         
    "rssi": 100,                                   
    "_id": "59d4737ab3fa33c832373efb",             
    "type": "sgv",                                 
    "glucose": 131

**Comment by tim2000s** [comment]
@sulkaharo The issue lies in what xDrip uploads to NightScout. All values have a noise value of 1.

**Comment by sulkaharo** [comment]
@tim2000s Sure - can @scottleibrand or someone else using an official receiver confirm what the expected values are? Nightscout implementation based on earlier data from the G4 receiver is:

```
  rawbg.noiseCodeToDisplay = function noiseCodeToDisplay(mgdl, noise) {
    var display;
    switch (parseInt(noise)) {
      case 0: display = '---'; break;
      case 1: display = translate('Clean'); break;
      case 2: display = translate('Light'); break;
      case 3: display = translate('Medium'); break;
      case 4: display = translate('Heavy'); break;
      default:
        if (mgdl < 40) {
          display = translate('Heavy');
        } else {
          display = '~~~';
        }
        break;
    }
    return display;
  };
```

**Comment by sulkaharo** [comment]
Also - what is the definition of noise we're after and how does that definition map to above noise codes?

**Comment by jmcrawford** [comment]
This is the packet definition from xDrip.c:
`typedef struct _Dexcom_packet
{
	uint8	len;
	uint32	dest_addr;
	uint32	src_addr;
	uint8	port;
	uint8	device_info;
	uint8	txId;
	uint16	raw;
	uint16	filtered;
	uint8	battery;
	uint8	unknown;
	uint8	checksum;
	int8	RSSI;
	uint8	LQI;
} Dexcom_packet;`

Could noise be interpolated from the difference between raw and filtered values?

**Comment by jamorham** [comment]
I don't think noise and glucose values should be limited to Dexcom type data only.

Regarding the issue raised:

https://github.com/NightscoutFoundation/xDrip/issues/191

I am hopeful that this commit will go some way to resolving it:

https://github.com/NightscoutFoundation/xDrip/commit/b4b632fa993ccda71e45d2c2dc3b2794560275c5 

This change is available in the Oct 4th xDrip Nightly.

As far as looping is concerned, it isn't my area of expertise but I would say that with these changes, any reading with a noise value other than `1 / Clean` should be disregarded.

Not all data sources have a true "raw" value so I would prefer not to try to exclude sgv and provide just raw as a fallback as I think this could be misleading.

**Comment by jamorham** [comment]
Anyone had a chance to verify if this is working correctly? Thanks.

**Comment by drnoname82** [comment]
Unfortunately not because I could not get the latest nightly to work with my SW3 and had to go back to the latest beta. The few readings it reported all had low noise and so I could not test any further.

**Comment by jamorham** [comment]
Ok, try the Oct 6th nightly as I think this should resolve the SW3 issues.

**Comment by ceben80** [comment]
I do have enabled `enable enableSMB_always`, running xDrip+ last nightly with G4, but the rig is pulling the BGs directly from my phone (cgm=xdrip), no issues so far.

**Comment by tim2000s** [comment]
I can confirm variable noise reports in the xdrip uploads. Most of the time I see nois:=1 but when getting ⬆️⬆️ On xdrip it uploads with noise:=2.

**Comment by tepidjuice** [comment]
Wouldn't 'enableUAM' be effected similarly?

**Comment by scottleibrand** [comment]
No, UAM is much safer if SMBs are disabled: it just calculates insulinReq differently based on recent deviations, but won't be able to deliver insulin very fast via temp basals.

**Comment by sulkaharo** [comment]
So, instead of just warning, I propose changing determine_basal lines 63 to 66 to

```
var bg = glucose_status.glucose;
var noise = glucose_status.noise;
if (bg < 39 || noise >= 3) {  //Dexcom is in ??? mode or calibrating
rT.reason = "CGM is calibrating, in ??? state or noise is high";    
```

which should make the behavior between xDrip and Dexcom fairly consistent (assuming my read on the glucose object being used here is correct).

**Comment by tim2000s** [comment]
Based on the dying sensor I experienced with xdrip, this looks like it makes sense.

**Comment by sulkaharo** [comment]
https://github.com/openaps/oref0/pull/735

**Comment by scottleibrand** [comment]
Given that #735 is somewhat stalled, should we go ahead and merge this PR before 0.6.0 release?

**Comment by drnoname82** [comment]
I think this PR is worth merging, also because even after we get #735 to work, most XDrip users still use XDrip versions that do not provide noise data.

Do you have any idea why #735 might not work? It would be great to have that safety feature in 0.6.0 as well.

**Comment by tim2000s** [comment]
I’ve been running SMB Always On for the last couple of weeks with xdrip and sensor placement has resulted in a fair amount of compression lows. The upshot of this is that on the rebound I’ve seen SMBing of 0.1u before the levels stabiliise. This doesn’t appear to be anymore insulin than the high temp would have provided without it, especially given the suspend that’s taken place every time beforehand. 

There’s been no issue with the drops and any moodiness on the way down as suspension is fine. 

What I’ve yet to see with xdrip is a long series of false highs. Given the data is calculated and provided from the G5 transmitter (where the algorithm resides) this is perhaps unsurprising.

**Comment by scottleibrand** [comment]
Agreed, this should be less of an issue when using the xDrip with the G5 transmitter.  I don't think we need to change the warning, though, as anyone using DIY systems to read their CGM needs to really understand what they're doing before enabling SMB.

**Pull request merged**
