### PR TITLE
Add trend arrows to medtronic glucose data

### PR DESCRIPTION
**Pull request by cjo20**
As the title says, attempt to replicate Dexcom trend arrows from Medtronic data. The new command is intended to run on "raw" glucose data from the pump (`iter_glucose` output). 

I ran it locally as `./oref0-mdt-trend.js monitor/glucose_raw.json > monitor/glucose.json; `.
`monitor/glucose.json` can then be used as normal.

The script calculates the rate of change in blood sugar for all BG data in the last 15 minutes, then computes an average of those. An average change of < 1mg/dl/min is "flat", 1-2 is 45 degrees, 2-3 is single arrow, 3+ is double arrow.

Testing would be welcome.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Any idea what is up with https://travis-ci.org/openaps/oref0/jobs/193186056#L465 ?

**Comment by cjo20** [comment]
No idea. Ran mocha locally and I get 102/102 passing.

**Comment by scottleibrand** [comment]
K. It'll probably clear up on the next commit then.

**Comment by cjo20** [comment]
It looks like it's a problem with `dev`. I forgot to merge with upstream before I branched mdt-trend`. 
Running on https://github.com/cjo20/oref0
```
git checkout mdt-trend
mocha tests
```
gives 102 passing.

```
git checkout dev
mocha tests
```
Gives the errors shown in the travis build.

**Comment by scottleibrand** [comment]
This approach looks reasonable to me.  Is there any more testing you'd like done (maybe by someone with a MDT CGM) before merging it?  I'm fine either way, as it still requires manual configuration to use it...

**Comment by cjo20** [comment]
Up to you. I'd like it to be tested by someone with MDT before being put in oref0-setup, but as you said, it requires manual configuration. Probably easier to get someone to test it if it's merged with dev.

**Comment by daveewall** [comment]
I appreciate this addition here (it fixed an Apple Watch app that was expecting that to be in Nightscout as well), but something is definitely up with this (I'm on a purely MDT setup).  Most times it's correct, but sometimes it's wildly wrong (see attachment for example).

image

Not sure when the double up arrow started, but it was showing at least for 20 minutes before this screenshot was taken.

**Comment by cjo20** [comment]
To be able to debug that I'll need a copy of the glucose history JSON

**Comment by daveewall** [comment]
Hopefully this is the file you're looking for.  It started at the high point in the screenshot.

Had to zip it to upload.

[cgm-glucose.zip](https://github.com/openaps/oref0/files/870244/cgm-glucose.zip)

**Pull request merged**
