### PR TITLE
Backtick replacement

### PR DESCRIPTION
**Pull request by rkresha**
**Rationale**

Backtick command substitution \`..\` is legacy syntax with several issues.

- It has a series of undefined behaviors related to quoting in POSIX.
- It imposes a custom escaping mode with surprising results.
- It's exceptionally hard to nest.

$(..) command substitution has none of these problems, and is therefore strongly encouraged.

### CODE REVIEW

**Comment by scottleibrand** [comment]
LGTM.  Have you tested these changes on a working loop yet?

**Comment by rkresha** [comment]
I intend to rebuild a second rig with these changes tonight and I'll report back tomorrow.

**Comment by scottleibrand** [comment]
Ok, cool.  I might merge them to the oref0-setup branch and test them
tonight if I have time, too.

**Comment by scottleibrand** [comment]
Ok, merging.  This is a squash and merge, so you should merge dev back into your dev_vanilla branch (or start a new one) for future merges.

**Pull request merged**
