### PR TITLE
Cancel temp on error and > 55m w/ skip_netural_temps

### PR DESCRIPTION
**Pull request by scottleibrand**
Per #840, skip_netural_temps currently breaks the temp basal safety checks, because the neutral temp we attempt to set to fix the situation never gets set.

This PR fixes that by issuing a cancel temp when the safety checks fail, and making sure that such a cancel temp command actually gets passed through to the pump.

This also includes a new feature to cancel temp basals (unless they're low glucose suspend zero-temps) after 55 minutes past the hour if skip_neutral_temps is set, so that no temp basal will be running at the top of the hour and therefore the pump will not beep or vibrate.

### CODE REVIEW

**Comment by scottleibrand** [comment]
This needs testing both by someone using skip_neutral_temps and someone without it.  To test: `cd ~/src/oref0 && git fetch && git checkout set-temp && git pull && npm run global-install`

**Comment by davidwagaps** [comment]
Sorry, my notification to test was filtered out of my inbox so I just saw it. 
Question: Will the temp cancelled at :55 resume after the top of the hour?

**Comment by scottleibrand** [comment]
It won't necessarily resume the same temp basal that was running, as that would mean extending it to 30m, but it will set a new temp basal if needed after :00

**Comment by davidwagaps** [comment]
OK, so it's "cancel temp basal at :55 and prevent setting temp until :01"
at which point system will determine if basal is needed (like at any other
time).

**Comment by davidwagaps** [comment]
Started testing yesterday evening. So far so good. I'll post more once it's been 24hrs.

**Comment by davidwagaps** [comment]
1. Does NOT cancel zero temp at :55 - pass
2. Otherwise cancels temp at :55 - pass
3. Resumes normal operation at :00 (sets temp if necessary sometime after
that) - pass
4. Does not set temp if temp = current pump basal setting (original "skip"
functionality) - pass
5. "reason":"Warning: currenttemp rate 0 != lastTemp rate 2.35 from
pumphistory; " - no longer appears in pill or log: pass
(Also posted in https://github.com/openaps/oref0/issues/840)

**Pull request merged**
