### PR TITLE
Add support to identify which bluetooth adapter to use

### PR DESCRIPTION
**Pull request by jpcunningh**
This is a work in progress to enable the user to use an external Bluetooth adapter in lieu of the builtin Bluetooth.

### CODE REVIEW

**Comment by jpcunningh** [comment]
@scottleibrand, I believe this one is ready.

**Comment by scottleibrand** [comment]
Just to confirm: this maintains the current behavior unless the preference string is added?

Looks like there's also a merge conflict now.

**Comment by jpcunningh** [comment]
@scottleibrand, yes, this preserves the current behavior that defaults to hci0 unless the preference string is added (I just re-verified on one of my rigs).

**Comment by jpcunningh** [comment]
The merge conflicts are corrected.

**Comment by scottleibrand** [comment]
Not sure why we're getting a Travis failure.  I'll try closing and reopening the PR to force it to try again.  The failure was:

```
not ok 189 IOB should calculate IOB without counting time pump suspended in middle of basal
  AssertionError: expected -0.01 to be 0.235
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (tests/iob.test.js:973:38)
```

**Pull request merged**
