### PR TITLE
Floating carbs / UAM

### PR DESCRIPTION
**Pull request by scottleibrand**
See below.

### CODE REVIEW

**Comment by scottleibrand** [comment]
This is still a WIP.  Opening PR to start documenting what has changed, and add preferences.json feature switches for more of the new stuff.

**Comment by scottleibrand** [comment]
Major changes in this PR (roughly in `git diff` order):
 - Updates to oref0-pump-loop.sh to wait up to 4 minutes for new BG before each loop, and improve multiple-rig cooperation.
 - Autotune: mitigate tendency to overestimate ISF by using a weighted average of fullNewISF and pumpISF.  See TODO below.
 - UAM: calculate deviationSlope, use that to predict how fast currentDeviation will decay to zero, and generate UAMpredBGs from that.
 - SMB: add preferences.json entries to enableSMB (and thereby enableUAM) in various ways
 - Ignore future temp basals in predBGs to reduce predBG (and temp basal) oscillation.  Truncate all BG predictions at 3.5 hours.
 - Rather than using min_5m_carbimpact, assume that 2/3 of remainingCarbs, capped at 90, will absorb over the next 4h.  This helps SMB/AMA get extra insulin started as soon as carbs are entered if no manual bolus has been done (yet).  See TODO below.
 - UAM/SMB/AMA: use predBGs from 60m to 3.5h for calculating COB and UAM minPredBGs, and from 90m for minIOBPredBG.  The minPredBGs determine insulinReq, and therefore how fast to SMB when predictions are up and to the right.
 - UAM: when active w/o announced carbs, use the max(minIOBPredBG,minUAMPredBG) for dosing.  When COB is present, average minIOBPredBG,minUAMPredBG and then do a weighted average with minCOBPredBG based on how many carbs remain as COB.  This allows SMB to deal appropriately with miscounted carbs, without overreacting to up and to the right UAM predictions: if a carb estimate is provided, it trusts that at the beginning, and gradually transitions to using observed deviations to drive dosing as COB decays.  
 - SMB: if naive_eventualBG < 40, always set (at least) a 30m zero temp for hypo safety
 - SMB: allow SMBs every 3 minutes to handle variable pump-loop timing
 - Only use CGM data from the same device as the most recent BG data point.

TODOs:
 - Add autotune ISF adjustmentFraction to preferences.json.  Default to 0.5?
 - Add remainingCarbs cap and/or fraction to preferences.json.  Default to 0 to disable?

**Comment by scottleibrand** [comment]
If anyone wants to volunteer to update the unit tests to reflect the new behavior, please speak up.  If not, I might just comment them out as unhelpful.

**Comment by scottleibrand** [comment]
I think this is now ready for review.

**Comment by danamlewis** [comment]
Ok - need 1-2 other people to eyeball the code and give this PR a thumbs up for merging SMB (and other oref1 stuff) into dev. @tim2000s, @ceben80, @cjo20, or anyone else - please give this an eye and let us know if you spot anything that is a blocker from getting this into dev this week. (Also working on a specific "here's what and how we need to test in dev" list, but we just need general code review here on this PR before we get to that stage)

**Comment by tim2000s** [comment]
I've had a run through this this morning. Nothing jumps out at me as looking wrong. One comment though. I've been running it on a dev rig and having a lot of issues on a ww rig with the below:

```
Starting supermicrobolus pump-loop at Mon May 1 10:31:03 BST 2017 with 18 second wait_for_silence:
Waiting up to 4 minutes for new BG: jq: error: null and number cannot be divided
date: invalid date ‘@’
glucose.json newer than pump_loop_completed
+ echo

+ echo The CC111x is located at /dev/spidev5.1
The CC111x is located at /dev/spidev5.1
+ cd /root/src/subg_rfspy/tools
+ case "$2" in
```
And then dropping into mmtune. I've also seen the following after trying to do and smb-enacted.json, which is resulting in nothing being sent to the pump.

```
{"carbs":24,"boluses":9,"mealCOB":0,"currentDeviation":4.96,"maxDeviation":16.65,"minDeviationSlope":-1.31}
{"iob":1.807,"activity":0.0424,"bolussnooze":0,"basaliob":1.169,"netbasalinsulin":1.2,"hightempinsulin":2.1,"microBolusInsulin":0,"microBolusIOB":0,"time":"2017-05-01T09:33:11.000Z","lastBolusTime":1493626627000}
{"delta":-4,"glucose":161,"short_avgdelta":-4.1,"long_avgdelta":-4.18}
{"duration":7,"rate":3.125,"temp":"absolute"}
Basal unchanged: 1; target_bg unchanged: 86; sens unchanged: 41.4
naive_eventualBG: 86, eventualBG: 114
Adjusting targets for high BG: min_bg from 86 to 80; target_bg from 86 to 80; max_bg from 86 to 80
Carb Impact: 4.7 mg/dL per 5m; CI Duration: 0 hours; remaining 4h+ CI: 0 mg/dL per 5m
Accel. Carb Impact: 10 mg/dL per 5m; ACI Duration: 0 hours
UAM Impact: 4.6 mg/dL per 5m; UAM Duration: 0.3 hours
minPredBG: 95 minIOBPredBG: 105 minCOBPredBG: 999 minUAMPredBG: 85 COB: 0 carbs: 24
naive_eventualBG 86, 0m zero temp needed; last bolus 76.7m ago (1493626627000).
Checking deliverAt: 2017-05-01T09:33:49.816Z is within 1m of current time: Mon May  1 10:33:51 BST 2017
and that smb-suggested.json is less than 1m old
enact/smb-suggested.json: {"insulinReq":0.23,"bg":161,"reservoir":"149.7","temp":"absolute","snoozeBG":114,"predBGs":{"UAM":[161,156,149,142,134,127,121,115,110,106,103,100,97,95,93,91,89,88,87,86,85],"IOB":[161,157,152,148,143,139,135,131,128,125,122,120,117,115,112,111,109,108,107,106,105]},"minPredBG":95,"IOB":1.807,"reason":"COB: 0, Dev: 28, BGI: -8.78, ISF: 2.3, Target: 4.4, IOBpredBG 5.8, UAMpredBG 4.7; Eventual BG 6.3 >= 4.4, insulinReq 0.23; microbolusing 0.1U. temp 3.125 >~ req 1.45U/hr","COB":0,"eventualBG":114,"units":0.1,"tick":-4,"deliverAt":"2017-05-01T09:33:49.816Z"}
No smb_enact needed. Temp refreshed: monitor/temp_basal.json: {"duration":7,"rate":3.125,"temp":"absolute"}
RefreshOptional feature meal assist disabled: not enough glucose data to calculate carb absorption; found: 0
ed pumphistory
pumphistory.json: "TempBasalDuration 2017-05-01T10:09:46 head[2], body[0] op[0x16]"
Checking pump clock: "2017-05-01T10:33:34+01:00" is within 1m of current time: Mon May  1 10:34:17 BST 2017
and that pumphistory is less than 1m old.  Temp refreshed
Could not parse input data:  [TypeError: Cannot read property 'date' of undefined]
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/invoke.py", line 48, in main
    reporters.Reporter(report, device, task)(output)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/reporters/__init__.py", line 33, in __call__
    self.blob = self.serialize(data)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/reporters/__init__.py", line 31, in serialize
    return self.method.serialize(render(data), self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/process.py", line 56, in prerender_json
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
I'm struggling to find issues with any files and oddly, I don't seem to be able to stop the pump-loop processes even with killall.

**Comment by tomasboudr** [comment]
Would it be annoying to change 'EnableSMB' to 'EnableSuperMicroBoluses' in preferences.json? SMB is an overloaded acronym and there is no need to not be more verbose for preferences that important.

**Comment by scottleibrand** [comment]
There's also an enable flag you have to pass to oref0-setup, which requires the long form.

**Comment by danamlewis** [comment]
Merged to dev! Please see https://github.com/openaps/oref0/pull/424#issuecomment-298807656 and https://github.com/openaps/oref0/pull/424#issuecomment-298809102 with regards to how to test in dev.

**Pull request merged**
