### PR TITLE
Add code to run js code on a shared server.

### PR DESCRIPTION
**Pull request by tzachi-dar**
This saves initilaztion time.

Worked for a day, which means testing only started.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
This is the initial version of the code that runs on a shared node.

ns-status and oref0-normalize-temps have changed.

This contains the changes to the js files, but does not contain changes to shell script to start the node, and make sure it stays alive.

**Comment by tzachi-dar** [comment]
As for running "json" commands:
json itself can not be used directly from another module.
So, our options are:
1) make a short change to allow it to support remote calls.
2) Since we are only making use of a small part of it, implement this outself. (should also be a short code - this is code to go over json files and filter it).
3) continue with https://github.com/openaps/oref0/pull/1342 (assuming that all issues there have been solved)

**Comment by Dune-jr** [comment]
Thank you for that work, @tzachi-dar! Looking forward to test that

**Comment by tzachi-dar** [comment]
I have added some more code to harden the solution.
@Dune-jr you can start testing if you wish.
Please note that you need to make sure that oref0-shared-node-loop is on the path.
Right now it is on bin/oref0-shared-node-loop.sh so you will probably have to create a symbolic link for it.

@scottleibrand still waiting for your input regarding https://github.com/openaps/oref0/pull/1350/#issuecomment-573369555
All solutions will work well, but still looking for your prefered method to solve the issue.

**Comment by scottleibrand** [comment]
normalize-temps error:
/home/sleibrand/src/oref0/bin/oref0-normalize-temps.js:64
   var result = oref0-normalize-temps(command)
                               ^

ReferenceError: oref0 is not defined
    at Object.<anonymous> (/home/sleibrand/src/oref0/bin/oref0-normalize-temps.js:64:32)

**Comment by tzachi-dar** [comment]
This is replaced by https://github.com/openaps/oref0/pull/1352

**Pull request closed without merging**
