### PR TITLE
Update device.json

### PR DESCRIPTION
**Pull request by ceben80**
Due to azure 24 h quota 288 BG query should be sufficient otherwise azure limit will exceed while querying 1000 BGs per minute

### CODE REVIEW

**Comment by scottleibrand** [comment]
Looking at this more closely, I don't think this device is used any longer, so that can't be what caused you to exceed your azure limits.  Per https://gitter.im/nightscout/intend-to-bolus?at=57eef1d2be5dec75500d5b50 we need someone to start working on switching the ns-loop upload stuff over to use the new ns device, and while we're at it we should start removing devices like this that are no longer used.

**Comment by ceben80** [comment]
before oref0.setup.sh I was working with that's a good approach?

[device "ns"]
fields = oper remote input
cmd = nightscout
args = ns https://xxx.azurewebsites.net xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
								
[report "monitor/glucose.json"]
oper = get
use = shell
remote = entries/sgv.json
reporter = JSON
json_default = True
device = ns
input = count=288
remainder =

**Comment by scottleibrand** [comment]
oref0-setup does this:

https://github.com/openaps/oref0/blob/dev/lib/oref0-setup/report.json#L32-L43

**Comment by scottleibrand** [comment]
That way, if you have multiple receivers, it will download more than 288 data points, and if you have one receiver with gaps, 24h will be less than 288.

**Comment by ceben80** [comment]
oki, understood

**Pull request closed without merging**
