### PR TITLE
Optimize oref0-pump-loop, and bug fixes

### PR DESCRIPTION
**Pull request by scottleibrand**
More refactoring to optimize oref0-pump-loop to run faster, especially on the Pi Zero W.

Also contains some bug fixes, including:
- Fix some incorrect "skipping bolus wizard entry with carbs and no insulin" messages where the bolus wizard and corresponding bolus record are logged with timestamps that differ by 1 second.  The fix in commit 2eee14b6e44493e9f0442f6b33e980480290a325 is to look for records up to 1s apart.
 - Fix the calculation of bwCarbs: bolus wizard carbs weren't being counted as either bwCarbs or nsCarbs, so oref0 was not properly disabling SMB for A52 risk reduction.  Fixing that also required fixing the variable reference to profile.A52_risk_enable.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Added some bug fixes: see updated description above.

**Comment by PieterGit** [comment]
Is this branch ready to test? ` www/app.pyc` should not be added to version control.

**Comment by PieterGit** [comment]
pump loop won't resolve errors and keeps mmtuning,  log excerpt 
```
Preflight OK. Profile less than 60m old and valid. RefreshValueError: need more than 0 values to unpack

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/myopenaps/monitor/pumphistory-merged.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/src/oref0/bin/oref0-calculate-iob.js:43:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Couldn't calculate IOB
oref0-pump-loop failed. pump_loop_completed more than 15m old; waiting for 40s silence before mmtuning
Radio ok. Listening: .No interfering pump comms detected from other rigs (this is a good thing!)

```

**Comment by scottleibrand** [comment]
@PieterGit I just committed 134458cffc74664a5d829ebf4d5ccd172a64275e which might help with your pumphistory-merged.json issue.

**Comment by scottleibrand** [comment]
Does anyone else want to test anything specific on this before I merge it to dev?  If not, I think it's about ready.

**Pull request merged**
