### PR TITLE
Reason improvements

### PR DESCRIPTION
**Pull request by alimhassam**
added some missing unit conversions, and added carb ration to the reason field

### CODE REVIEW

**Comment by scottleibrand** [comment]
This looks fine to me, but I won't be able to test it with mmol/L.  Maybe if you could just paste the resulting log lines from your pump-loop.log so I can make sure they look reasonable, that'd be good enough to merge to dev for wider testing there?

**Comment by alimhassam** [comment]
sure, i'll post a screenshot of NS reason field, and a log excerpt

**Comment by alimhassam** [comment]
image

**Comment by scottleibrand** [comment]
Hmm, is convert_bg() adding newlines?  If so, that won't really work.  Or is that something custom you added to your NS?

**Comment by alimhassam** [comment]
no, sorry, my version of NS is replacing ", " with "<br/>"

**Comment by alimhassam** [comment]
and i just realised i put the wrong screenshot, i moved CR after ISF in the latest push

**Comment by scottleibrand** [comment]
Ok, good.  I don't think we'll want to change the default OpenAPS pill behavior to match that, but it wouldn't hurt to start discussion around what we actually want it to look like.

**Comment by alimhassam** [comment]
sure, we can discuss once i do the pr, i already find this more readable so added the quick hack, but there is for sure room for even better improvement as someone suggested in i-to-b forum.

**Pull request merged**
