### PR TITLE
Merge latest meal-assist into dev

### PR DESCRIPTION
**Pull request by scottleibrand**
Lots of updates here.  @danamlewis and I have been running this for several weeks now, so it's time to get more people testing it.

Changes are:

Phase in mealAssist and wtfAssist smoothly (rather than turning it on and off at a binary threshold)
#61 Meal assist "simulated extended bolus" high temps
#58 Automatic sensitivity/resistance detection
Script to generate oref0.html (displaying the same data as pebble.json, but in basic HTML format)

If anyone else has been running on the meal-assist branch and can give this a :+1: for merge to dev, I'd like to get it merged so everyone running meal assist on dev can start testing the new behavior.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Will need to hold on merging this until we do more testing per #77.

**Comment by scottleibrand** [comment]
#76 is also a blocker for merge.

**Comment by scottleibrand** [comment]
All blockers have been taken care of.  If I can get a couple :+1:, I'll go ahead and merge this to dev.

**Comment by danamlewis** [comment]
Thumbs up from the primary guinea pig, but need some secondary :+1: as well.

**Comment by amazaheri** [comment]
:1:

**Comment by jasoncalabrese** [comment]
Been running on all rigs since Saturday, but haven't had a chance to setup auto-sens

**Comment by amazaheri** [comment]
:+1:

**Pull request merged**
