### PR TITLE
PR for dev to master in prep for 0.5.0 release

### PR DESCRIPTION
**Pull request by scottleibrand**

### CODE REVIEW

**Comment by scottleibrand** [comment]
Things we need tested:

Flash jubilinux and set up a rig from scratch using all the oref0-setup permutations you have available to test, and make sure you can get looping without running into any errors.  In particular, we've made changes to:
 - Nightscout uploads and downloads
 - oref0-pump-loop (instead of the old openaps pump-loop alias)
 - WW radio settings (and how the cc1110 radio chip gets reset, for both WW and NA pumps)
 - xdrip first-upload
 
After setting up your rig your preferred way, keep a close eye on the standard algorithm and make sure it's behaving as you've come to expect / desire.

If you're interested in testing out any of the new algorithms, then after at least a few days, enable features of interest one at a time (i.e. in oref0-setup and/or preferences.json) and verify the new behavior works well, and as you'd expect.  See also https://openaps.org/reference-design/ and  https://github.com/openaps/oref0/pull/452#issuecomment-298200212 for more details on many of those.

**Comment by scottleibrand** [comment]
Advanced testing:

Once https://github.com/openaps/oref0/pull/452 is merged, and in addition to the oref0-setup tests detailed above, we'll also need some volunteers to test the new oref1 features, such as as supermicroboluses (SMB), unannounced meals (UAM, aka "floating carbs"), and "remainingCarbs" projections.

 - To test SMB, you'll need to run oref0-setup with a "microbolus" enable flag to configure it to use SMB in oref0-pump-loop, and also enable the appropriate enableSMB settings in preferences.json.  I would enable them one at a time, in your preferred order, and then closely observe the behavior (via both Nightscout and pump-loop.log) in the enabled situation.  In addition to testing it in "normal" situations, pay special attention to how it behaves in more extreme situations, such as with rescue carbs (announced or not), post-meal activity, etc.
 - Another optional feature that might help your SMB (or AMA) deal with entered meal carbs is to set an appropriate "remainingCarbsCap".  That should be set to no larger than a typical large meal, and no larger than the number of carbs you'd typically be able to absorb over 4 hours.  There is a hard-coded maximum of 90 grams, so don't bother setting anything higher than that.  If remainingCarbsCap is set to something above zero, then in situations where carbs have been entered but carb absorption has not yet begun, oref1 will assume that 2/3 of those carbs will be absorbed evenly over the next 4 hours.  As a result, oref1 can begin SMB'ing (or AMA high-temping) more so than it otherwise would immediately after entering carbs.  If carbs are entered early, this can also act more aggressively than "eating soon", based on trusting that you really will eat (most of) the entered carbs at some point before all the insulin kicks in.
 - To test UAM, you'll need to enableUAM in preferences.json.  UAM can be enabled without SMB, but it won't be very effective without enableSMB_with_bolus.  You'll probably also want to upgrade your Nightscout to a version that includes https://github.com/nightscout/cgm-remote-monitor/pull/2564  To test UAM, you'll first want to be familiar with SMB's "normal" behavior, and then test, with a small meal, giving an up-front bolus (of more than 30m worth of basal, so it can be distinguished from an SMB) and *not* entering carbs.  You'll probably also want to do an "eating soon mode" temporary target or bolus beforehand.  You can then observe, by watching the NS purple line predictions and the pump-loop.log, whether your OpenAPS rig is SMB'ing appropriately when it starts to see UAM carb impact.

**Comment by danamlewis** [comment]
^ Please note to us which situations you have tested & confirmed to be working - we'd like to make sure a few people have tested each combination of scenarios for a variety of setups (CGM types, ww/not, etc.). Please do turn things on one at a time and observe over a couple of days or set this up on a test rig. Do NOT turn on everything at once; a) easier to end up unhappy b) not helpful for helping us get everything to master :) by being able to validate nothing breaks by going one at a time.

**Comment by tim2000s** [comment]
Please note: Whilst testing Floating Carbs/UAM, it is best to avoid using correction boluses. Instead, set a low temp target and allow oref1 to correct for you. 

If you do use a correction bolus and have  enableSMB_with_bolus set to True, it may result in additional boluses.

**Comment by Kdisimone** [comment]
First test:  Rig number 1 was on master branch.  Updated & switched to dev branch.  Ran oref0-setup.sh fresh (not through rerun-script) and looping just great.  No problems.  Uploads only show microSB mention in the pump-loop for where IOB is calculated (and that part is =0).  Otherwise SMB does not show in logs (so that's good...since I didn't enable it yet on that rig).

**Comment by Kdisimone** [comment]
Second rig:  Fresh flash of jubilinux 0.1.1 and have installed dev branch including the --btmac extension.  Noticed it installed Bluez 5.44 (so we should update docs when this merges to note that it's not 5.37 anymore).  Noticed some preinstalled aliases (nice!  will need to update docs for that too.  And I may add to the list of the new ones via PR I think?)

**Comment by Kdisimone** [comment]
and not that it is necessarily on topic...but Rig #2 paired and works with bluez 5.44 on iPhone no problems.

**Comment by scottleibrand** [comment]
Notes on what the different things do in preferences.json can be found as code comments here: https://github.com/openaps/oref0/blob/dev/lib/profile/index.js

**Comment by francesc0-cgm** [comment]
Yesterday night using smb maybe for too much activity during the day my son went low. After correction during the night he raised a bit. Then it made 3 smb during the night and my son went low. I'm pretty sure my isf and my basals are ok during the night (auto tune). For kids seems a bit too strong...
img_0142

**Comment by francesc0-cgm** [comment]
Should be interesting adding a feature about avoiding smb if a low occurred in the past hours.

**Comment by francesc0-cgm** [comment]
Seems that with high sensitivity and low insulin needs it is not so reliable it has low temped making him raise then with cob at 0 it shouted 3x0.1 making him goes low. Settings are ok, with oref0 never had too much problems.
img_0147

**Comment by tim2000s** [comment]
Hi @francesc0-cgm - Thursday night into Friday morning - there seem to be a lot of lows there too. Was that oref0 or oref1?

**Comment by francesc0-cgm** [comment]
It was loop with a bad sensor


In data 6 Maggio 2017 1:52:47 PM Tim Street <notifications@github.com> ha 
scritto:

**Comment by francesc0-cgm** [comment]
At lunch a very big meal with a lot of carbs...COB became 0 when it was not and it stopped to smb and this is the result, with a set failure due to prolonged zero temping (he is 345)

img_0150

**Comment by sulkaharo** [comment]
@francesc0-cgm the current COB algorithm considers each meal for a max duration of the DIA (the insulin activity duration). Looking at the graph, I'd assume the COB went to zero because there was so much time from the meal. Do you have UAM (unannounced meals) enabled? Were all the carbs marked, or is some missing from the graph? Are you sure there wasn't a bubble in the tubing? What's the sensitivity set at (I'd assume the loop would have stopped zero temping sooner given the >300 points BG)?

**Comment by francesc0-cgm** [comment]
@sulkaharo I have my DIA set to 4 hrs. From LOOP experience i know that pasta has an absorption of about 6 hours, this could be the first problem. All carb where inserted correctly. UAM was off, i was just testing SMB. No bubble in the tubing but with those BGs i think the set had a failure. The sensitivity on the afternoon is set at 170 (on LOOP and OpenAPS) and never had this type of problems. If you look at the pic you could see SMB made it 0 temping also around 300s...this is due to low basal rates of my son linked to high values of sensitivity. Of course maybe he doesn't start to drop before due to the set failure

**Comment by scottleibrand** [comment]
@francesc0-cgm - Recapping our conversation in https://gitter.im/nightscout/intend-to-bolus, it looks like the site failure was the cause of the rise to 300, rather than the effect of the zero temping on the way up (as SMB was active, there was never any period of zero insulin delivery then).  However, the 10am to noon CEST zero temping, caused by carb absorption deviations dropping from 23 mg/dL/5m to -4 mg/dL/5m over the course of about 10 minutes at 10am CEST.  Given the 0.175U/hr basals, that is too abrupt of a shift for oref1 to deal with except by really extended zero temping (which was insufficient to prevent a low in this case).  It might be best to leave SMB disabled in situations where the basal is lower than 0.4U/hr, to ensure that the maxBolus allowed by SMB (30m of basal, so 0.2U at 0.4U/hr) is higher than the minimum microbolus oref1 can deliver (0.1U).

**Comment by alternateal** [comment]
Floating Carbs / UAM - So using a 754 WW with a G5, enableSMB_with_bolus and enableUAM set in preferences - single rig rather than multiple rigs, additional code added to Nightscout to show the UAM line. Bacon roll announced with a 2.5u correction, no carbs entered in the system - three micro boluses driven by system.

screen shot 2017-05-07 at 09 04 11

**Comment by PieterGit** [comment]
Testing floating Carbs / UAM / SMB (all options). 
Only during daytime on fixed/home/test single rig where I can monitor pump loop.
Test rig is RPI3/TI USB/754WW/Dexcom G4 (USB). 
Found some RF pump issues, but might be due to my setup.
I don't see those RF issue with dev and SMB disabled.
Working on getting my token based authentication working, so I can reinstall on a Edison test rig soon.
Note: that I think it would be good if we find UAM/SMB issue to create a seperate GitHub issue, 
because otherwise this thread will be cluttered.

**Comment by Kdisimone** [comment]
I don't think my SMB is working like I expected...perhaps.  I had thought that smb was designed to, in essence, front-load a correction rather than use the 30 min long temp basal to deliver it. The size of the front load depended on how much it could safely suspend to recover if it isn’t needed. I’m not seeing that behavior. Instead, 120 min basal suspensions seem to be the normal and unwavering.  It's happened on there meals the same way.  When SMBs have picked back up as BGs rise after a meal, the loop still continues to have a temp basal suspension, even when the SMBs are being delivered. Would seem to me that if we are correcting for a rising BG that is going to be above target…at least ending the suspension would be appropriate in light of an SMB being given.
img_2743
img_2744
img_2745

**Comment by Kdisimone** [comment]
This was on a 723 with the SMB and UAM features all enabled for the day.  Temp basals have been at 0 for whole 2 hours several times

**Comment by scottleibrand** [comment]
The behavior @kdisimone is seeing is SMB working correctly as intended.  See https://gitter.im/nightscout/intend-to-bolus?at=590fce909d90dc7a1c573974 for the full explanation.

**Comment by danamlewis** [comment]
(Adding notes to a branch-in-waiting of the docs about new oref1-related variables - see https://github.com/openaps/docs/pull/777/files#diff-30efe825c13d049e1c2d6bf2b4e0bfad)

**Comment by danamlewis** [comment]
If you have questions/issues related to turning on and testing oref1 features (SMB, UAM, etc.), please log them on this issue (https://github.com/openaps/oref0/issues/461).

**Comment by ericfeibelman** [comment]
Is there a setting to make SMB a little less aggressive. In my testing, it often overcompensates and a low blood sugar follows.

**Comment by scottleibrand** [comment]
There are lots of settings that affect SMB's aggressiveness.  Let's jump over to Gitter to discuss.

**Comment by danamlewis** [comment]
Pushover merged to dev, which includes the following: 
    oref0-online updates for stability
    oref0-set-device-clocks if pump clock is >1m off
    oref0-set-system-clock if determine-basal complains it's set incorrectly
    support for oref1 pushover alerts of insulinReq and carbsReq
    allow non-SMB code paths to set temps up to 120 minutes when needed
    allow non-zero temps in SMB mode when lastCOBpredBG > target_bg
    don't SMB if basal is < 0.3 U/hr (if 0.1U SMB represents >20m of basal)

**Comment by danamlewis** [comment]
For anyone who's been testing dev, please double check your autotune files. If you see CSF as 0, please re-pull dev to grab the fix for this (per https://github.com/openaps/oref0/issues/480, now resolved and merged to dev).

**Comment by danamlewis** [comment]
Just merged in the re-work of oref0-setup.sh which now includes:
* Formatting and colors for readability. 
* AMA, autosens, and autotune are now out of advanced features
* Advanced features sub-menu now holds Pushover setup prompts, and a reminder to manually enable oref1 features if you want them.
* maxIOB will now be set in oref0-setup, with a note about recommending 0 or 1 hour of basal to newbies; it defaults to zero if not set.

**Comment by danamlewis** [comment]
Keeping this thread up to date, here's what we need to do before final rounds of testings before a release:

- Some more docs work - need help beefing up the oref1 page; also want to add notes to this release/the docs that better explain the few changes to basic oref0 behavior over current master. (Mainly, how the addition of remainingCarbCap impacts basic oref0, and how to toggle that.)

- Also need to tackle https://github.com/openaps/oref0/issues/443, which I think is the last code-related blocker before this release. Help welcome to tackle this; we need to do https://github.com/openaps/oref0/issues/419 and https://github.com/openaps/oref0/issues/443 to accomplish.

**Comment by PieterGit** [comment]
I also think https://github.com/openaps/oref0/pull/470 is ready to merge to dev and release. @ceben80 will test it soon. More testing is appreciated! I'm running it more than a week on it and cannot find errors. Let's give users a possibility to secure their CGM data. Initial docs are available at https://github.com/PieterGit/docs/blob/tokenbased/docs/docs/walkthrough/phase-1/nightscout-setup.md#switching-from-api_secret-to-token-based-authentication-for-your-rig

My wishlist for this month (in order of my priorities) is:
- improve mmtune and init / error behaviour (because I got some situations where a manual mmtune was required)
- improvements to pancreable pebble integration (carsbsReq, insulinReq), prototype code is available, needs integration in oref0
- carbsReq for more situations. I think this would be great to prevent hypo's, see https://github.com/openaps/oref0/issues/483
- don't charge dexcom g4 when connected to USB (requires dexcom_reader release, see https://github.com/PieterGit/dexcom_reader/blob/master/dexcom_reader/bat.py )
- cgm calibration dexcom_reader issue https://github.com/openaps/dexcom_reader/issues/16 (probably won't make 0.5.0 release because it's a though problem)
...

**Comment by PieterGit** [comment]
To avoid errors such as https://github.com/openaps/oref0/issues/500 I think it would be good only to use stable releases on the master branch only (no master checkouts). It's good to use latest master branches in dev when we are at the beginning of a release cycle.   Since I think we're about to release a new version, we should now change the external dependencies such as mraa to stable versions now.

We should also make sure that there are no outstanding non released commits on openaps project.s I think before releasing oref0, we should first release our own dependencies such as openaps and dexcom_reader.

**Comment by danamlewis** [comment]
Ok: I think we've gotten through all the major remaining blockers, and we should freeze and do final testing to get 0.5.0 released. What this version (in dev) currently includes:
 
* Improved oref0-setup.sh experience (colors, etc.)
  * AMA is always on by default - no longer prompts in the script
  * Autotune and autosens moved out of advanced features menu
  * max_IOB will be prompted for
* oref1 features (SMB, UAM) included, and can be set up via oref0-setup.sh under advanced features
  * oref1-related pushover is also under advanced features
  * oref1 also includes insulinReq and carbsReq, which will show in the pill even if Pushover not enabled
  * SMB requires autotune folder to be present on the rig
* oref0-setup installs bluez 5.44 if needed unless version 5.37 or newer is present 
* oref0-online/wifi related improvements for connectivity
* oref0-reset-git and logrotate improvements to help with full disks
* oref0-set-device-clocks if pump clock is >1m off
* oref0-set-system-clock if determine-basal complains it's set incorrectly
* Bolus wizard carb entries without a bolus will now be ignored
* Fix for zombie (reappearing) carbs
* Assume remainingCarbs (carbs we’re not yet seeing deviations for) will absorb over 4h
* Various improvements for WW pumps
* Other feature additions:
  * Rewind_resets_autosens resets autosensitivity to neutral for a while after each pump rewind
  * Autosens_adjust_targets: when autosens detects sensitivity/resistance, also adjust BG target accordingly
  * adv_target_adjustments: lowers target automatically when BG and eventualBG are high
  * unsuspend_if_no_temp: if enabled, pump will un-suspend after a zero temp finishes
  * autotune_isf_adjustmentFraction: keeps autotune ISF closer to pump ISF via a weighted average of fullNewISF and pumpISF.  
  * allow non-SMB code paths to set temps up to 120 minutes when needed
  * Nightscout token auth

Let's begin final testing to prepare for the release. We need the following user setups to test:
* WW pump user
* Medtronic CGM user
* Pi/TI user
* xDrip user
* with SMB/UAM 
* without SMB/UAM

If you test, make sure to comment here with your setup description (suggestion: pump model/CGM type/rig type), and which feature combinations you tested with/out, and any issues. 

To grab the latest dev:
1. `cd ~/src/oref0 && git checkout dev && git pull`
2. `npm run global-install`
3. Run oref0-setup.sh again - either from scratch, or using oref0-runagain, but please note which way you do it (and you'll probably want to run from scratch to view all the beautiful changes ;)).

**Comment by tynbendad** [comment]
tested with 523 pump, g5, edison/explorer - seems to be working well, first smb delivered!

**Comment by ceben80** [comment]
Running since several hours, no issues so far

**Comment by francesc0-cgm** [comment]
723 xdrip and G4 here.
Every time i reboot or i switch on the rig i have:

`Starting supermicrobolus pump-loop at Tue Jul 4 00:32:46 CEST 2017 with 30 second wait_for_silence:
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: .No pump comms detected from other rigs
mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low?
Checking pump status (suspended/bolusing): mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low?
grep: monitor/status.json: No such file or directory
Error, retrying
Sleeping 8; `

After a few tries it makes a mmtune (sometimes after a couple, many times after several minutes) and it starts to loop without any problem

**Comment by PieterGit** [comment]
https://github.com/openaps/oref0/pull/456 (fix for `--ww_ti_usb_reset`)  will also be in 0.5.0.

We must make a choice which MRAA release to go for in 0.5.0 to avoid extra oref0 releases because of dependencies.  I think mraa 1.7.0 is quite recent, or we could ask the MRAA devs to release a 1.7.1 and use that. See https://github.com/intel-iot-devkit/mraa/issues/771 for details.

@francesc0-cgm : do you use a WW pump? I think the loop in the SMB pump loop causes problems with WW users that require a mmtune to get fixed.

**Comment by francesc0-cgm** [comment]
@PieterGit n, it is a NAS one

**Comment by RedCyclist1** [comment]
with SMB/UAM on a Medtronic 723, Dexcom G5,
We had one hiccup in Step 3 to run oref0 set up. 
 
Error: "Please, commit your changes or stash them before you can merge."  

Once Scott provided instructions to run "cd ~/src/oref0 and then git stash is likely all you need, and then you can re-run the command that failed." 

It made sense. and has run all day with no errors.  We are setting up second rig now and did not experience the previous error, it went straight to running script to update to Dev 0.5.0. 

Both rigs up and running SMB/UAM

**Comment by alternateal** [comment]
G5 / 754WW

Loaded from scratch - get this as result of trying to loop - never seems to try running mmtune. 

Starting supermicrobolus pump-loop at Wed Jul 5 20:23:35 BST 2017 with 24 second wait_for_silence:
Waiting up to 4 minutes for new BG: glucose.json newer than pump_loop_completed
Radio ok. Listening: .No pump comms detected from other rigs (this is a good thing!)
mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low?
Checking pump status (suspended/bolusing): mmeowlink.exceptions.CommsException: No acknowledgement from pump on wakeup. Is it out of range or is the battery too low?
grep: monitor/status.json: No such file or directory
Error, retrying
Sleeping 1;

**Comment by scottleibrand** [comment]
We're working on some improvements for that in https://github.com/openaps/oref0/pull/523 if you want to try that.

**Comment by alternateal** [comment]
#523 appears to have worked to kick mmtune in faster.

**Comment by alternateal** [comment]
G5. 754WW

oref0 - works
SMB - works
UAM - works

Needed to do a little bit of work to get iPhone BT hotspot to work after installing this version - didn't work as per docs, needed to add a couple of lines to oref0-bluetoothup.sh to force the connection to the hotspot. Not got it to pull the MAC address into the script so I have put my MAC address in the file. This seems to work well and flips back onto wifi when available.

#!/bin/bash

if ! ( hciconfig -a | grep -q "PSCAN" ) ; then
   sudo killall bluetoothd
   sudo /usr/local/bin/bluetoothd --experimental &
fi

if ( hciconfig -a | grep -q "DOWN" ) ; then
   sudo hciconfig hci0 up
   sudo /usr/local/bin/bluetoothd --experimental &
   sudo bt-pan client XX:YY:ZZ:AA:BB:CC
   sudo dhclient bnep0
fi

if !( hciconfig -a | grep -q $HOSTNAME ) ; then
   sudo hciconfig hci0 name $HOSTNAME
fi

**Comment by scottleibrand** [comment]
@alternateal oref0-bluetoothup.sh isn't supposed to do the `bt-pan client` part.  That is done in oref0-online: https://github.com/openaps/oref0/blob/dev/bin/oref0-online.sh#L45

**Comment by danamlewis** [comment]
Big thanks to everyone who's tested previously; we fixed a couple of issues, and are now needing another round of testing so we can ready this for release! Please do re-pull dev and rerun setup and share your setup so we know we've tested the different options (WW pump, different cgms, with advanced features/without, etc.). Thanks again to everyone who's contributed with testing and/or code for this big release!

**Comment by tim2000s** [comment]
I've run two setups successfully. One running on xdripaps with iPhone link up for off wifi, and had no issues and the other is an NS only instance that is static at home. Both haven't chucked anything curveball like at me, and I've seen no issue on the dev branch so happy to give a big 👍 On those. RPi3 is a different issue and it's not enjoying the current dev branch at all.

**Comment by Bender1061** [comment]
Working for me. MDT 723 Edison with Explorer and Edison with TI, using SMB. 👍

**Comment by alternateal** [comment]
Ok, new Edison and explorer flashed from scratch. G5 with 754WW - thumbs up from me to go to prod. Bluetooth works as intended also :-)

**Comment by Kdisimone** [comment]
Worked on a brand new edison with 723 and g4.  used auto setup and updated to oref1.  all good

**Comment by PieterGit** [comment]
Fresh install with 754 and g4 on USB on rpi3. No problems with installing. Found one small issue https://github.com/openaps/oref0/issues/543 (don't know if it is a regression).
RPI seem to respond slower than I used too (on the terminal), but load averages are about 1.0.

**Comment by dramageek** [comment]
Upgrade install (updated the repository, re-ran oref0-setup), explorer board, 722NA.

Works for me both with/without SMB. Bluetooth still works, Nightscout token auth too.

**Comment by danamlewis** [comment]
Huge thanks everyone for the final round of testing - seeing green lights and turtles all the way down, so will do the release. (Docs PR to match will be https://github.com/openaps/docs/pull/942 if anyone wants to go thumbs that up while we do oref0 0.5.0 release ;))

**Pull request merged**
