### PR TITLE
Add quotation marks around egrep expression.

### PR DESCRIPTION
**Pull request by tzachi-dar**

### CODE REVIEW

**Comment by tzachi-dar** [comment]
Running with it when the myopenaps/2 exists, and when it does not.

בתאריך יום ו׳, 17 בינו׳ 2020, 17:41, מאת Scott Leibrand ‏<
notifications@github.com>:

**Comment by scottleibrand** [comment]
Have you been looping successfully with it on active rigs since then?

**Comment by tzachi-dar** [comment]
Currently only on a test rig.
I'll update the active rigs tonight and make sure it also works there.

**Comment by tzachi-dar** [comment]
This has been running fine on an active rig since yesterday.

**Pull request merged**
