### PR TITLE
Edison battery

### PR DESCRIPTION
**Pull request by Bender1061**
Change to go to dev branch. and not use cron. Also add script to prompt for BT Mac address

### CODE REVIEW

**Comment by Bender1061** [comment]
OK, there appears to be an issue with this
keep getting 
```
Starting ns-loop at Sun Dec 18 23:43:02 EST 2016:
ns://JSON/shell/cgm/ns-glucose.json
reporting cgm/ns-glucose.json
Refreshed temptargets and meal-carbs
Edison Battery at Sun Dec 18 23:43:23 EST 2016: {"batteryVoltage":3799, "battery":62}
UploadNot an openaps environment, run: openaps init
ed
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
Not an openaps environment, run: openaps init
```

I'll have to dig into it tomorrow

**Comment by Bender1061** [comment]
@scottleibrand can you just close or reject this and 277, Thanks

**Comment by Bender1061** [comment]
if anyone is interesting this is working quit well at the moment

**Comment by scottleibrand** [comment]
Ok, I think this is the approach I want to merge, and then close out https://github.com/openaps/oref0/pull/277 - any objections?

Thanks for everyone's collaboration on this.

**Comment by Bender1061** [comment]
Sounds good to me

**Pull request merged**
