### PR TITLE
gzip old autotune json and log files to save space

### PR DESCRIPTION
**Pull request by scottleibrand**
Without intervention, the autotune/ directory can grow indefinitely, as it keeps all old entries, treatments, and autotune log files.  To reduce the disk space impact of doing so, this PR gzips all of those old files before each run.

### CODE REVIEW

**Comment by tim2000s** [comment]
Very sensible given the amount of manual deleting (and then cron jobs) I’ve been running.

**Comment by tim2000s** [comment]
Probably want to look at something similar on the openaps logs. I've been reviewing my disk space this evening (using ncdu - great little tool for this stuff, install with `sudo apt install ncdu` ) and I can see that `/var/log/openaps` is consuming 10% of the overall disk space, with roughly 50% made up of the recently rolled logs, 25% with the current logs and 25% on the old gzipped logs.

**Comment by scottleibrand** [comment]
We already have logrotate in place to handle those.  If you have a rig with ongoing disk space issues from log pressure, we need help adjusting logrotate settings to constrain that.

**Comment by tim2000s** [comment]
I'm just testing something on logrotate to see if I can improve it.

**Pull request merged**
