### PR TITLE
restore cp of newprofile

### PR DESCRIPTION
**Pull request by tynbendad**
restore "Copy tuned profile produced by autotune to profile.json for use with next day of data"

### CODE REVIEW

**Comment by tynbendad** [comment]
autotune successfully ran for me, previously it had failed with https://github.com/openaps/oref0/issues/480

**Comment by tim2000s** [comment]
I've added this into the new install where I was seeing the same issue. If it works I'll report back tomorrow am.

**Comment by mgranberry** [comment]
I had to do essentially the same thing, but figured it was due to a change that I'd made.

**Comment by tim2000s** [comment]
I'm not convinced this is a complete answer. While CSF is adjusted, not all basal rates get adjusted (it seems to stop at 12noon) and based on comparison with one that I know works, that seems wrong. So I don't think this is the entire fix. 👎 I'm afraid.

**Comment by scottleibrand** [comment]
That is the expected behavior if you ate lunch around noon.  Running autotune in your loop only autotunes based on a single day's data each night, so it'll take a few weeks to tune everything the way an rig that's been running awhile would do.  So I'll interpret that as a 👍 for the CSF fix.

**Comment by ericfeibelman** [comment]
I manually made the change to my system (dev) and now autotune works for me. Yay!

Parameter      | Current  | Autotune 
-------------------------------------
ISF            | 46.000   | 53.106   
CSF            | n/a      | 3.579    
Carb Ratio     | 12.000   | 14.838   
  00:00        | 0.650    | 0.650    
  01:00        |          | 0.650    
  02:00        |          | 0.650    
  03:00        |          | 0.650    
  04:00        | 0.800    | 0.800    
  05:00        |          | 0.800    
  06:00        |          | 0.800    
  07:00        |          | 0.800    
  08:00        |          | 0.800    
  09:00        |          | 0.779    
  10:00        | 0.650    | 0.662    
  11:00        |          | 0.662    
  12:00        |          | 0.679    
  13:00        |          | 0.650    
  14:00        |          | 0.644    
  15:00        | 0.800    | 0.759    
  16:00        |          | 0.759    
  17:00        |          | 0.765    
  18:00        | 0.650    | 0.650    
  19:00        |          | 0.650    
  20:00        |          | 0.650    
  21:00        |          | 0.650    
  22:00        |          | 0.650    
  23:00        |          | 0.650

**Comment by rsilvers129** [comment]
Confirmed it fixed my issue. Parameter      | Current  | Autotune 
-------------------------------------
ISF            | 32.000   | 32.997   
CSF            | n/a      | 4.272    
Carb Ratio     | 7.500    | 7.724    
  00:00        | 0.675    | 0.691    
  01:00        | 0.725    | 0.737

**Comment by davidkeddydb** [comment]
I don't think I Vi'd the change incorrectly but my basal rates show nothing different than what is on the pump. Didn't work for me.  I edited the file and then rebooted.  Was I supposed to rerun set up?  If so, then I screwed up.

**Comment by rsilvers129** [comment]
Make sure you are editing the correct file. There is more than one copy on your Edison.

Type: which oref0-autotune and it should show
/usr/local/bin/oref0-autotune

Then edit that one. Jump to line 226. Put the code there, if it is not already, and make sure there are no + signs at the beginning of the line.

**Comment by ceben80** [comment]
@danamlewis fix works for me

```
Recommendations Log File: /root/myopenaps/autotune/autotune_recommendations.log

Parameter      | Current  | Autotune
-------------------------------------
ISF            | 35.000   | 31.056
CSF            | n/a      | 3.416
Carb Ratio     | 9.000    | 9.091
  00:00        | 1.200    | 1.224
  01:00        | 1.100    | 1.138
  02:00        | 1.100    | 1.111
  03:00        | 1.100    | 1.109
  04:00        | 1.300    | 1.299
  05:00        | 1.300    | 1.300
  06:00        | 1.500    | 1.504
  07:00        | 1.500    | 1.500
  08:00        | 1.500    | 1.548
  09:00        | 1.200    | 1.248
  10:00        | 1.200    | 1.250
  11:00        | 1.200    | 1.202
  12:00        | 0.800    | 0.802
  13:00        | 0.800    | 0.800
  14:00        | 0.800    | 0.800
  15:00        | 0.800    | 0.800
  16:00        | 0.800    | 0.807
  17:00        | 0.800    | 0.803
  18:00        | 0.800    | 0.803
  19:00        | 0.800    | 0.796
  20:00        | 0.800    | 0.800
  21:00        | 0.800    | 0.800
  22:00        | 0.800    | 0.800
  23:00        | 0.800    | 0.826
```

**Comment by danamlewis** [comment]
According to many folks, this seems to resolve https://github.com/openaps/oref0/issues/480 (null/0 CSF output), so will merge. To get this fix, re-pull dev again and it should fix your autotune moving forward. Please reopen an issue if you see any further problems related to autotune.

**Pull request merged**
