### PR TITLE
Re-adding bnep0 check into oref0-setup.sh

### PR DESCRIPTION
**Pull request by rkresha**
@scottleibrand  
Here is the re-add that shouldn't cause an issue with rpi. @cluckj would you be willing to validate this?

### CODE REVIEW

**Comment by cluckj** [comment]
:+1: Tested & working as expected on the pi; thanks!

**Comment by scottleibrand** [comment]
Do we need a test on Edison as well?

**Comment by rkresha** [comment]
> Do we need a test on Edison as well?

Based on my previous work on this I feel confident with the changes without actually testing them. Really your comfort level though. Please advise @scottleibrand

**Comment by rkresha** [comment]
@scottleibrand works as expected. Edison is good to go.

**Pull request merged**
