### PR TITLE
Fix bluetoothup

### PR DESCRIPTION
**Pull request by dcacklam**
PR to reduce bluetooth flapping on Pi by not doing the kill bluetoothd if no PSCAN on arm archetectures.

### CODE REVIEW

**Comment by scottleibrand** [comment]
What I did in the go-explorer-hat branch is https://github.com/openaps/oref0/commit/cb41fb7b4b9565f5902a763ea02085cce52b15f7

Can you think of any good reasons to use one approach or the other?  I'm fairly agnostic.

**Comment by dcacklam** [comment]
If someone deletes or renames the 'edison' account (or installs a different Linux base that has a different (or no) default account) the passwd-based hardware-ID will break. 

Unless we introduce a different HW platform than Edison & Pi, looking for ARM arch is a sure-fire way to check for Pi hardware.

**Comment by scottleibrand** [comment]
I’d rather support new hardware types (we’ve already started looking into one that might be coming to market soon) than try to support people doing arbitrary unnecessary customization like changing directory or user names.

**Comment by dcacklam** [comment]
In that case your way makes sense...

**Comment by scottleibrand** [comment]
Ok, I just cherry-picked cb41fb7b4b9565f5902a763ea02085cce52b15f7 and pushed it to dev.  Thanks.

**Pull request closed without merging**
