### PR TITLE
Changes to support Jubilinux v0.3.0 (stretch)

### PR DESCRIPTION
**Pull request by cluckj**
(Mostly cosmetic changes right now)

### CODE REVIEW

**Comment by Ricco555** [comment]
works also on jubilinux v0.4.1
:+1:

**Comment by scottleibrand** [comment]
Is this still a WIP?

**Comment by cluckj** [comment]
I think I'm going to close it in favor of a version of #1241 for `dev`.

**Comment by cluckj** [comment]
(Superseded by https://github.com/openaps/oref0/pull/1243)

**Pull request closed without merging**
