### PR TITLE
cleaned-up 0.7.0-refactor

### PR DESCRIPTION
**Pull request by scottleibrand**
cherry-pick of the commits from @jimrandomh's https://github.com/openaps/oref0/pull/994, resolving merge conflicts along the way

### CODE REVIEW

**Comment by tim2000s** [comment]
Just tried to install this with xdrip for CGM. Runs into an issue with downloading the xdrip files:

```
Importing /root/src/oref0/lib/oref0-setup/xdrip-cgm.json
Not an openaps environment, run: openaps init
Could not import /root/src/oref0/lib/oref0-setup/xdrip-cgm.json
```

**Comment by scottleibrand** [comment]
@tim2000s can you confirm whether https://github.com/openaps/oref0/pull/1030/commits/3d702a3123a701fc89669731496c6d719ba6ee37 fixes your xdrip-cgm import issue?

**Comment by tim2000s** [comment]
Will do. Travelling today so may take a little time.

**Comment by scottleibrand** [comment]
Merging this to 0.7.0-dev to get wider testing.

**Pull request merged**
