### PR TITLE
Uploader battery status

### PR DESCRIPTION
**Pull request by cjo20**
Puts a battery percentage in the upbat pill of Nightscout. Expects a file that contains a single number, the battery percentage.

uploader.json could be generated with the following `root` cronjob (`sudo crontab -e`)

`*/5 * * * /path/to/EdisonVoltage/voltage 3 > /path/to/openaps/uploader.json`

I've tested the various combinations of --uploader uploader.json / mmtune.json and they all seem to work.

### CODE REVIEW

**Comment by Spazholio** [comment]
Is there any way this can also be merged into the AMA branch?

**Comment by scottleibrand** [comment]
We're working on that.  In the mean time you can get both via the merge-ama branch, if you're willing to look for stuff we might've broken during the merge conflict resolution.

**Comment by scottleibrand** [comment]
Looks like https://github.com/openaps/oref0/pull/154#issuecomment-231501772 is the one remaining issue.  If you know how to fix, feel free to PR.

**Comment by Spazholio** [comment]
Completely missed that there was another branch out there.  Pulled and running.  Will report back.

**Pull request merged**
