### PR TITLE
Pumphistory safety checks

### PR DESCRIPTION
**Pull request by scottleibrand**
@hilarykoch recently experienced an A52 error that rebooted the pump and somehow caused decocare/openaps to prematurely stop parsing pumphistory such that it didn't return an error but didn't include recent events.  This in turn resulted in incorrect IOB, causing OpenAPS to overdose insulin, providing Leo with an unscheduled pump break and dessert.

This PR adds some safety checks to make sure that pumphistory is being updated, and that the lastTemp in pumphistory matches the currently running temp basal on the pump.

### CODE REVIEW

**Comment by scottleibrand** [comment]
This is working now: I think it's good to merge.

**Comment by mgranberryto** [comment]
I've had this happen as well.

**Comment by scottleibrand** [comment]
@mgranberryto can you describe exactly what happened in your situation?  Did it just fail to read some records, or were new temps and SMBs also not being read?

**Comment by mgranberryto** [comment]
New temps/SMBs were being unread.  I assumed that it was due to an edited record after the fact, but reading this after the fact I realize that this is the same issue.  It recovered about 6 hours later.

**Pull request merged**
