### PR TITLE
fix bug with diaratio that was having the backwards effect and some cleanup

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Not ready to merge, test coming later tonight...

### CODE REVIEW

**Comment by scottleibrand** [comment]
@eyim may also want to checkout this branch and test it...

**Comment by amazaheri** [comment]
Testing it as we speak ...

**Comment by jasoncalabrese** [comment]
Needs one more little fix, bIOB needs to /2 instead on *2

**Comment by scottleibrand** [comment]
Jason's on the road, but that's:

diff --git a/lib/iob/total.js b/lib/iob/total.js
index eade937..94e0124 100644
--- a/lib/iob/total.js
+++ b/lib/iob/total.js
@@ -19,7 +19,7 @@ function iobTotal(opts, time) {
             if (tIOB && tIOB.activityContrib) activity += tIOB.activityContrib;
             // keep track of bolus IOB separately for snoozes, but decay it three times as fast
             if (treatment.insulin >= 0.2 && treatment.started_at) {
-                var bIOB = iobCalc(treatment, time, dia*2)
+                var bIOB = iobCalc(treatment, time, dia/2)
                 //console.log(treatment);
                 //console.log(bIOB);
                 if (bIOB && bIOB.iobContrib) bolusiob += bIOB.iobContrib;

**Pull request merged**
