### PR TITLE
out of the box pebble pancreabble support and notification to pebble for insulinReq and carbsReq

### PR DESCRIPTION
**Pull request by PieterGit**
- out of the box pebble support. Tested with `CGM=G4-upload`, but others may also work fine.
- notifications are sent to the pebble when using SMB / oref1

### CODE REVIEW

**Comment by applehat** [comment]
Any reason this wouldn't work with any CGM setting? monitor/glucose.json is present on all the CGMs, right?

Or maybe the format is different?

**Comment by tim2000s** [comment]
I would expect it to work for all. monitor/glucose.json should be standardised.

**Comment by applehat** [comment]
I will test tonight (hopefully). I have a pebble that's been sitting doing
nothing that I'd love to use.

**Comment by PieterGit** [comment]
I have only tested with  `CGM=G4-upload`. Please let me know waht CGM option you use. It now uses `monitor/glucose.json`. There may still be some issue that needs to be resolved, but it seemed to work.

**Comment by PieterGit** [comment]
You must still pair and trust your pebble with `bluetoothctl`

**Comment by PieterGit** [comment]
Note you need to enable the new notifications in `pancreoptions.json`. 
Should I enable them by default to `true`?

**Comment by Bender1061** [comment]
My Current Pebble I was using for Pancreabble stopped working, I've ordered another. But something we need to look into is not all monitor/glucose.json's are the same. The MDT looks quite a bit different than someone using one of the other CGMs. 
at least that is my concern.

**Comment by PieterGit** [comment]
@Bender1061 can you explain the differences? This patch makes pancreabble able to work with all kinds of date formatsa and timezones. 
@applehat : did you have a chance of testing this out?

**Comment by Bender1061** [comment]
[
  {
    "trend_arrow": "FLAT", 
    "glucose": 120, 
    "direction": "Flat", 
    "_id": "597a6cbc82d198a1dfd760ba", 
    "name": "GlucoseSensorData", 
    "date_type": "relative", 
    "_tell": 2, 
    "display_time": "2017-07-27T18:37:00-04:00", 
    "packet_size": 0, 
    "dateString": "2017-07-27T18:37:00-04:00", 
    "device": "openaps://medtronic/pump/cgm", 
    "date": 1501195020000, 
    "sgv": 120, 
    "type": "sgv", 
    "op": 60
  }, 
  {
    "trend_arrow": "FLAT", 
    "glucose": 120, 
    "direction": "Flat", 
    "_id": "597a6cbc82d198a1dfd760bb", 
    "name": "GlucoseSensorData", 
    "date_type": "relative", 
    "_tell": 3, 
    "display_time": "2017-07-27T18:32:00-04:00", 
    "packet_size": 0, 
    "dateString": "2017-07-27T18:32:00-04:00", 
    "device": "openaps://medtronic/pump/cgm", 
    "date": 1501194720000, 
    "sgv": 120, 
    "type": "sgv", 
    "op": 60
  }, 

There is the  format of the MDT CGM, does that work similar to yours?

**Comment by PieterGit** [comment]
my glucose.json (G4-upload) does not have a `name` attribute, but pancreabble only uses `display_time`, `glucose` and `trend_arrow`, see https://github.com/mddub/pancreabble/blob/98860fda64f03f2fcf8a857dfb0de2b84292924f/pancreabble/urchin.py#L124-L129

So I don't see why this won't work for you. Did you have a try?

**Comment by applehat** [comment]
I haven't yet. Last night ended up being short of free time. But my pebble
is charged and ready for testing tonight (hopefully)

**Comment by Bender1061** [comment]
I should get my replacement Pebble within a week, so I'll be testing it as soon as I get it.

**Comment by applehat** [comment]
@PieterGit, xDrip doesn't have a `display_time` field.

```  {
    "filtered": 179392, 
    "direction": "Flat", 
    "noise": 1, 
    "sysTime": "2017-07-26T23:07:57.703-0500", 
    "dateString": "2017-07-26T23:07:57.703000-05:00", 
    "sgv": 163, 
    "device": "xDrip-DexcomG5", 
    "unfiltered": 177056, 
    "delta": -0.747, 
    "date": 1501128477703, 
    "rssi": 100, 
    "_id": "5979671e2d9ce7d83f4015e6", 
    "type": "sgv", 
    "glucose": 163
  }
```

**Comment by applehat** [comment]
So, I am REALLY bad at python, and have no idea how you would want to do conditional checking for xDrip, but for what its worth, this is how I made `urchin.py` work with xDrip glucose.json

```        
cgm_records = [
            {
                'date': dateutil.parser.parse(r['dateString'], ignoretz=True),
                'sgv': r['sgv'],
                'trend': DEXCOM_TRENDS.index(r.get('direction').upper().replace("FORTYFIVE","45_")),
            }
            for r
            in sorted(cgm_history, key=itemgetter('dateString'), reverse=True)
        ]
```

**Comment by applehat** [comment]
img_20170727_232935_1024

Confirmed working with xDrip with those changes mentioned above.

**Comment by PieterGit** [comment]
@applehat : thanks for testing!

Can others confirm that their `monitor/glucose.json` has the following fields:
- dateString
- glucose
- trend_arrow

What we know now:
- xdrip: yes
- G4-upload: yes

If so, I'll change the PR to pancreabble to use `dateString` instead of `display_time`.

**Comment by applehat** [comment]
@PieterGit - the xdrip doesn't have the `trend_arrow` field - instead of has `direction`.

I also had to filter the value a bit to make it look like what the G4-upload provides.

```
r.get('direction').upper().replace("FORTYFIVE","45_")
```

this translates `Flat` to `FLAT` and `fortyfive_up` to `45_UP`.

**Comment by applehat** [comment]
The example posted by @Bender1061 has 'direction' in it as well, so assuming the G4 also does, its probably best to key off it like I'm doing vs using trend_arrow. That covers G4, xdrip, and mdt, and thats most of us.

**Comment by PieterGit** [comment]
Asked @mddub to honor pancreabble PR https://github.com/mddub/pancreabble/pull/15
That is required, so that the official branch can be used in stead of my fork of pancreabble.

That PR will use `dateString`, `direction` and `sgv`. They seem to be present in all CGM options.

```
 cgm_records = [
            {
                'date': dateutil.parser.parse(r['dateString'], ignoretz=True),
                'sgv': r['sgv'],
                'trend': DEXCOM_TRENDS.index(r.get('direction').upper().replace("FORTYFIVE","45_"))
            }
            for r
            in sorted(cgm_history, key=itemgetter('dateString'), reverse=True)
        ]
```

**Comment by applehat** [comment]
Sounds 💯  to me!

**Comment by applehat** [comment]
Also unrelated to testing, but shouldn't this PR merge into `dev` instead of `master`?

**Comment by scottleibrand** [comment]
@applehat Yes.  Just changed the base to dev.

**Comment by Diadon81** [comment]
Does it work with MDT?

**Comment by PieterGit** [comment]
@Diadon81 should work with MDT because `monitor/glucose.json` has `dateString`, `direction` and `sgv`. Please confirm.
@scottleibrand : thanks for changing base to dev. That was intended, but I made an error in the Github interface. That was one advantage of GitHub Desktop, because that selected the branch automatically from the client. Unfortunately it made merging a hell because it's buggy.

**Comment by applehat** [comment]
@Diadon81 it *should*, but if you would like to test, it would be very appreciated =)

**Comment by applehat** [comment]
Hmm. So I just got a pushover for carbs required but no notification on my
pebble. I'll investigate to make sure I have the settings correct.

**Comment by applehat** [comment]
Yep, it's enabled.

**Comment by applehat** [comment]
Ahh. Also, "SINGLEUP" for the single up arrow doesn't match either. Discovered this after dinner.

**Comment by applehat** [comment]
Just got home and figured out the replacements.

This code feels really dirty tho. May be a cleaner way to do this.

`'trend': DEXCOM_TRENDS.index(r.get('direction').upper().replace("FORTYFIVE","45_").replace("SINGLE","SINGLE_").replace("DOUBLE","DOUBLE_"))`

**Comment by PieterGit** [comment]
Can't fix it the coming days. Perhaps changing the constants in urchin.py is the best solution. If anybody wants to prepare the change, please do.

**Comment by Bender1061** [comment]
So with MDT this is what is showing on the log
```
upload/urchin-data.json  raised  'dateString'
pbbl://JSON/format_urchin_data/upload/urchin-data.json
Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/src/openaps/bin/openaps-report", line 82, in <module>
    app( )
  File "/root/src/openaps/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/root/src/openaps/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/root/src/openaps/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/root/src/openaps/openaps/reports/invoke.py", line 40, in main
    output = task.method(args, app)
  File "/root/src/openaps/openaps/uses/use.py", line 45, in __call__
    output = self.main(args, app)
  File "/root/.local/lib/python2.7/site-packages/pancreabble/urchin.py", line 132, in main
    in sorted(cgm_history, key=itemgetter('dateString'), reverse=True)
KeyError: 'dateString'
```
now if I try it on a rig that is working
```
}pbbl://JSON/format_urchin_data/upload/urchin-data.json
reporting upload/urchin-data.json
{
  "received": true
}
```

Now the notifications are working correctly. just the Urchin Data. 

and now I was only running one rig at a time so it was not a com interference issue. 
but the log kind of looks like we have a datestring issue.

**Comment by PieterGit** [comment]
This PR is on hold because I need to take care of improving the pancreabble PR  
https://github.com/mddub/pancreabble/pull/15#issuecomment-320349230
That will probably not be next week, so please be patient.

**Comment by scottleibrand** [comment]
Is this worth keeping open, or would you rather do a new clean PR against 0.6.0 after release?

**Comment by Diadon81** [comment]
Close it

**Comment by PieterGit** [comment]
I'll hope to do a clean PR after the 0.6.x. Fine with closing it for now.

**Pull request closed without merging**
