### PR TITLE
don't do redundant JSON parsing

### PR DESCRIPTION
**Pull request by mgranberry**
This cleans up a number of chained `json` calls to execute all operations in a single execution.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Have you tested this?  I haven't yet, but don't see any indication from `man json` that `json -e "somecode;" -e "someothercode;"` will execute both `somecode` and `someothercode`.

**Comment by scottleibrand** [comment]
If not, we might want something like:

```
json -e "this.medtronic = this._type; \
    this.dateString = this.timestamp + '$(date +%z)';  \
    this.type = 'medtronic';"
etc.
```

**Comment by mgranberry** [comment]
It works for me.  From the `json` source: 
```js
        case '-e':     
        case '-E':  // DEPRECATED in v9
            parsed.exeSnippets.push(args.shift());
            break;
...
     for (i = 0; i < opts.exeSnippets.length; i++) {
            exeFuncs[i] = new Function(opts.exeSnippets[i]);
        }   
```

**Comment by scottleibrand** [comment]
Yay for undocumented features.  :-)

Would putting all the json into a single multiline quoted string be more readable or better for any other reason?  If not, I'm fine with testing your approach.

**Comment by mgranberry** [comment]
I don't think it makes a big difference either way.  I'd be happy to change it to multiline strings if you have a preference for them.

**Pull request merged**
