### PR TITLE
0.6.1 release dev to master

### PR DESCRIPTION
**Pull request by danamlewis**
0.6.1-rc1:

Many minor fixes & improvements.

**Notable:**
•	x12 fixes 
•	limit SMB zero temps to 60 minutes
•	offline web page
•	raise BG target for noisy / raw CGM data (#833)
•	autosens is always enabled (*to disable, set min/max to 1*)
•	faster autotune; and avoids raising basals from UAM carbs
•	added cleaning to address full diskspace issues
•	Carelink support re-added
•	Suspends will count as zero IOB; no longer need to temp to zero and suspend (*but people should make sure to change their settings for suspend-if-no-temp if they leave this as false, so pumps don't get unsuspended and issue SMB's while they're still disconnected*)
•	No longer warns in logs (causing excessive buildup) about DIA of 2 < 3. Defaults to 5, regardless, for curves, since 0.6.0

### CODE REVIEW

**Comment by tim2000s** [comment]
Tried installing Dev this evening and running into the following issues:
```
Checking for BT Mac, BT Peb or Shareble
Checking bluez installation
bluez version 5.48 already installed
Installing prerequisites and configs for local-only hotspot
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dnsmasq is already the newest version.
hostapd is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up bluez (5.23-2+deb8u1) ...
Job for bluetooth.service failed. See 'systemctl status bluetooth.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript bluetooth, action "restart" failed.
dpkg: error processing package bluez (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 bluez
E: Sub-process /usr/bin/dpkg returned an error code (1)
Couldn't install hostapd dnsmasq
```

Struggling to work out where the issue is, but there's obviously something not quite right when it's trying to install an old version of bluez over the top of 5.48.

**Comment by tim2000s** [comment]
Turns out there was a rather old bluez install that I’d forgotten about which had been done manually and was interfering with the setup. 

Using “apt-get remove bluez” cleared it and we were good to go.

**Comment by danamlewis** [comment]
We are preparing 0.6.1 as a release candidate. Some things to focus on testing:

- x12 setup from scratch, ensuring you can successfully loop and all steps are completed with these code changes. (Please make note if any docs need changing to match these changes?)
- Ensure autotune results are still as expected
- Check log rotate file is set automatically to hourly
- Test suspend counting as zero IOB (but remember to turn off your unsuspend-if-no-temp setting!)
- Carelink users also confirm fresh setup enables successful looping

(Plus the usual all pump models; all time zones; etc!)

**Comment by Bender1061** [comment]
it's looking like the offline page does not work with MDT CGM. I'm not sure if it's needing to look at glucose-unzoned or not. Which brings on the point, how we have such different CGM format in Glucose from the MDT. Do we need to get someone to do make a fix to make the monitor/glucose the same between all CGM's and not have this special case of MDT stuff. this would reduce some of the work we have to do to convert stuff so much. Less special cases would be nice.

**Comment by M1Sports20** [comment]
Filling comments as requested by dana from gitter.
All has been well with this dev build.  My setup:
Two rigs, both identical:
**Rig**: edision with explorer board
**Pump**: Medtronic 523
**Timezone**: Eastern
**Time**: Started 4-20-18 
**Target**: 90
**Settings**:
```
"max_iob": 10,
"max_daily_safety_multiplier": 3,
"current_basal_safety_multiplier": 4,
"autosens_max": 1.2,
"autosens_min": 0.7,
"rewind_resets_autosens": true,
"adv_target_adjustments": false,
"exercise_mode": true,
"wide_bg_target_range": false,
"sensitivity_raises_target": true,
"unsuspend_if_no_temp": true,
"enableSMB_always": true,
"enableSMB_with_bolus": true,
"enableSMB_with_COB": true,
"enableSMB_with_temptarget": true,
"enableSMB_with_carbs": true,
"enableUAM": true,
"curve": "rapid-acting",
"offline_hotspot": false,
"maxSMBBasalMinutes": 45
```

**Comment by cluckj** [comment]
From-scratch x12 setup & docs worked for me. Can anyone else with an x12 check this as well?

**Comment by danamlewis** [comment]
Just marked this as 0.6.1-rc1. As a reminder, we need lots of help testing this to get a release, so please check out a fresh dev (instructions [here](http://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/update-your-rig.html#alternative-step-1a-dev-to-get-on-dev-branch-to-test-even-more-recently-added-new-stuff), follow steps 1A, 2, and 3) and make sure to comment on this PR to let us know how it's going. Thanks to everyone who's tested & commented so far!

**Comment by AdrianLxM** [comment]
`maxRaw` seems to be written to but never used within determine-basal:
https://github.com/openaps/oref0/blob/0cb310d67eada06fb082853a171b5a18cbb1afca/lib/determine-basal/determine-basal.js#L288

I also could not find any changes in 0.7.0 that would use it. All raising of targets etc. is done implicitly via adding a noise value in `lib/with-raw-glucose.js`

**Comment by scottleibrand** [comment]
@Tornado-Tim fixed: please to re-test if you'd like to confirm.

**Comment by Tornado-Tim** [comment]
Testing the WebUI: The WebUI is a bit dodgy in retrieving data from the Rig......  BG Data retrieval date esp.
openaps-webui
openaps-webui-2
openaps-webui-3

**Comment by Tornado-Tim** [comment]
Will make a separate issue for the WebUI as requested by @danamlewis.
@scottleibrand: the issue is fixed for the issue stated above, but must have overlooked the exact same issue occurs at the end of the setup script and looks like below:
```
bash-completion is already the newest version.
bc is already the newest version.
jq is already the newest version.
ntpdate is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
importing supermicrobolus file
determine-basal://JSON/shell/enact/smb-suggested.json
pump://JSON/set_temp_basal/enact/smb-enacted.json
pump://JSON/bolus/enact/bolused.json
Adding OpenAPS log shortcuts
Add NIGHTSCOUT_HOST and API_SECRET to /root/.bash_profile
sed: can't read .profile: No such file or directory
sed: can't read .profile: No such file or directory

grep: /proc/device-tree/hat/product: No such file or directory
Resetting spi_serial
Schedule openaps in cron? y/[N] 
```

**Comment by danamlewis** [comment]
Reminder - please test dev and comment on your setup. Expecting to release 0.6.1 end of this week if no major issues are spotted. See [here](https://github.com/openaps/oref0/pull/816#issuecomment-381450794) for the list of things to test for this release. 

To test, check out a fresh dev (instructions [here](http://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/update-your-rig.html#alternative-step-1a-dev-to-get-on-dev-branch-to-test-even-more-recently-added-new-stuff), follow steps 1A, 2, and 3) and make sure to comment on this PR to let us know how it's going.

**Comment by Tornado-Tim** [comment]
Given the latest 0.6.1 pull a try with the latest fix for TT in mmol being issued, works well.
Seems like this is ready for release to me :tada:

**Comment by Tornado-Tim** [comment]
`MaxUAMSMBBasalMinutes` is working wonderfully! Graph with it in action!
Awesome stuff @scottleibrand and @danamlewis :+1: 
smbfeature

**Comment by tynbendad** [comment]
i tried latest dev on a backup rig and it was working well until we used it for a full day - the rig hung twice (as in unresponsive, even thru serial port).  i plan to try it on another rig shortly, its unlikely that its related to changes in dev, but thought i should post just in case.

**Comment by danamlewis** [comment]
I asked on Gitter for some European time zone testers. On Gitter, @CaptainBalou said "I am using this branch and I am update frequently. I am in Europe with CEST time zone. I had not issues which prevented me from normal looping. Setup is Veo 754, xdrip, G5."

so that sounds like a 👍 for non-NA time zones, xdrip, etc.

**Pull request merged**
