### PR TITLE
Spidev already in use reboot

### PR DESCRIPTION
**Pull request by Kdisimone**
I'm not entirely sure that this change is entered correctly...trying to resolve the "spidev already in use" error by adding a crontab line.  PLEASE take a look at this carefully as I'm a complete noob and basically was working off existing syntaxes to help me add the line to the script

### CODE REVIEW

**Comment by Bender1061** [comment]
are you sure you want to use 50 lines? I know you have it waiting for 10 mins, but matters how long your pump loop is. With the Enlite people, it can take about 7 mins to complete a loop, so I would be a bit more comfortable with 30 lines myself.

**Comment by Kdisimone** [comment]
I'm totally open to suggestion....I'm definitely not an expert on what would work best here for the greatest good.

**Comment by moomoobloo** [comment]
I'm not sure what the context for this is, but why would we want to reboot the device just because spidev is already in use?

Getting that error is normal and expected in many situations. For instance, any time a pump command is manually invoked, it's expected that the loop would produce the 'already in use' error, and I don't think it would be helpful to reboot in that situation.

Also, I have similar concerns to @Bender1061 that triggering reboot based on log output is not very robust. It seems to create the risk of infinite reboot loops or at least a series of several consecutive reboots if the error is not cleared from the logs in time. 

Is there a more specific condition that can be detected instead of the 'already in use' error? Is there a way to detect it independent of the log output?

**Comment by Kdisimone** [comment]
It is related to this issue https://github.com/openaps/oref0/issues/406

**Comment by Kdisimone** [comment]
I see now that @scottleibrand commented this cron line won't work well as the solution...I'd missed that prior to submitting this.  I will close this out...but the issue still needs resolution.  If one of you can suggest a better way and make a PR, that would be much appreciated.

**Comment by Kdisimone** [comment]
I have been using a different solution currently, but do not know how to PR it in.  I do know however, that the BT tethering definitely hangs us up everyday that my daughter goes from the car ride (BT use) to school (school wifi).  It will not automatically hop off the BT and get on school wifi.  It gets stuck with this error and only a reboot will solve the issue.

**Pull request closed without merging**
