### PR TITLE
Release oref0 dev to master (official release of oref0-setup)

### PR DESCRIPTION
**Pull request by bewest**
### dev happens here

Send your pull requests here. :-)

### CODE REVIEW

**Comment by bewest** [comment]
Planning wise: we know we'd like a few things:

* [ ] - plan on integrating https://github.com/openaps/oref0/compare/dev...advanced-meal-assist?expand=1
  * [ ] - hitlist of things needed to move to dev (prepping for release) :)

Feel free to amend, add.

**Comment by amazaheri** [comment]
@bewest with G5 stuff you are baking I think it would be great if we can work on a layer on top to allow access to various modules/data elements on the rig to be able allowing UI on platform of choice to talk to rig via BT. We talked about it in the past.

**Comment by amazaheri** [comment]
@bewest RL supportability for openAPS tool set as a device :)

**Comment by bewest** [comment]
https://github.com/openaps/oref0/compare/dev...advanced-meal-assist?expand=1 This branch/pr should be rigorously checked, and it looks like we should maybe adjust some of the cli handling before moving into dev?

**Comment by bewest** [comment]
wrong pr earlier: https://github.com/openaps/oref0/pull/119

**Comment by danamlewis** [comment]
Needs a few testers to make sure updating to dev doesn't break anything, given AMA is merged to dev, before considering a dev to master.

**Comment by amazaheri** [comment]
I will do it by weekend on our dev rig.

**Comment by scottleibrand** [comment]
We also need to go over all the AMA features more carefully and make sure all the new stuff is off by default and the arguments are fully backwards and forward compatible.

**Comment by amazaheri** [comment]
Merged Dev and switched from AMA branch on all the rigs, ran the loop successfully on all rigs.

**Comment by jasoncalabrese** [comment]
I'm in sync with `dev` on all rigs also

**Comment by scottleibrand** [comment]
Now that mm-cgm is merged, I think we're ready to review oref0 dev for a release to master, at which point we'll be able to update oref0-setup to point to master instead of dev, and do proper version checks for things like https://github.com/openaps/oref0/issues/254

Can the next few people to run oref0-setup please comment here and let us know which configuration you used (CGM and radio stick type, etc.) and whether you ran into any bugs?

**Comment by Bender1061** [comment]
So far working well with Edison w/ Breakout board TI stick wired Serial. MDT

**Comment by live4sw** [comment]
So far working well with Pi 3 with USB TI stick and Dexcom G4. No bugs yet after about 6 hours of usage. Only issue is that I am not getting the AMA purple lines in Nightscout yet, but I think that is probably an NS issue with my setup, not an openaps one.

**Comment by PieterGit** [comment]
Installs fine on pi3 with slice of radio. Will do more testing.

Before releasing this shouldn't all the dependencies be also released. The current version uses a lot of unreleased versions. I would expect that a stable oref0 uses stable versions of mmeowlink. I also noticed that the script pulls the dev branch of oref0 if ~/src/oref0 does not exist. When merging to master that should also be changed.

**Comment by scottleibrand** [comment]
Yeah, we need to fix all of those things. I'm thinking that I'll need to cut a release of oref0 first, then update oref0-setup to check for that version or later, and then release that. I don't control the mmeowlink repo, so the timing there will be up to @oskarpearson

**Comment by scottleibrand** [comment]
Is everyone happy with the activityContrib fix?  Anything else before I release?

**Comment by danamlewis** [comment]
👍

**Comment by oskarpearson** [comment]
@scottleibrand I've released mmeowlink https://github.com/oskarpearson/mmeowlink/releases/tag/v0.9.1 :)

**Comment by scottleibrand** [comment]
Thanks!  Just updated https://github.com/openaps/oref0/pull/267/commits/5ea09f0a980c31e33b8b46dedc55cfc8add30a5d to use it.  :-)

**Comment by oskarpearson** [comment]
Great. :) 

BTW: if you wanted to, you could use 'pip install -U mmeowlink' since I've uploaded it to pypy. I see you've done that in a few other places rather than pull git repos. I'm not sure which you'd prefer to do :)

**Comment by oskarpearson** [comment]
BTW: I've created this for an issue that might want triaging before release of the new setup script. It's comparatively minor slowdown - so don't let it hold you up unnecessarily :)

https://github.com/openaps/oref0/issues/268

**Comment by scottleibrand** [comment]
Ah, was wondering if pip was an option. I'll use that. Might want to update the mmeowlink wiki too.

**Pull request merged**
