### PR TITLE
support for uploading MDT CGM data to NS

### PR DESCRIPTION
**Pull request by scottleibrand**
This sets the dateString and sgv values to allow uploading of MDT CGM data to NS.

### CODE REVIEW

**Comment by scottleibrand** [comment]
And with these reports, MDT CGM users should have their CGM data uploaded to NS automatically.   @mwilliams is going to test with a fresh oref0-setup install.  Might also be of interest to @cjo20 and others.

**Comment by Bender1061** [comment]
So Something semi sort of releated. I'm trying to test this right now, But I've been having a very bad afternoon/evening. So my BG is above 400 (yeah I know bad) but ok, so when that happens, the pump does not see the BG Data. and the loop basically does not run. Interesting enough, if I'm using my mmconnect to upload to the system it actually give it a blood sugar of 400. and Nightscout reads that as 400, and my loop gets that information and will constantly try to keep a basal at my Max to get it to come down. 
I really like how it does that. 
does anyone see a way that we can make OpenAPS do that? I know this is a weird situation, and obviously for any of this to work, we have to be hooked up to the net, so my current situation isn't a standard one by any means. 
just thought I would throw that out there. 

hopefully when my BG comes back down within the next couple hours, I'll find out if everything is working or not.

**Comment by redjujube** [comment]
Tried this out with a Medtronic CGM/pump. Not having any success as of yet. Unfortunately I'm not wearing a CGM sensor at the moment, but there is old CGM sensor data on the pump that should be getting uploaded. BG checks are getting uploaded. I am also not seeing the openaps pill box in nightscout (when does this get populated? The openaps plugin is enabled.

Here is the nightscout page: https://redjujube.azurewebsites.net/

Here is the output from the pump-loop.log (21:21:00 is the time of the last bolus)

`Starting pump-loop at Mon 7 Nov 22:59:18 EST 2016:
pump://JSON/read_temp_basal/monitor/temp_basal.json
reporting monitor/temp_basal.json
reporting cgm/cgm-glucose.json
Profile less than 60m old
glucose.json newer than temp_basal.json
Temp refreshed
BG data is too old, or clock set incorrectly.  Your CGM time is Mon Nov 07 2016 21:21:00 GMT-0500 (EST) but your system time is Mon Nov 07 2016 23:00:25 GMT-0500 (EST)
determine-basal://text/shell/enact/suggested.json
reporting enact/suggested.json
{"reason":"BG data is too old, or clock set incorrectly.  Your CGM time is Mon Nov 07 2016 21:21:00 GMT-0500 (EST) but your system time is Mon Nov 07 2016 23:00:25 GMT-0500 (EST)"}
{"reason":"BG data is too old, or clock set incorrectly.  Your CGM time is Mon Nov 07 2016 21:21:00 GMT-0500 (EST) but your system time is Mon Nov 07 2016 23:00:25 GMT-0500 (EST)"}
cat: enact/enacted.json: No such file or directory
glucose.json newer than pumphistory: Refreshed pumphistory
BG data is too old, or clock set incorrectly.  Your CGM time is Mon Nov 07 2016 21:21:00 GMT-0500 (EST) but your system time is Mon Nov 07 2016 23:01:00 GMT-0500 (EST)
determine-basal://text/shell/enact/suggested.json
reporting enact/suggested.json
{"reason":"BG data is too old, or clock set incorrectly.  Your CGM time is Mon Nov 07 2016 21:21:00 GMT-0500 (EST) but your system time is Mon Nov 07 2016 23:01:00 GMT-0500 (EST)"}
{"reason":"BG data is too old, or clock set incorrectly.  Your CGM time is Mon Nov 07 2016 21:21:00 GMT-0500 (EST) but your system time is Mon Nov 07 2016 23:01:00 GMT-0500 (EST)"}
cat: enact/enacted.json: No such file or directory
Settings less than 10m old
Pumphistory-24 less than 20m old
Completed pump-loop at Mon 7 Nov 23:01:05 EST 2016
`

**Comment by mwilliams** [comment]
Haven't forgotten about this, sensor died out Monday and then well, the week happened. 

Tossing on a sensor after lunch, will go ahead and pull this branch on a fresh RPi3 I've got setup and will give it a whirl!

**Comment by mwilliams** [comment]
Tested this on a somewhat fresh RPi3.  Two things.

1) I ran into https://github.com/openaps/oref0/issues/254 and had to take the manual steps to make the check happy.  Not a big deal.  I think I saw a PR that addresses this already
2) After running the setup script, it fails on `Could not run ored0-get-profile`.  Full gist of the run: https://gist.github.com/mwilliams/8a0ebd4523b6c5f642b23402ca8ea063 - I'm going to blow away my node/npm install and get the latest and greatest, not sure if that has any impact but I'm wondering if I hosed something when addressing https://github.com/openaps/oref0/issues/254.  

I should have some time this week to troubleshoot further.

**Comment by scottleibrand** [comment]
Looks like there were a few things I missed when trying to capture @mwilliams setup.  Finally got those things fixed up, and got @betluis daughter's rig uploading correctly.  He's going to do a complete reinstall end-to-end to make sure I didn't miss anything else, but if anyone else wants to give this another shot, it should work much better now.

If your Nightscout has no CGM data, you might also need to run `openaps first-upload` to get the first data point uploaded to NS, and after that the rig should do the rest.

**Comment by mwilliams** [comment]
I'll give this another whirl as well.  And I still have the dump of the working setup from when you compared the diffs against dev.  I can try to dig it up from the Pi we worked on and toss it in a gist.  Though I'll hold on doing so if your changes work.  Glad you've got another MDT user up and running!

**Comment by Bender1061** [comment]
So I'm having issues while it tries to Run nightscout/glucose.json 

```
edison@Bender:~/johnopenaps$ openaps report invoke nightscout/glucose.json
ns://JSON/shell/nightscout/glucose.json
No JSON object could be decoded
Unknown request: mm-format-ns-glucose

openaps use ns shell get entries.json 'count=10'
openaps use ns shell upload treatments.json recently/combined-treatments.json

  -h                                  This message.
  get type args                                  Get records of type from
                                                 Nightscout matching args.

  oref0_glucose [tz] [args]                      Get records matching oref0
                                                 requirements according to args
                                                 from Nightscout.
                                                 tz should be the name of the
                                                 timezones device (default with
                                                 no args is tz).
                                                 args are ampersand separated
                                                 arguments to append to the
                                                 search query for Nightscout.
  oref0_glucose_without_zone [args]              Like oref0_glucose but without
                                                 rezoning.
  oref0_glucose_since expr [tz] [count]          Get records matching oref0
                                                 requirements filtered by a date calculated by expr
                                                 from Nightscout.
                                                 expr is used with date -d, for example -6hours.
                                                 tz should be the name of the
                                                 timezones device (default with
                                                 no args is tz).
                                                 count is the max count (needed to overide NS default of 10).
  upload endpoint file                           Upload a file to the Nightscout endpoint.
  latest-treatment-time                          - get latest treatment time from Nightscout
  format-recent-history-treatments history model - Formats medtronic pump
                                                 history and model into
                                                 Nightscout compatible
                                                 treatments.

  format-recent-type ZONE type file              - Selects elements from the
                                                 file where the elements would
                                                 satisfy a gap in the last 1000
                                                 Nightscout records.

  upload-non-empty-treatments file               - Upload a non empty treatments
                                                 file to Nightscout.
  lsgaps tz entries                              - Re-use openaps timezone device
                                                 to find gaps in a type (entries)
                                                 by default.
  upload-non-empty-type type file
  status                                         - ns-status
  get-status                                     - status - get NS status
  preflight                                      - NS preflight
  temp_targets [expr]                            - Get temp target treatments from Nightscout
                                                 expr is used with date -d, default is -24hours.
  carb_history [expr]                            - Get treatments with carbs from Nightscout
                                                 expr is used with date -d, default is -24hours.
## Nightscout Endpoints

* entries.json - Glucose values, mbgs, sensor data.
* treatments.json - Pump history, bolus, treatments, temp basals.
* devicestatus.json - Battery levels, reservoir.
* profile.json - Planned rates/settings/ratios/sensitivities.
* status.json  - Server status.

## Examples


### Get records from Nightscout

Use the get feature which takes two arguments: the name of the endpoint
(entries, devicestatus, treatments, profiles) and any query arguments to append
to the argument string. 'count=10' is a reasonable debugging value.
The query-params can be used to generate any query Nightscout can respond to.

    openaps use ns shell get $endpoint $query-params

### Unifying pump treatments in Nightscout

To upload treatments data to Nightscout, prepare you zoned glucose, and pump
model reports, and use the following two reports:

    openaps report add nightscout/recent-treatments.json JSON ns shell  format-recent-history-treatments monitor/pump-history.json model.json
    openaps report add nightscout/uploaded.json JSON  ns shell upload-non-empty-treatments  nightscout/recent-treatments.json

Here are the equivalent uses:

    openaps use ns shell format-recent-history-treatments monitor/pump-history.json model.json
    openaps use ns shell upload-non-empty-treatments nightscout/recent-treatments.json

The first report runs the format-recent-history-treatments use, which fetches
data from Nightscout and determines which of the latest deltas from openaps
need to be sent. The second one uses the upload-non-empty-treatments use to
upload treatments to Nightscout, if there is any data to upload.

### Uploading glucose values to Nightscout

Format potential entries (glucose values) for Nightscout.

    openaps use ns shell format-recent-type tz entries monitor/glucose.json  | json -a dateString | wc -l
    # Add it as a report
    openaps report add nightscout/recent-missing-entries.json JSON ns shell format-recent-type tz entries monitor/glucose.json
    # fetch data for first time
    openaps report invoke nightscout/recent-missing-entries.json

    # add report for uploading to NS
    openaps report add nightscout/uploaded-entries.json JSON  ns shell upload entries.json nightscout/recent-missing-entries.json
    # upload for fist time.
    openaps report invoke nightscout/uploaded-entries.json

Traceback (most recent call last):
  File "/usr/local/bin/openaps-report", line 82, in <module>
    app( )
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/__init__.py", line 51, in __call__
    self.run(self.args)
  File "/usr/local/bin/openaps-report", line 75, in run
    output = app(args, self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/cli/subcommand.py", line 52, in __call__
    return self.method.main(args, app)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/invoke.py", line 48, in main
    reporters.Reporter(report, device, task)(output)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/reporters/__init__.py", line 33, in __call__
    self.blob = self.serialize(data)
  File "/usr/local/lib/python2.7/dist-packages/openaps/reports/reporters/__init__.py", line 31, in serialize
    return self.method.serialize(render(data), self)
  File "/usr/local/lib/python2.7/dist-packages/openaps/vendors/process.py", line 56, in prerender_json
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
edison@Bender:~/johnopenaps$
```

**Comment by Bender1061** [comment]
and my monitor/glucose.json looks fine.

**Comment by scottleibrand** [comment]
@bender1061 you have an old `nightscout`. Pull the latest oref0-setup branch and do `npm run global-install` to update it.

**Comment by Bender1061** [comment]
LOL, Yeah I just did that and it's working

**Comment by Bender1061** [comment]
wait are you saying use oref0-setup and not mm-cgm?

**Comment by scottleibrand** [comment]
No, sorry, I got them confused.

**Comment by Bender1061** [comment]
Now I was when i was trying to get this to work, I took off the mmconnect from the enable on my nightscout site. Do you think I need to keep that out? doesn't the new Nightscout (non dev) support multiple CGM's ?

**Comment by scottleibrand** [comment]
You could try reenabling that. I think it would handle two CGM sources fine, but not 100% sure

**Comment by Bender1061** [comment]
Interesting so it does allow multiple CGM sources, but the time is different 

image

**Comment by Bender1061** [comment]
I tried just adding the mmconnect first, and that worked fine, then I turned the connect back on and this happened. I'm not exactly sure what that is going to do to the loop, I'm going to let it run a few hours and see if that makes a difference.
yes i know I don't really need the connect at all, but there are those times I've described above where it will safely bring me back down automatically if my BG goes HIGH. It's nice if I go to bed HIGH and as long as the calibration isn't needed I wake up with perfect BG.

**Comment by scottleibrand** [comment]
I know oref0 will deal fine with multiple BG sources. If they are offset in time and different values, then it might make the temps oscillate a bit, but if they're both reporting the same sensor value then it will be completely unaffected.

**Comment by Bender1061** [comment]
so interesting enough, after I first turned on my mmconnect, it did the whole double thing, but now while both are working, it looks correct. So Awesome!

image

**Comment by Bender1061** [comment]
I believe it's because he connect uploads faster, so the rig is reading the data and combining it correctly, and not making a double upload.

**Comment by Bender1061** [comment]
Ok, since I've been playing with this branch. I've had the .git folder mess up 2 times. Where I had to go as root, delete the .git and then run oref0-reset-git to get it up and running.
First time I had this happen I just deleted the aps file and reinstalled, this time I just did the above and it's running again.

now this is only with one of my rigs as it's what I'm running this on. Is there something different between this and dev that would be causing that?

I've not had this happen before, granted I've seen people having this issue on gitter. 

we have the oref0-reset-git in the crom, but is there a good way to detect when this happens and automate the deletion of the .git and then run oref0-reset-git?

or like I asked above, is there something in this branch that caused this issue.

**Comment by scottleibrand** [comment]
That's because mm-cgm doesn't have the truncate-git stuff yet.  Merging that back in from dev via https://github.com/openaps/oref0/pull/260

**Comment by Bender1061** [comment]
Running it now, hopefully it lasts longer now :-) but the upload is working well

**Comment by Bender1061** [comment]
Something I do notice though, is it's about 10 mins before it updates with the last One or two CGM data points. Not horrible by any means, but still seams long.

**Comment by scottleibrand** [comment]
You might want to dig into the sequence of which reports get run when, and see if there are any improvements that could be made to speed it up.  Feel free to PR in any improvements if you find them.

**Comment by Bender1061** [comment]
So, while it does seam later, the time really is not a problem. Because really within 10 mins on nightscout is still plenty accurate. The rig is still reading it from the pump plenty fast to see and make adjustments. But I've ween running this for 4 days and it's working great.

**Comment by scottleibrand** [comment]
Great to hear.  Anything else we need to look at, or would you 👍 this for merge?

**Comment by Bender1061** [comment]
I have been testing this without my mmconnect for the past 4 days as well, just to make sure everything works.

**Comment by scottleibrand** [comment]
And..?  

Merge, or not yet?  :-)

**Comment by Bender1061** [comment]
Merge it!

**Pull request merged**
