### PR TITLE
Slightly refactor oref0 meal to read all the data before

### PR DESCRIPTION
**Pull request by alimhassam**
trying to match bolus wizard entries to corresponding
bolus entries.

This allows out of order bolus and bolus wizard entries to
still work correctly.

Before this change, when the bolus entry was after the bolusWizard
entry, the carb was being skipped because no corresponding
bolus was seen.

I'm hoping this will help with the issue reported in #952

### CODE REVIEW

**Comment by alimhassam** [comment]
This was only lightly tested on the go-explorer-hat branch which doesnt' have the issue. Ideally would be good to have someone on the dev branch who can reproduce the 'skipping carb' issue relyably, and see if this fixes it.

**Comment by scottleibrand** [comment]
Also need to figure out why the unit tests are failing and fix that.

**Comment by alimhassam** [comment]
The failed test was be cause there was a record with a bolus after the boluswizard in the test case. It was previously skipped in test, but should have been included i believe... so i changed the expected count to 6.

**Comment by PieterGit** [comment]
👍 tested this branch, and added an extra information https://github.com/PieterGit/oref0/commits/robust-oref0-meal 
Please cherry pick my extra logging, and let's merge it do dev

**Comment by alimhassam** [comment]
cherry-picked logging improvements from @PieterGit.
as per discussion here https://gitter.im/openaps/oref0?at=5aae657227c509a774773ab1, this might also relate to #709 and #777

**Comment by PieterGit** [comment]
First results of this branch are very good with 754WW and carbs via boluswizard. Will report more feedback  later.  @JELCRAWFORD and @LongboatAline are you able to test this branch/PR as well?
@alimhassam : are we able to find out if this was a regression, or was an unfound bug?

**Comment by alimhassam** [comment]
@tim2000s would you be able to post a excerpt of your `monitor/pumphistory-merged.json` file including a `BolusWizard` and a corresponding `Bolus` entry? I'm curious to see what's different on your setup.

**Comment by tim2000s** [comment]
I’ll test it again this morning @alimhassam

**Comment by PieterGit** [comment]
btw i also did a `aptitude -t jessie-backports upgrade jq` to upgrade jq to 1.5. I think this should be backported to dev as well. Any objections?

**Comment by alimhassam** [comment]
@PieterGit

I agree, I think that would be good. From what I understand jq 1.4 sort might not be stable which could cause unpredictable behavior... 
Might explain why it used to work sometimes for some people.

I think using 1.5 would make things easier to deal with.

**Comment by alimhassam** [comment]
@PieterGit to answer your earlier question I *think* this issue might hace got introduced when merged pump history was added with #513
Though would needed to be bisected/tested to confirm which is probably not worth the effort.

**Comment by JELCRAWFORD** [comment]
We did not see this problem last night or this morning with this fix in place. I have not reviewed school time bolus records yet, but can confirm later on. Curious this seems like it may be pump specific. 

Thx all.

**Comment by tim2000s** [comment]
@alimhassam - here you go...

```
{
    "_type": "Bolus",
    "_description": "Bolus 2018-03-19T08:40:36 head[4], body[0] op[0x01]",
    "timestamp": "2018-03-19T08:40:36+00:00",
    "_body": "",
    "appended": [
      {
        "_type": "UnabsorbedInsulinBolus",
        "_description": "UnabsorbedInsulinBolus unknown head[41], body[0] op[0x5c]",
        "_body": "",
        "_head": "5c290c3444203e443c484404524404984408a24404b644101a54042454102e5408385404ce5408d854",
        "data": [
          {
            "amount": 0.3,
            "age": 52
          },
          {
            "amount": 0.8,
            "age": 62
          },
          {
            "amount": 1.5,
            "age": 72
          },
          {
            "amount": 0.1,
            "age": 82
          },
          {
            "amount": 0.1,
            "age": 152
          },
          {
            "amount": 0.2,
            "age": 162
          },
          {
            "amount": 0.1,
            "age": 182
          },
          {
            "amount": 0.4,
            "age": 282
          },
          {
            "amount": 0.1,
"age": 292
          },
          {
            "amount": 0.4,
            "age": 302
          },
          {
            "amount": 0.2,
            "age": 312
          },
          {
            "amount": 0.1,
            "age": 462
          },
          {
            "amount": 0.2,
            "age": 472
          }
        ],
        "_date": ""
      }
    ],
    "programmed": 3.5,
    "duration": 0,
    "amount": 3.5,
    "_head": "01232300",
    "type": "normal",
    "_date": "24e8481312"
  },
  {
    "unknown_byte[8]": 0,
    "_type": "BolusWizard",
    "bg": 0,
    "_byte[5]": 0,
    "unknown_byte[10]": 0,
    "_description": "BolusWizard 2018-03-19T08:40:36 head[2], body[13] op[0x5b]",
    "timestamp": "2018-03-19T08:40:36+00:00",
    "_body": "1e900819370025000000002537",
    "bg_target_high": 55,
    "sensitivity": 25,
    "carb_ratio": 8,
    "food_estimate": 3.7,
    "unabsorbed_insulin_total": 0,
    "correction_estimate": 0,
    "carb_input": 30,
    "_head": "5b00",
    "unabsorbed_insulin_count": "??",
"_byte[7]": 0,
    "bolus_estimate": 3.7,
    "_date": "24e8081312",
    "bg_target_low": 55
  },
```

**Comment by PieterGit** [comment]
~ 36 hours without extra `Skipping bolus wizard entry`, except the bolus wizard entry without carbs. 
Median improved almost 1 mmol/L over last two days, so I think it's definitely an improvement, for 754WW users that use pump for bolussing. @scottleibrand is this ready for broader testing on dev?

**Comment by tim2000s** [comment]
Given this doesn’t seem to affect 722 (or maybe 715) users, does the change require broader testing with those pumps?

**Comment by alimhassam** [comment]
@tim2000s just want to confirm that's the order you see the records in `monitor/pumphistory-merged.json` ? could you also confirm the order of the records in `monitor/pumphistory-zoned.json` and `settings/pumphistory-24h-zoned.json` ??

I've been also running this change on the go-explorer-hat branch without any visible negative impact, i think this is ready to merge to `dev`, and we could also merge `dev` to `go-explorer-hat`. (I'm using a 722 pump. )

I'm not sure if the different behavior across people is related to the pump, or the jq or the decocare  version or anything, but i don't think it matters that much. 
The change should work fix the issue for people who are having issues, and shouldn't affect anything else.

**Comment by JELCRAWFORD** [comment]
@alimhassam - I'm not sure this is fixed.  We are getting the following output in the middle of the pump loop log.  Mike indicates that we have occasionally gotten all this 'extra' stuff in the middle of the pump loop log.  I have not seen it before today, though admittedly I don't watch via this log as often as he does.  As you scroll down, you will see the "skipping" comment about midway...  I've bold faced it.

_description: 'BasalProfileStart 2018-03-19T09:00:00 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T09:00:00-06:00',
  _body: '121600',
  profile_index: 5,
  _head: '7b05',
  rate: 0.55,
  offset: 32400000,
  _date: '00c0091312' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-19T08:41:53 head[2], body[1] op[0x33]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '35e9085312' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T08:41:53 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '0e1600',
  profile_index: 4,
  _head: '7b04',
  rate: 0.55,
  offset: 25200000,
  _date: '35e9081312' }
No duration found for 0 U/hr basalundefined { _type: 'ChangeTime',
  _description: 'ChangeTime 2018-03-18T22:28:28 head[2], body[0] op[0x17]',
  timestamp: '2018-03-18T22:28:28-06:00',
  _body: '',
  _head: '1700',
  _date: '1cdc165212' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-18T22:18:14 head[2], body[1] op[0x33]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '0ed2165212' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-18T22:18:14 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '291400',
  profile_index: 8,
  _head: '7b08',
  rate: 0.5,
  offset: 73800000,
  _date: '0ed2161212' }
No duration found for 0 U/hr basalundefined { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T09:00:00 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T09:00:00-06:00',
  _body: '121600',
  profile_index: 5,
  _head: '7b05',
  rate: 0.55,
  offset: 32400000,
  _date: '00c0091312' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-19T08:41:53 head[2], body[1] op[0x33]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '35e9085312' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T08:41:53 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '0e1600',
  profile_index: 4,
  _head: '7b04',
  rate: 0.55,
  offset: 25200000,
  _date: '35e9081312' }
No duration found for 0 U/hr basalundefined { _type: 'ChangeTime',
  _description: 'ChangeTime 2018-03-18T22:28:28 head[2], body[0] op[0x17]',
  timestamp: '2018-03-18T22:28:28-06:00',
  _body: '',
  _head: '1700',
  _date: '1cdc165212' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-18T22:18:14 head[2], body[1] op[0x33]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '0ed2165212' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-18T22:18:14 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '291400',
  profile_index: 8,
  _head: '7b08',
  rate: 0.5,
  offset: 73800000,
  _date: '0ed2161212' }
 **pumphistoryskipping bolus wizard entry with 21 g carbs and no insulin**
No duration found for 0 U/hr basalundefined { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T09:00:00 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T09:00:00-06:00',
  _body: '121600',
  profile_index: 5,
  _head: '7b05',
  rate: 0.55,
  offset: 32400000,
  _date: '00c0091312' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-19T08:41:53 head[2], body[1] op[0x33]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '35e9085312' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T08:41:53 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '0e1600',
  profile_index: 4,
  _head: '7b04',
  rate: 0.55,
  offset: 25200000,
  _date: '35e9081312' }
No duration found for 0 U/hr basalundefined { _type: 'ChangeTime',
  _description: 'ChangeTime 2018-03-18T22:28:28 head[2], body[0] op[0x17]',
  timestamp: '2018-03-18T22:28:28-06:00',
  _body: '',
  _head: '1700',
  _date: '1cdc165212' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-18T22:18:14 head[2], body[1] op[0x33]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '0ed2165212' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-18T22:18:14 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '291400',
  profile_index: 8,
  _head: '7b08',
  rate: 0.5,
  offset: 73800000,
  _date: '0ed2161212' }
No duration found for 0 U/hr basalundefined { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T09:00:00 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T09:00:00-06:00',
  _body: '121600',
  profile_index: 5,
  _head: '7b05',
  rate: 0.55,
  offset: 32400000,
  _date: '00c0091312' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-19T08:41:53 head[2], body[1] op[0x33]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '35e9085312' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T08:41:53 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '0e1600',
  profile_index: 4,
  _head: '7b04',
  rate: 0.55,
  offset: 25200000,
  _date: '35e9081312' }
No duration found for 0 U/hr basalundefined { _type: 'ChangeTime',
  _description: 'ChangeTime 2018-03-18T22:28:28 head[2], body[0] op[0x17]',
  timestamp: '2018-03-18T22:28:28-06:00',
  _body: '',
  _head: '1700',
  _date: '1cdc165212' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-18T22:18:14 head[2], body[1] op[0x33]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '0ed2165212' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-18T22:18:14 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '291400',
  profile_index: 8,
  _head: '7b08',
  rate: 0.5,
  offset: 73800000,
  _date: '0ed2161212' }
No duration found for 0 U/hr basalundefined { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T09:00:00 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T09:00:00-06:00',
  _body: '121600',
  profile_index: 5,
  _head: '7b05',
  rate: 0.55,
  offset: 32400000,
  _date: '00c0091312' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-19T08:41:53 head[2], body[1] op[0x33]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '35e9085312' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T08:41:53 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '0e1600',
  profile_index: 4,
  _head: '7b04',
  rate: 0.55,
  offset: 25200000,
  _date: '35e9081312' }
No duration found for 0 U/hr basalundefined { _type: 'ChangeTime',
  _description: 'ChangeTime 2018-03-18T22:28:28 head[2], body[0] op[0x17]',
  timestamp: '2018-03-18T22:28:28-06:00',
  _body: '',
  _head: '1700',
  _date: '1cdc165212' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-18T22:18:14 head[2], body[1] op[0x33]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '0ed2165212' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-18T22:18:14 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '291400',
  profile_index: 8,
  _head: '7b08',
  rate: 0.5,
  offset: 73800000,
  _date: '0ed2161212' }
 and meal.json
No duration found for 0 U/hr basalundefined { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T09:00:00 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T09:00:00-06:00',
  _body: '121600',
  profile_index: 5,
  _head: '7b05',
  rate: 0.55,
  offset: 32400000,
  _date: '00c0091312' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-19T08:41:53 head[2], body[1] op[0x33]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '35e9085312' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T08:41:53 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '0e1600',
  profile_index: 4,
  _head: '7b04',
  rate: 0.55,
  offset: 25200000,
  _date: '35e9081312' }
No duration found for 0 U/hr basalundefined { _type: 'ChangeTime',
  _description: 'ChangeTime 2018-03-18T22:28:28 head[2], body[0] op[0x17]',
  timestamp: '2018-03-18T22:28:28-06:00',
  _body: '',
  _head: '1700',
  _date: '1cdc165212' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-18T22:18:14 head[2], body[1] op[0x33]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '0ed2165212' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-18T22:18:14 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '291400',
  profile_index: 8,
  _head: '7b08',
  rate: 0.5,
  offset: 73800000,
  _date: '0ed2161212' }
No duration found for 0 U/hr basalundefined { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T09:00:00 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T09:00:00-06:00',
  _body: '121600',
  profile_index: 5,
  _head: '7b05',
  rate: 0.55,
  offset: 32400000,
  _date: '00c0091312' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-19T08:41:53 head[2], body[1] op[0x33]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '35e9085312' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-19T08:41:53 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-19T08:41:53-06:00',
  _body: '0e1600',
  profile_index: 4,
  _head: '7b04',
  rate: 0.55,
  offset: 25200000,
  _date: '35e9081312' }
No duration found for 0 U/hr basalundefined { _type: 'ChangeTime',
  _description: 'ChangeTime 2018-03-18T22:28:28 head[2], body[0] op[0x17]',
  timestamp: '2018-03-18T22:28:28-06:00',
  _body: '',
  _head: '1700',
  _date: '1cdc165212' } { _type: 'TempBasal',
  temp: 'absolute',
  _description: 'TempBasal 2018-03-18T22:18:14 head[2], body[1] op[0x33]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '00',
  _head: '3300',
  rate: 0,
  _date: '0ed2165212' } { _type: 'BasalProfileStart',
  _description: 'BasalProfileStart 2018-03-18T22:18:14 head[2], body[3] op[0x7b]',
  timestamp: '2018-03-18T22:18:14-06:00',
  _body: '291400',
  profile_index: 8,
  _head: '7b08',
  rate: 0.5,
  offset: 73800000,
  _date: '0ed2161212' }
IOB: 2.508
Your instance of oref0 [0.6.1-dev, 954test] is up-to-date.
Completed oref0-pump-loop at Mon Mar 19 21:50:38 MDT 2018

**Comment by alimhassam** [comment]
Oh wow, will need to figure out what's causing this never saw this before either. It seems like there are basal profile changes and time changes interleaved with TempBasal records in your pump history file.

Could you also post that 21g `BolusWizard` and associated `Bolus` entry from your monitor/pumphistory-merged.json file?

**Comment by JELCRAWFORD** [comment]
Yup - here it is.  Let me know if you want more of it... 


"_type": "BolusWizard",
    "bg": 11.4,
    "_description": "BolusWizard 2018-03-18T20:01:44 head[2], body[15] op[0x5b]",
    "timestamp": "2018-03-18T20:01:44-06:00",
    "_body": "1590005f2d3534005800005c005835",
    "carb_input": 21,
    "bg_target_high": 5.3,
    "sensitivity": 4.5,
    "carb_ratio": 9.5,
    "food_estimate": 2.2,
    "unabsorbed_insulin_total": 2.3,
    "correction_estimate": 1.3,
    "bg_target_low": 5.3,
    "_head": "5b72",
    "bolus_estimate": 2.2,
    "_date": "2cc1141212"
  },
  {
    "programmed": 2.2,
    "_type": "Bolus",
    "_description": "Bolus 2018-03-18T20:01:44 head[8], body[0] op[0x01]",
    "timestamp": "2018-03-18T20:01:44-06:00",
    "_body": "",
    "_head": "0100580058005c00",
    "amount": 2.2,
    "unabsorbed": 2.3,
    "duration": 0,
    "type": "normal",
    "_date": "2cc1541212"

**Comment by alimhassam** [comment]
I think all these records in the logs might be due to the Basal profile change which is probably something not well supported, is that something you use?

The skipping message is more puzzling can't figure it out right now...

**Comment by JELCRAWFORD** [comment]
Well, that's the rub of it - we didn't do a basal profile change...  We don't use that feature.  The boy's been on the same basal profile throughout.

**Comment by tim2000s** [comment]
@JELCRAWFORD dumb couple of questions. 

1. Are you using the primary basal profile or is the pump set on a secondary one?

2. Could the pump have been fiddled with by your son just playing with it?

@alimhassam - my records are in the order taken from the file.

**Comment by PieterGit** [comment]
@JELCRAWFORD : if you see `skipping` instead of `Skipping` you don't have (the latest) version of this PR running. Are you sure you applied this PR? (or did you only not pull my logging improvements)
I don't see any `Skipping bolus wizard entry` items anymore with a 754WW.

@alimhassam is there anything I can further test? I'm running this branch without issues as far as I can see.

**Comment by alimhassam** [comment]
I'd like to get this merged to dev so more people can test.

**Comment by alimhassam** [comment]
thanks @scottleibrand 

@JELCRAWFORD if you update to dev, and still see the `Skipping bolus wizard` message let me know. 

It shouldn't occur in theory and might suggest something off with your setup. We've seen situations with 2 myopenaps loops running in different directories recently, could this explain your situation? (just a wild guess at this point).

**Comment by JELCRAWFORD** [comment]
updated to dev right after fix was merged.  No evidence of skipping or Skipping since update.  Will watch again tomorrow.

Don't have an instance of 2x openaps loops running from same rig.  Haven't seen odd output this evening either, but before yesterday I'd never seen it - don't know frequency in that regard.  

Thx for your assistance with this!

**Pull request merged**
