### PR TITLE
Added shell scripts to format dexcom reading into a NS preferred format

### PR DESCRIPTION
**Pull request by ThomasEmge**
I have added two scripts:
1. formatting glucose and iter_calibrations readings to sgv and mbg
2. formatting sensor_insertions to treatments

I also modified nightscout.sh to allow for culling of the dexcom readings

### CODE REVIEW

**Comment by bewest** [comment]
Looking good.

**Comment by scottleibrand** [comment]
@inform880 and @jasoncalabrese can you test this and see whether it at least partially addresses https://github.com/openaps/oref0/issues/88 ?

**Comment by jasoncalabrese** [comment]
I didn't find a way to get the cal records, with the slope and intercept.  We need that to use the sensor records.  The calibrations are mbgs.

**Comment by scottleibrand** [comment]
@jasoncalabrese does that just affect raw?  Do these scripts look good for getting SGVs at least?

**Comment by jasoncalabrese** [comment]
Yeah, that's just for raw, only issue I see with this related to the device name.  I think we should stick with the openaps:// prefix, something like openaps://dexcom.

**Comment by jasoncalabrese** [comment]
Think we want a different treatment eventType so NS will use it for the sage plugin, need to look that up, but on phone now.

**Comment by jasoncalabrese** [comment]
We should use `Sensor Start` for the `eventType` https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/plugins/sensorage.js#L80

**Comment by scottleibrand** [comment]
Not sure why this got stalled.  But is it still needed in light of `oref0_glucose`?

**Comment by ThomasEmge** [comment]
I haven't been actively using it but the code itself is sitting in my loop in case I want to plug in the dexcom to the rpi. Where can I find `oref0_glucose`?

**Comment by scottleibrand** [comment]
I don't think this is needed any longer in light of oref0_glucose and https://github.com/openaps/docs/wiki/CGM-Loop-with-openxshareble-scratchpad - closing.

**Pull request closed without merging**
