### PR TITLE
Empty target fix

### LINKED ISSUE #1271: [empty] value for Temporary Targets set in Nightscout => negative values for basal and ISF in oref0
**Describe the bug**
I set a 360 minutes temp target using the Nightscout browser from iPhone Safari. My plan was to set a high temp target (150 or so, don't remember). I probably did not enter a target in either one or in both of the target fields, and I (vaguely) remember backing out once. 

Temp Target was displayed as "Target = 0" by oref0. That resulted in negative ISF and negative basal rates to be returned, and zero temp basal and no SMBs for the duration, with exception of positive basal and small SMBs for a short time after carb entries.

The temporary target still showed in the upper area of the Nightscout browser graph 18 hours after temp target was set to end. Clearing Mongo Device Status dB did not clear the display, however, deleting the TT entry from the NS treatments dB did remove it from the NS display.

**To Reproduce**
Note - I was not able to reproduce the error just now while setting **no values for both upper and lower TT**; rig is not quite "buying" pump history and meal: 
Couldn't refresh_pumphistory_and_meal
oref0-pump-loop failed.

**Steps to (maybe?) reproduce the behavior:**
1. Set Temp Target in Nightscout browser using "manual" option. 
2. set time (360 min)
3. omit setting targets 

**Expected behavior**
Ideally - NS browser would not allow [null] values to be entered in the (manual) TempTarget screen. 

oref0 behavior was safe for preventing Hypo - it did not take the target = 0 literally. (Thank you!). 

This behavior could be a problem if a long undefined TT was set, and user were to not notice, interact and rethink causes of resulting high BGs for a long time, e.g. overnight, especially for people prone to DKA (I am not)

**Screenshots**
Here's a screenshot from today showing the [Null value] Temp Target still showing 18 hours later in NS. Nightscout showing temp trget from yesterday at 360 or so

**Smartphone (please complete the following information):**
iOS is 12.3.2 - iPhone 8 Plus
**Setup Information (please complete the following information):**
* Pump type: Medtronic 522, v. 2.4A firmware
* CGM type: Dexcom G6 via Lookout and Dexcom App
* Rig type: Edison/Explorer Board rig
* oref0 version 0.7.0-dev

**Additional context**
from pump loop log ```Sensitivity ratio set to -1.5 based on temp target of 0; Adjusting basal from 1.1 to -1.7; ISF from 66 to -44; CR: 14.025``` 

Loop log entry showing the situation: 
Starting oref0-pump-loop at Sat Jun 22 17:05:03 PDT 2019 with 20 second wait_for_silence:
Waiting up to 4 minutes for new BG: .glucose.json newer than pump_loop_completed

Listening for 20s: .No interfering pump comms detected from other rigs (this is a good thing!)
Continuing oref0-pump-loop at Sat Jun 22 17:05:38 PDT 2019
Preflight OK. Profile less than 60m old; Profile valid. Pump history updated through 2019-06-22T17:02:26-07:00 with 0 new records; meal.json refreshed: {"carbs":50,"nsCarbs":50,"bwCarbs":0,"journalCarbs":0,"mealCOB":36,"currentDeviation":11.52,"maxDeviation":9.45,"minDeviation":1.38,"slopeFromMaxDeviation":0,"slopeFromMinDeviation":2.385,"allDeviations":[12,9,5,1,6],"lastCarbTime":1561244222430,"bwFound":false}
Listening for 10s: .No interfering pump comms detected from other rigs (this is a good thing!)
Continuing oref0-pump-loop at Sat Jun 22 17:06:29 PDT 2019
Checking that pump clock: "2019-06-22T17:06:12-07:00" is within 90s of current time: 2019-06-22T17:06:31-0700
Temp refreshed: monitor/temp_basal.json: {"duration":27,"temp":"absolute","rate":0}
{"carbs":50,"nsCarbs":50,"bwCarbs":0,"journalCarbs":0,"mealCOB":36,"currentDeviation":11.52,"maxDeviation":9.45,"minDeviation":1.38,"slopeFromMaxDeviation":0,"slopeFromMinDeviation":2.385,"allDeviations":[12,9,5,1,6],"lastCarbTime":1561244222430,"bwFound":false}
Autotune exists! Hoorah! You can use microbolus-related features.
{"iob":-1.035,"activity":-0.0084,"basaliob":-1.425,"bolusiob":0.39,**_"netbasalinsulin":-5.2_**,"bolusinsulin":3,"time":"2019-06-23T00:06:14.000Z","iobWithZeroTemp":{"iob":-1.035,"activity":-0.0084,"basaliob":-1.425,"bolusiob":0.39,"netbasalinsulin":-5.2,"bolusinsulin":3,"time":"2019-06-23T00:06:14.000Z"},"lastBolusTime":1561243599000,"lastTemp":{"rate":0,"timestamp":"2019-06-22T17:02:26-07:00","started_at":"2019-06-23T00:02:26.000Z","date":1561248146000,"duration":4.8}}
{"delta":10,"glucose":267,"noise":1,"short_avgdelta":10.83,"long_avgdelta":7.24,"date":1561248259739,"last_cal":0}
**_Sensitivity ratio set to -0.69 based on temp target of 0; Adjusting basal from 1.05 to -0.75; ISF from 147.2 to -213.4;_** CR: 20
currenttemp: { duration: 27, temp: 'absolute', rate: 0 } lastTempAge: 4 m tempModulus: 1 m
SMB enabled for COB of 36
profile.sens: 147.243 sens: -213.4 CSF: -10.67
Limiting carb impact from 19 to -26.7 mg/dL/5m ( 30 g/h )
Last carbs 70 minutes ago; remainingCATime: 3.6 hours; 28% carbs absorbed
Carb Impact: -26.7 mg/dL per 5m; CI Duration: 2.4 hours; remaining CI (~2h peak): -17.8 mg/dL per 5m
predCIs (mg/dL/5m): 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
remainingCIs:       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 3 4
UAM Impact: 19 mg/dL per 5m; UAM Duration: 2 hours
minPredBG: -33 minIOBPredBG: 39 minZTGuardBG: -421 minCOBPredBG: 39 minUAMPredBG: 116 avgPredBG: -33 COB: 36 / 50
minGuardBG -39 projected below 20 - disabling SMB
BG projected to remain above 0 for 240 minutes
naive_eventualBG: 46 bgUndershoot: -26 zeroTempDuration: 240 zeroTempEffect: -908 carbsReq: -106
2019-06-23T00:06:42.802Z
Checking deliverAt: 2019-06-23T00:06:42.802Z is within 1m of current time: Sat Jun 22 17:06:42 PDT 2019
and that smb-suggested.json is less than 1m old
enact/smb-suggested.json: {"temp":"absolute","bg":267,"tick":"+10","eventualBG":160,"insulinReq":0,"reservoir":"127.5\n","deliverAt":"2019-06-23T00:06:42.802Z","sensitivityRatio":-0.69,"COB":36,"IOB":-1.035}
"COB: 36, Dev: 114, BGI: -9, ISF: -213, CR: 20, Target: 0, minPredBG -33, minGuardBG -39, IOBpredBG 39; minGuardBG -39<20 27m left and 0 ~ req 0U/hr: no temp required"
IOB: [267,234,202,173,145,120,97,77,59,43,39,39,39]
ZT:  [267,258,249,239,229,218,208,196,185,173,161,149,136,123,110,97,83,69,55,41,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39]
No smb_enact needed. Checking pump status (suspended/bolusing): {"status":"normal","bolusing":false,"suspended":false}
Temp refreshed: monitor/temp_basal.json: {"duration":27,"temp":"absolute","rate":0}
No bolus needed. Settings less than 30 minutes old. Your instance of oref0 [0.7.0-dev, dev] is up-to-date.
Completed oref0-pump-loop at Sat Jun 22 17:06:48 PDT 2019

### PR DESCRIPTION
**Pull request by scottleibrand**
Fixes #1271, where a temp target entry without a min/max target value would bypass the existing validity checks and result in insufficient insulin dosing for the duration of the temp target.

This PR skips any temp target values without a valid min (and max, if wide_bg_target_range is set) target value.

### CODE REVIEW

**Comment by scottleibrand** [comment]
I've tested this successfully via the following method:

 - Update 1 rig to the empty-target-fix branch, and leave one rig on dev.
 - Set a temp target in NS, by selecting +, Temporary Target, Reason: Manual, add a duration, and leave Top and Bottom blank.
 - Allow both rigs to download the updated temp targets and perform a loop.

The dev rig experiences the bug, and reports:
`Sensitivity ratio set to -1.5 based on temp target of 0; Adjusting basal from 1.4 to -2.05; ISF from 66 to -44; CR: 14.025`

The empty-target-fix rig ignores the bad temp target and reports:
`Autosens ratio: 0.98; Adjusting basal from 1.4 to 1.35; target_bg from 100 to 101; ISF from 66 to 67.3; CR: 14.025`

**Comment by scottleibrand** [comment]
(This PR also includes a null check on `peakDeviations[2]`, which is an unrelated corner case I'd fixed and forgotten to commit.)

**Comment by straykatz** [comment]
Your description looks reasonable ... glad you were able to duplicate the issue. 

What do you think about a comment in the log that acknowledges that there is a temp target set, but that it is invalid? 

I'll try to update a rig with the branch, but I don't think I'll have time tonight to go through with it.

**Comment by scottleibrand** [comment]
I added some debugging output (`console.error("eventualBG target range invalid: " + temptargets_data[i].targetBottom + "-" + temptargets_data[i].targetTop);`), but that command is run with its console.error redirected, so it only shows up in the main pump-loop.log if you run oref0-pump-loop manually with OREF0_DEBUG set. Given that, I'd rather not add any additional complexity to expose that further in the logs.

I think the proper place to warn the user that their temp target is invalid is in Nightscout when it's initially being set, as you noted in https://github.com/nightscout/cgm-remote-monitor/issues/4702

If no objections, I'll go ahead and merge this to dev for further testing there.

**Comment by straykatz** [comment]
sounds good :)

**Comment by straykatz** [comment]
I guess instead of testing the branch, I'll just update dev on one of the rigs ... (I have never actually updated to a branch :-D )

**Pull request merged**
