### PR TITLE
Dev to master for next release

### PR DESCRIPTION
**Pull request by scottleibrand**

### CODE REVIEW

**Comment by scottleibrand** [comment]
We'd like to do a patch release to get the https://github.com/openaps/oref0/pull/411 "spidev5.1 already in use" workaround and the https://github.com/openaps/oref0/pull/404 carb treatment sorting fix released.  There are some other changes in here as well, but they're mostly minor.  Does anyone see anything else that needs further testing before we release dev to master?

**Comment by jbwittmer** [comment]
I've been running current dev release on two rigs without issues.

**Comment by scottleibrand** [comment]
Last call: if anyone knows of any reason we shouldn't do a release tomorrow, please speak up.

**Comment by PieterGit** [comment]
@scottleibrand : i see several remarks on i-to-b now of people with problems with dev and a PI3/TI USB. I would suggest that you need at least one or two positive people with recent dev branch and a PI3/TI USB combo. If they have problems with the WW pump (mostly installing problems), it will be fixed in the next release with my pull request https://github.com/openaps/oref0/pull/357 but I'm not sure if there aren't regressions with PI3/TI USB and non-WW pump.

**Comment by Bender1061** [comment]
working MDT Edison Explorer  👍

**Comment by PieterGit** [comment]
@scottleibrand : I created https://github.com/openaps/oref0/pull/421 and currently @libxmike will test if those small fixes make his rig work. That will get rid of some of the issues WW-pump users encounter, without all the rest of the stuff that is currently on my devww branch. Please consider including that in the next release. I'm pretty confident those changes improve the code for WW-pump users, without being a hazard for non-WW pump users.

I also changed all the `~` to `$HOME` consistently in `oref0-setup.sh` as you suggested in a code review.

**Pull request merged**
