### PR TITLE
fix broken safety checks with a single pump-loop type

### PR DESCRIPTION
**Pull request by scottleibrand**
Per https://github.com/openaps/oref0/issues/720 the recently added safety checks caused a regression for users of the non-SMB pump-loop.  To fix that, and make sure that future changes to oref0-pump-loop are more thoroughly tested, this deprecates the old pump-loop and consolidates both SMB and non-SMB use cases onto the one formerly known as smb_pump_loop.  The actual bolus commands are not executed if --microbolus is not passed, but everything else is done the same for both loop types.  This results in some extra status checks for non-SMB users, but that shouldn't hurt anything, and helps avoid problems like we saw with the safety checks making assumptions about the state of various data files that weren't met when the basal-only pump-loop did things in a different order.

### CODE REVIEW

**Comment by scottleibrand** [comment]
To test: `cd ~/src/oref0 && git fetch && git checkout pump-loop-type && git pull && npm run global-install`

**Comment by bdr1177** [comment]
I'll plan to test this tonight.

**Comment by scottleibrand** [comment]
Merged to dev for testing there, as it fixes a major bug that is known to be preventing people from looping.

**Comment by Mackwe** [comment]
Have been off-grid for a week. Updating the rig with latest 'dev'. Have you got any feedback from users yet? (Before I go live with this update)? Thanks!

**Comment by scottleibrand** [comment]
Seems to be working well.

**Comment by Mackwe** [comment]
Awesome! And those people are running without the 'microbolus' switch in runagain?

**Comment by scottleibrand** [comment]
Yep.  And in related news, looks like we're going to retire that switch to simplify things further.

**Pull request merged**
