### PR TITLE
Calling out the number one beginner error

### PR DESCRIPTION
**Pull request by danamlewis**
Number one error for beginners that blocks looping is when people don't have the pump set to absolute u/hr (in % basal type instead), which prevents the rig from being able to set temp basals.

(Note: needs testing)

### CODE REVIEW

**Comment by sulkaharo** [comment]
Should this also just stop the loop from executing, so it's immediately obvious something is not right?

**Comment by danamlewis** [comment]
I'd rather they get the full logs still, as there's often other things from the logs they need to fix, too, vs. exiting if they don't have the temp mode set right.

**Comment by scottleibrand** [comment]
If no objections, I'd like to merge this to dev for testing for a 0.5.3 release before we start merging new features (like exponential curves) for an eventual 0.6.0 release.

**Comment by scottleibrand** [comment]
Merged this to 0.6.0-dev. If everything looks good there I'll merge to dev as well for eventual 0.5.3 release.

**Comment by scottleibrand** [comment]
Temp refreshed: monitor/temp_basal.json: {"duration":0,"rate":0,"temp":"percent"}
SMB pump-loop failed. Pssst! Your pump is set to % basal type. The pump won’t accept temporary basal rates in this mode. Change it to absolute u/hr, and temporary basal rates will then be able to be set.
Unsuccessful supermicrobolus pump-loop at Sun 13 Aug 21:39:13 MST 2017

**Pull request merged**
