### PR TITLE
switch non-SMB users over to oref0-pump-loop

### PR DESCRIPTION
**Pull request by scottleibrand**
Not yet tested.  To test:

```
cd ~/src/oref0
git fetch
git checkout oref0-pump-loop
npm run global-install
```
and run oref0-runagain or oref0-setup again.

### CODE REVIEW

**Comment by Kdisimone** [comment]
would we potentially need to convert CGM tags (G4 in particular?) for master branch users who have the master tags saved in runagain?

**Comment by scottleibrand** [comment]
Anyone trying to use their 0.4.x runagain files on 0.5.0 will need to update those, regardless of this PR.

**Comment by Kdisimone** [comment]
worked for me

**Comment by scottleibrand** [comment]
@wharper11 also tested this and said in Gitter that it looks good.

**Pull request merged**
