### PR TITLE
Reboot rig if Unable to initialize libusb: -99 errors with Dexcom connected to USB OTG and uptime > 30m

### PR DESCRIPTION
**Pull request by PieterGit**
fixes https://github.com/openaps/oref0/issues/527

### CODE REVIEW

**Comment by PieterGit** [comment]
You mean like this? I will test this on a new rig.

**Comment by scottleibrand** [comment]
Yeah, I think that'll do it, thx.

**Comment by PieterGit** [comment]
It works, but you need to repower the USB before the rig is rebooted. 
Otherwise it won't reboot anymore (because it has been rebooted once).
There is no trigger to know when the power on the UART is back up.
So I think I'm stuck with two options:
1.  create an option for it, and let the user decide if reboot after 16 minutes, and then each half an hour is ok
2.  find some way to find out at which moment the USB UART gets 5V power. Do you know any?
3. upgrade to kernel 4.12 in which most USB-kernel issues for OTG are probably gone. 

If nobody knows a way to do 2, I think short-term solution is 1. (which is fine for me, because we always use USB OTG and primarily one rig).

**Comment by scottleibrand** [comment]
I don't understand the problem.  If you have incoming CGM data from either OTG or NS (your CGM data is more recent than the last reboot), then when CGM data gets to be 16 minutes old, it will reboot again.  What is the scenario where that's not good enough?

**Comment by PieterGit** [comment]
- only use CGM from USB OTG
- battery on USB UART is empty
- will cause USB subsystem to cause lsusb -99
- rig will reboot once
- no effect, because battery is still empty
- user changes battery or powers batter
- rig won't reboot because it has rebooted once and uptime < cmg last update

**Comment by scottleibrand** [comment]
Ok.  How are you preventing it from getting CGM data from NS?  Is this rig the only uploader?  Or is it just never online?

**Comment by PieterGit** [comment]
The rig is the only uploader, so it will download CGM data from NS if it has uploaded it itselves. It's online when it's on wifi. Remember European Dexcom don't have bluetooth / Share, so only USB OTG.

**Comment by scottleibrand** [comment]
In that case maybe some form of "I can hit the NS API, but it doesn't have any new CGM data" check would justify more frequent reboots?  That way, if you have two uploader rigs, or another uploader method like Share, it wouldn't reboot all the time, but if you don't have that it would fall back to rebooting periodically until it gets CGM data again...

If it's not obvious what I'm trying to accomplish here: I'd like to minimize the number of things for people to (mis)configure and instead have it behave sensibly in as many conditions as possible.

**Comment by PieterGit** [comment]
I'll try to implement something like that later this weekend. Can I also reboot frequently (say every 30 minutes) if I cannot reach the NS API (timeout)? (e.g. if I'm offline and have a loose cable or empty USB UART battery).

**Comment by scottleibrand** [comment]
It feels like there's some risk of doing that by default, but maybe it's not very high if we're only talking about a clean reboot every 30m...

**Comment by PieterGit** [comment]
I'm thinking on rewritinga and creating a preference `reboot_on_cgm_usb_error` (default:  false) and a `reboot_on_cgm_usb_error_threshold` (default: 16 minutes). 
And require both uptime > reboot_on_cgm_usb_error_thresholdand cgm last updated > reboot_on_cgm_usb_error_threshold

**Comment by scottleibrand** [comment]
I'm good with that.  Probably don't need to even have those preferences show up by default in preferences.json: anyone who wants them can add them in manually.

**Comment by tynbendad** [comment]
just ran into this - glad someone else is thinking about this.. i "solved" this by adding a script to check if the lsusb output is different & do a pushover to me if it changes, so at least i can know when it failed ;).

>Probably don't need to even have those preferences show up by default in preferences.json: anyone who wants them can add them in manually.

this worries me - how will we find out about the options? are there other options like this & is there a central list of them?

**Comment by scottleibrand** [comment]
@tynbendad openaps.rtfd.io/en/latest/docs/While%20You%20Wait%20For%20Gear/preferences-and-safety-settings.html

**Comment by scottleibrand** [comment]
Sorry I forgot about this one.  The code looks good to me.  I'm not sure why you're requiring and upgrade of dependencies, though.

**Comment by PieterGit** [comment]
i will drop the upgrade of dependencies for this pr, and won't reboot if fresh cgm's are available from Nightscout

**Comment by scottleibrand** [comment]
Sounds good.  LMK when you're ready for me to take another look.

**Comment by tynbendad** [comment]
Does this only work when enabled, or have a way to not affect non-receiver rigs?  Fwiw I rarely (maybe never?) see an lsusb error with receiver on 2017 explorer board or 2016 with trace cut.

**Comment by PieterGit** [comment]
I will make it configurable with an option (default disabled). I can reproduce lsusb errors quite easily with both the 2017 and 2016 trace cut Explorer board. Today I added some extra logging for fresh rigs. I'll work on this PR the next days to test and improve it.

**Comment by PieterGit** [comment]
@tynbendad @scottleibrand @sulkaharo : I'm thinking of closing this PR and not merging it.

Reasons:
- we should try to fix the root cause, probably kernel related
- during testing and developing my rig often rebooted, I can't use a `shutdown +5`  because the pump loop will then cancel that shutdown because there are no radio errors.  There is no coordinating between the pump and cgm loop that both might want to reboot the rig. Creating such a mechanism is too complex and error-prone.
- the added code to the cgm-loop is quite ugly and potentially error prone, we shouldn't let a workaround make the cgm-loop code less readable

I'm now thinking of three alternatives:
1.  documenting the best known workaround for those who are running in this problem:  
`*/15 * * * * /usr/bin/lsusb || shutdown -r now "lsusb error"`
2.  automating 1 in oref0-setup.sh (with a question and oref0 parameter to enable it in cron)
3. waiting to a jubilinux version with a 4.x kernel that probably doesn't have this problem

I propose to do 2. 
Thoughts?

**Comment by scottleibrand** [comment]
Yeah, I think we should revisit this when we refactor the cgm-loop stuff.  I am fine with just documenting the workaround in the meantime.

**Comment by scottleibrand** [comment]
Any reason to leave this open?

**Comment by PieterGit** [comment]
Closing this PR. Adding this will be to much work. The workaround `*/15 * * * * /usr/bin/lsusb || shutdown -r now "lsusb error"` is much more robust for those who use rigs with Dexcom attached by USB.

**Pull request closed without merging**
