### PR TITLE
rewind, prime and battery indicates change

### PR DESCRIPTION
**Pull request by Foxy7**
Added optional preferences to enable automatice update of Cannula, Insulin and Battery Age on Nightscout.

### CODE REVIEW

**Comment by Foxy7** [comment]
- [ ] actually i was going to set this to it was only fixed primes that get picked up. thought i had, but will check again. therefore manual primes would be ignored by openaps calcs.

**Comment by Foxy7** [comment]
linke to doc update: https://github.com/openaps/docs/pull/1571

**Comment by Foxy7** [comment]
example output:
```
{
  "timestamp": "2021-09-27T22:10:34+01:00",
  "_type": "Prime",
  "id": "AwADAAOiShYbFQ==",
  "amount": 0.3,
  "fixed": 0.3,
  "type": "fixed",
  "medtronic": "mm://openaps/mm-format-ns-treatments/Prime",
  "created_at": "2021-09-27T21:10:34.000Z",
  "enteredBy": "openaps://medtronic/722",
  "eventType": "Site Change",
  "notes": "Prime 722 ",
  "utcOffset": 60
}
{
  "timestamp": "2021-09-27T21:57:03+01:00",
  "_type": "Prime",
  "id": "AwAAAEODeTUbFQ==",
  "amount": 6.7,
  "fixed": 0,
  "type": "manual",
  "medtronic": "mm://openaps/mm-format-ns-treatments/Prime",
  "created_at": "2021-09-27T20:57:03.000Z",
  "enteredBy": "openaps://medtronic/722",
  "eventType": "Note",
  "notes": "Prime 722 ",
  "utcOffset": 60
}
{
  "timestamp": "2021-09-27T21:54:59+01:00",
  "_type": "Rewind",
  "id": "IQC7dhUbFQ==",
  "medtronic": "mm://openaps/mm-format-ns-treatments/Rewind",
  "created_at": "2021-09-27T20:54:59.000Z",
  "enteredBy": "openaps://medtronic/722",
  "eventType": "Insulin Change",
  "notes": "Rewind 722 ",
  "utcOffset": 60
}
```

image

**Comment by scottleibrand** [comment]
Can you confirm (have you tested?) that this only affects pills on Nightscout, and doesn't affect OpenAPS behavior in any way? If so, I'll probably s/cartridge/reservoir/g and then go ahead and merge it.

**Comment by jimrandomh** [comment]
Nice, this solves a pain point for me (currently pump-site-change is the only thing I'm entering directly in Nightscout, everything else I enter through the pump).

**Comment by scottleibrand** [comment]
@jimrandomh can you test it from this branch and confirm the intended behavior? Or would I need to merge it to dev first?

**Comment by jimrandomh** [comment]
I'll be testing it (and don't need it merged to dev to do so).

**Comment by jimrandomh** [comment]
I have been using this for a week and it seems to be working correctly. It updates the pills in Nightscout in the expected way.

**Comment by Foxy7** [comment]
Thanks both. yes to confirm only impacts NS pill, not OpenAPS at all.

**Comment by szymjaw** [comment]
It's not working for me.
Prime tretment in 'monitor/pumphistory-24h-zoned.json'
>{
    "timestamp": "2021-12-30T11:15:57+01:00",
    "_type": "Prime",
    "id": "AwAAAEj5DyseFQ==",
    "amount": 7.2,
    "fixed": 0,
    "type": "manual"
  }

after mm-format-ns-treatments.sh format

> {
    "timestamp": "2021-12-30T11:15:57+01:00",
    "_type": "Prime",
    "id": "AwAAAEj5DyseFQ==",
    "amount": 7.2,
    "fixed": 0,
    "type": "manual",
    "medtronic": "mm://openaps//root/src/oref0/bin/oref0-log-shortcuts.sh/Prime",
    "created_at": "2021-12-30T11:15:57+01:00",
    "enteredBy": "openaps://medtronic/",
    "eventType": "Note",
    "notes": "Prime  "
  }

whe I remove "and .type == "fixed" " from mm-format-ns-treatments.sh

>   {
    "timestamp": "2021-12-30T11:15:57+01:00",
    "_type": "Prime",
    "id": "AwAAAEj5DyseFQ==",
    "amount": 7.2,
    "fixed": 0,
    "type": "manual",
    "medtronic": "mm://openaps//root/src/oref0/bin/oref0-log-shortcuts.sh/Prime",
    "created_at": "2021-12-30T11:15:57+01:00",
    "enteredBy": "openaps://medtronic/",
    "eventType": "Site Change",
    "notes": "Prime  "
  },

**Comment by Foxy7** [comment]
@szymjaw this is correct, a "manual" prime won't trigger the NS eventType change and will only be shown as a note. 

This is because the usual process is that the medtronic pump is rewound, the tubing is manually primed and finally a 0.3 fixed prime (infusion set dependent) is used to fill the cannula. Hences the code only picks up two events, rewind and fixed prime. 

In the past we have used manual prime to add insulin which won't be counted by OpenAPS, e.g. after the pump was disconnected for a shower, we'd do a small manual prime to make up for missed insulin without OpenAPS double counting.

**Pull request merged**
