### PR TITLE
Tool to pull profile from Nightscout

### PR DESCRIPTION
**Pull request by scottleibrand**

### CODE REVIEW

**Comment by scottleibrand** [comment]
@viq looks like you've already done most of the work needed to help with a TODO I have for the oref0-simulator: `# TODO: download profile.json from Nightscout profile.json endpoint, and copy over to pumpprofile.json for autotuning`
https://github.com/openaps/oref0/pull/1325#issuecomment-562814662
Thanks!

Is there anything we need to know about this branch before pulling it in for simulator development?

**Comment by viq** [comment]
I haven't touched it in a while, it's a bit work in progress and IIRC
currently a bit chatty, but there's a flag inside to turn it off.

It was mostly done with autotune in mind. There are some corner cases it
doesn't deal with yet, for example AndroidAPS local profile in the profile
change event doesn't seem to include time zone.

There are some things that OpenAPS expects that aren't in nightscout that I
just hardcode.

There's one thing missing that I didn't do yet: DIA and insulin profile.
That data does not exist in nightscout profile and I intended to hardcode
some defaults and add flags to select other values, but didn't get around
to that.

Other than that, IIRC I was changing only that file, and it Works For Me.

**Comment by scottleibrand** [comment]
Cool, thanks. That's basically my use-case: running autotune, and the new oref0-backtest / oref0-simulator.

Is there an easy way to resolve `ImportError: No module named texttable` automatically? Ideally I'd like `pip` or something to install that without requiring it to be done manually.

**Comment by viq** [comment]
I could remove that dependency, it's only for printing profile as a table.
Otherwise, most people are on debian derivatives, and there are packages
for that, just `apt install python-texttable` or `python3-texttable`,
depending which python version you want to use (I tried to make it work
with both). I strongly dislike the idea of it performing such modifications
to the system without my knowledge, especially as you get different result
depending whether you do it as root, user, or run it in virtualenv.

**Comment by scottleibrand** [comment]
Ah, ok.  I'll just comment the singleton stuff out for now then. Thanks.

**Comment by viq** [comment]
Apparently it's possible to do conditional imports in python, I'll try
having a look at that.

**Pull request merged**
