### PR TITLE
autotune fixes (e.g. support for tokenbased authentication for autotune)

### PR DESCRIPTION
**Pull request by PieterGit**
Using SourceTree instead of GitHub Desktop

autotune fixes:
- support for tokenbased authenitcation for autotune
- support for use of API_SECRET when Nightscout site is default denied
- skip files that are not complete for oref0-autotune-export-to-xlsx.py (instead of throwing error)
- out of the box support for other locales (set LC_NUMERIC=en_US.UTF-8 in oref0-autotune-recommends-report.sh)
- add units to oref0-autotune-recommends-report.sh
- deprecate API_SECRET_READ oref0-autotune.sh (but if API_SECRET is set to the hashed version, it will still work)
- meaningful errors if essential files do not exists (e.g. settings/pumpprofile.json)

### CODE REVIEW

**Comment by PieterGit** [comment]
Retested it with token based authentication and with hashed API_SECRET admin password. Works fine. Please review and merge when accepted. 

I think this is also the fix for https://github.com/openaps/oref0/issues/342 and https://github.com/openaps/oref0/issues/397

@beached @gregtcm @jessiepusateri (or others). Can you please confirm that this PR works for you?

**Comment by scottleibrand** [comment]
Rebased against autotune-tokenauth branch and merging for easier testing.

**Comment by PieterGit** [comment]
Issue has not merged to dev yet. It was closed because @scottleibrand merge it to branch `openaps:autotune-tokenauth`. After testing it can be merged to dev.
I can't reopen the pull request for some reason.

**Comment by scottleibrand** [comment]
I don't believe I closed any issues.  This PR got merged to autotune-tokenauth, so we'll need a new PR of that branch to dev once we've tested it to our satisfaction.

**Comment by mountrcg** [comment]
Where can I enter the the hashed API-Secret in oref0-autotune? I have tried inserting line 52:

```
51 RECOMMENDS_REPORT=true
52 API_SECRET=32ea1df04----------------d8ae84f2750
53 UNKNOWN_OPTION=""TypeError: opts.glucose.map is not a function
```

but get:

```
TypeError: opts.glucose.map is not a function
    at categorizeBGDatums (/usr/local/lib/node_modules/oref0/lib/autotune-prep/categorize.js:22:40)
    at generate (/usr/local/lib/node_modules/oref0/lib/autotune-prep/index.js:24:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/oref0/bin/oref0-autotune-prep.js:110:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
Could not run oref0-autotune-prep ns-treatments.2018-10-03.json profile.json ns-entries.2018-10-03.json
```

**Pull request merged**
