### PR TITLE
Wip/accoutforbasalprofile

### PR DESCRIPTION
**Pull request by sulkaharo**
Changes IOB calculation take full basal profile into account. Fixes potential issues with fetching the basal rate (previous code was relying on the basal profile data being sorted, when it wasn't actually guaranteed).

### CODE REVIEW

**Comment by thebookins** [comment]
While we are at it, it wouldn't hurt to fix the sorting function at the end of history.js:
`     all_data.sort(function (a, b) { return a.date > b.date });`
Since `a.date` and `b.date` are integers, it's sufficient to write `return a.date - b.date` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). The current code doesn't sort properly. I'm not sure any of the downstream code depends on sorted data, but it may in the future.

**Comment by jasoncalabrese** [comment]
Tested last night and installed on all our rigs

**Comment by jasoncalabrese** [comment]
For sorting we should use lodash more, and get rid of the custom/fragile sort code.

**Comment by thebookins** [comment]
The iob calculation will be incorrect when temp basals cross basal profile boundaries (see https://github.com/openaps/oref0/issues/95#issuecomment-242865676).

**Comment by jasoncalabrese** [comment]
Updated main rig to the latest with the lodash sort, looking going I'm going to merge

**Pull request merged**
