### PR TITLE
if currentDeviation is null or maxDeviation is 0, set mealCOB to 0

### PR DESCRIPTION
**Pull request by scottleibrand**
This should help eliminate one source of zombie carbs by forcing mealCOB to 0 until we have enough data to properly calculate deviations.

### CODE REVIEW

**Comment by scottleibrand** [comment]
@tynbendad you might want to test this.

**Comment by tynbendad** [comment]
awesome, will do!  i think i just need to pull from bad-deviation branch, will try that tonight before he heads to 2ndary rig.

**Comment by scottleibrand** [comment]
Yeah, if you're already on dev, that should be sufficient.  Otherwise, you'll want to do `npm run global-install` as well after pulling that branch.

**Comment by scottleibrand** [comment]
Merged this to 0.6.0-dev.  If everything looks good there I'll merge to dev as well for eventual 0.5.3 release.

**Comment by tynbendad** [comment]
it did not fix the problem:
{"carbs":98,"boluses":10.7,"mealCOB":98,"currentDeviation":null,"maxDeviation":0,"minDeviationSlope":0}
mealCOB is still 98...  as is COB used for microbolus,etc.

root@benaps2:~# grep -n "currentDeviation === null" ~/src/oref0/lib/meal/total.js
71:    if (typeof(c.currentDeviation) === 'undefined' || c.currentDeviation === null) {

**Comment by scottleibrand** [comment]
Let's jump on Gitter for some real-time troubleshooting if you can.

**Comment by tynbendad** [comment]
summary from gitter: after running  npm run global-install from src/oref0 the fix appears to be working correctly.

**Pull request merged**
