### PR TITLE
Removing "enable" requirement for SMB - use preferences only 

### PR DESCRIPTION
**Pull request by danamlewis**
Per discussion in https://github.com/openaps/oref0/issues/737, moving forward with the community-voted option of removing the requirement to "enable" SMB, and only have to turn it on via preferences, to prevent edge case and unnecessary confusion. This needs testing before it merges.

### CODE REVIEW

**Comment by scottleibrand** [comment]
To test: `cd ~/src/oref0 && git fetch && git checkout smb-in-preferences-only && git pull && npm run global-install` and then re-run oref0-setup.

**Comment by scottleibrand** [comment]
Any volunteers to test this so we can merge it?

**Comment by efidoman** [comment]
I'm testing it now. I switched to this branch, ran global install, took microbolus out of oref0-runagain.sh and re-ran setup. It is looping now with  `Starting oref0-pump-loop at Thu Nov  2 10:51:02 EDT `

However, I need to wait for lunch time to test SMB's. My current preferences are as follows:

`{
        "max_iob": 9,
        "max_daily_safety_multiplier": 13,
        "current_basal_safety_multiplier": 14,
        "autosens_max": 1.5,
        "autosens_min": 0.5,
        "rewind_resets_autosens": true,
        "adv_target_adjustments": false,
        "exercise_mode": false,
        "unsuspend_if_no_temp": true,
        "enableSMB_with_COB": true,
        "enableSMB_with_temptarget": true,
        "enableUAM": true,
        "curve": "rapid-acting"
}
`

**Comment by efidoman** [comment]
SMB isn't working for me. I think the problem may be unrelated to this branch's changes. My NS site is up and running and getting treatments, but openaps isn't able to communicate with it for some reason. I can't figure out why yet.

**Comment by efidoman** [comment]
OK - I got my unrelated npm install issues all sorted out and fixed. Testing this branch and it works great for me. 👍 

SMB's are working and I didn't use enable microbolus when I re-ran oref0-runagain.sh.

**Comment by scottleibrand** [comment]
Thanks.  Based on @efidoman's testing I think we're good to merge this if nobody else wants to test anything specific before it goes to dev.

**Pull request merged**
