### PR TITLE
Attempting to --nogit by default for existing user installs

### PR DESCRIPTION
**Pull request by danamlewis**
Thanks to the amazing @Kdisimone as always for the first round of testing, confirmed it successfully installs and removes an existing git directory.

Looks like this after starting setup:
screen shot 2017-10-06 at 2 25 36 pm

And then it successfully removed .git

For anyone else who wants to test:
1. `cd ~/myopenaps` and `ls -la` (you should see .git listed in the alphabetical list - we need this tested on rigs that still have git)
2. `cd ~/src/oref0/ && git fetch && git checkout no-git-default && git pull`
3. `npm run global-install`
4. `bash ~/myopenaps/oref0-runagain.sh`
5. Once done, `ls -la` again in `myopenaps` and confirm that .git no longer exists there.
*(If you're planning to stay on this branch vs. switching back to dev, make sure to re-set your preferences!)*

### CODE REVIEW

**Comment by scottleibrand** [comment]
Nice.  We should also test it on a rig that's already had .git removed.  It will probably whine about being unable to remove .git - we'll need to decide if that's clear enough, or if we need to redirect the output of `rm` to squelch it.

**Comment by Kdisimone** [comment]
@scottleibrand I'll rerun it now...want me to just try a runagain?

**Comment by scottleibrand** [comment]
Ok, good.  No scary warnings.  :-)  Thanks.

**Comment by Kdisimone** [comment]
no worries.  installed fine both ways.  and YEAH for nogit!

**Pull request merged**
