### PR TITLE
unsuspend pump automatically if temp basal duration is zero

### PR DESCRIPTION
**Pull request by scottleibrand**
Per https://github.com/openaps/oref0/issues/175, sometimes people forget to resume / unsuspend their pump after reconnecting it.  This would cause oref1 to automatically resume the pump if the underlying zero temp has expired.  As long as the zero temp is still running, it would honor the suspend status and do nothing.  As written, this would not apply to users running the old `openaps pump-loop`, only people who have enabled microboluses in oref0-setup and are using oref0-pump-loop.sh.

Thoughts?

### CODE REVIEW

**Comment by mgranberryto** [comment]
I have mixed feelings about this, but I also have it set up to SMS me if I leave the pump suspended.  I think the better fix is a better mechanism to notify OpenAPS that the pump is disconnected.  I can't think of a situation where this would have done me harm and several where it would have caught a mistake earlier, but it still feels like it's a surprising behavior.  I know a semi-pro tennis player that chooses to go pump-free while training, only bolusing for a couple snacks throughout the day because his insulin needs are so low.  He leaves his pump suspended during those periods because he simply doesn't need the insulin during his training days.

I'll concede that there are fewer people like him than people like me who sometimes forget to unsuspend the pump after a shower or other reasons to disconnect, for me, this would be a welcomed change, but it may surprise people and insulin delivery will be affected.  I can imagine a situation where I didn't have a reservoir on me and had to inject insulin away from a pump and would want to suspend delivery until the other insulin had cleared my system.  This is one of those situations where I wish we had an alerting device as part of the base system.

**Comment by scottleibrand** [comment]
Wouldn't someone in that scenario need to set a long temp basal to zero (for the duration the pump is expected to be suspended) so that IOB is correct when the pump is later unsuspended?

**Comment by scottleibrand** [comment]
@danamlewis Any thoughts?

**Comment by danamlewis** [comment]
@scottleibrand 👍 would this be in preferences to toggle?

**Comment by scottleibrand** [comment]
Only if someone insists that we need Yet Another Preference for it.  I would prefer to make it the default behavior.

**Comment by danamlewis** [comment]
@kdisimone thoughts on Yet Another Preference(TM) vs having it in the code so if people do want to disable, they can just comment out the code? (I'm ok with lengthening the preferences list)

**Comment by PieterGit** [comment]
@scottleibrand : I think this behaviour warrants a new preference. I think the mental model of people is that oref0 changes the temp basals, oref1 does microboluses. Having pumps unsuspend is not expected behaviour. So I would make it default False and if the user chooses to change the preference it's aware of this pump behaviour.

**Comment by betluis** [comment]
Many times my daughter has ended up high due to forgetting to re-activate the pump, specially at night. My personal opinion is that the system should reactivate the pump when 0 temping is not needed any more. The pump therapy is required to keep a person within range, if somebody purposely wants to stop insulin delivery regardless of sugar levels then probably the best way is to disconnect the pump from the body altogether. In practice every time my daughter suspends the pump she intends to do it temporarily but then she forgets to reactivate it...

**Comment by mgranberryto** [comment]
This would be helpful for me, but I know to expect it.  It seems like suspending is an explicit "do not give insulin" command and overriding that seems strange.  I'm with Pieter on this one.  It's a feature that I want enabled, but not by default.  What if emergency care workers suspend the pump and take over insulin delivery without disconnecting?  The corner cases are problematic here.

**Comment by tim2000s** [comment]
My view on this is that suspension is a willing interference by a human so automatic resume should not be a default setting. There can be good reasons for it. It's also not a feature that I think should be enabled. For example, the shower setting is to remove the pump, set basal to zero then suspend. With something like this enabled, it would cancel the zero temp. 

I think we probably need to hash out what the use cases and counter cases are before setting up a test version. 

It raises the question about whether we should build in a feature that purports to replace a forgetful adult but also overrides a conscious one.

**Comment by scottleibrand** [comment]
@tim2000s no, it wouldn't cancel the zero temp in a zero-temp then suspend case.  If there is a zero temp still running, it will never unsuspend.  Only once the zero temp expires would it do so.  So if a conscious adult wants to suspend for 6 hours, then they set a 6 hour temp to zero and suspend.  If they only plan to be suspended for 30m, then they only set a 30m zero temp before suspending.

Can you explain what use cases (good reasons) there would be for suspending without an appropriate-length zero temp, or for wanting the pump to remain suspended indefinitely (with the rig still running)?

**Comment by moomoobloo** [comment]
How about starting with on on-by-default Pushover alert? That should be
fairly uncontroversial.

**Comment by danamlewis** [comment]
Not everyone has or wants Pushover. That's certainly one option, but I'd rather create the preference, default it to false, and allow those who want it to turn it to be true. Any information about edge cases/cautions about using it can be added to the docs for people to consider, like any other feature, before turning it on.

**Comment by scottleibrand** [comment]
A pushover alert would also be a good idea, but we can't rely on those, because they require the user to purchase and configure an extra service.  It sounds like there are enough people who might want to turn off auto-unsuspend that it should be a preference, and enough people are uncomfortable with on-by-default that I think I'd be ok with off-by-default.  I suspect this will turn out like AMA, though, and everyone will go turn it on as they set up their rigs.

**Comment by danamlewis** [comment]
Added to preferences with an explanation; defaults to false. LGTM for merging to dev @scottleibrand

**Comment by danamlewis** [comment]
Testing, it worked:

```
Temp refreshed: monitor/temp_basal.json: {"duration":0,"rate":0,"temp":"absolute"}
Checking pump status (suspended/bolusing): {"status":"normal","bolusing":false,"suspended":true}
Pump suspended; Temp basal has ended: unsuspending pump
{
  "status": "resumed",
  "recieved": true,
  "enacted_at": "2017-06-28T15:27:00.974838"
}
```

**Comment by scottleibrand** [comment]
With pump suspended and zero temp still running:
```
Temp refreshed: monitor/temp_basal.json: {"duration":8,"rate":0,"temp":"absolute"}
Checking pump status (suspended/bolusing): {"status":"normal","bolusing":false,"suspended":true}
Pump suspended; Temp basal still running: leaving pump suspended
Checking pump status (suspended/bolusing): {"status":"normal","bolusing":false,"suspended":true}
```

**Comment by scottleibrand** [comment]
As soon as the temp basal ended, it unsuspended:
```
Temp refreshed: monitor/temp_basal.json: {"duration":0,"rate":0,"temp":"absolute"}
Checking pump status (suspended/bolusing): {"status":"normal","bolusing":false,"suspended":true}
Pump suspended; Temp basal has ended: unsuspending pump
{
  "status": "resumed",
  "recieved": true,
  "enacted_at": "2017-06-28T16:12:54.057081"
}Checking pump status (suspended/bolusing): {"status":"normal","bolusing":false,"suspended":false}
```
and then set a temp on the next pump-loop.

**Comment by scottleibrand** [comment]
Oh, and I forgot to copy and paste it, but we also saw that oref0-pump-loop would not unsuspend without `"unsuspend_if_no_temp": true` set in preferences.

I think that's all the testing we need before merging to dev.  If no objections, I'll do so shortly.

**Pull request merged**
