### PR TITLE
Meal assist

### PR DESCRIPTION
**Pull request by scottleibrand**
Not ready to merge yet.

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
testing to see if gitter picks this up

**Comment by scottleibrand** [comment]
now that #41 is merged, any reason not to merge this so meal-assist becomes our new dev?

**Comment by danamlewis** [comment]
+1 for merging to dev @scottleibrand

**Comment by amazaheri** [comment]
Let's do it, fully tested with 512 as well.

**Comment by amazaheri** [comment]
3 nights of dogfooding.

**Pull request merged**
