### PR TITLE
Autotune patch release to master (oref0 0.5.5 patch release)

### PR DESCRIPTION
**Pull request by danamlewis**
There are some significant improvement to autotune that are currently in the dev branch, that make a big difference to tackle the previously-known issues around upward bias on ISF and carb ratio. Dev (0.6.0) is a ways out from release, so wanting to patch so one-off users of autotune and everyone on master can utilize the autotune improvements sooner.

### CODE REVIEW

**Comment by scottleibrand** [comment]
Tested successfully on my Mac, a rig, and a Ubuntu box.

**Comment by scottleibrand** [comment]
To test: 
```
cd ~/src/oref0/ && git fetch && git checkout autotune-prep && git pull
npm run global-install
oref0-autotune --dir=~/myopenaps --ns-host=https://yournightscout.herokuapp.com
```

**Comment by Kdisimone** [comment]
@scottleibrand minor correction on branch name

```
cd ~/src/oref0/ && git fetch && git checkout autotune-patch && git pull
npm run global-install
oref0-autotune --dir=~/myopenaps --ns-host=https://yournightscout.herokuapp.com
```

**Comment by danamlewis** [comment]
Good catch @Kdisimone  :) Fixed.

**Comment by Kdisimone** [comment]
was this supposed to also help Phase C, mac users doing on one-off on their local computers?

if so, i ran into an error using it that way:

```
Kathryns-iMac:settings iMac4K$ oref0-autotune --dir=~/myopenaps --ns-host=https://testopenaps.herokuapp.com
Warning: API_SECRET is not set when calling oref0-autotune.sh
Running oref0-autotune --dir=/Users/iMac4K/myopenaps --ns-host=https://testopenaps.herokuapp.com --start-date=2017-10-05 --end-date=2017-10-05
/usr/local/bin/oref0-autotune: line 156: json: command not found
Grabbing NIGHTSCOUT treatments.json and entries/sgv.json for date range...
Query: https://testopenaps.herokuapp.com find%5Bdate%5D%5B%24gte%5D=1507186800000&find%5Bdate%5D%5B%24lte%5D=1507273200000&count=1000
/usr/local/bin/ns-get: line 60: json: command not found
Couldn't download ns-entries.2017-10-05.json
```

**Comment by scottleibrand** [comment]
That's a different issue I keep asking people to PR in a fix for, but no one seems willing to do.  (I could do it, but it's simple enough there's no reason someone else shouldn't.)  We just need to replace all instances of the `json` command with `jq .` and then test that fixes it without breaking anything.

**Comment by Kdisimone** [comment]
I'll do that

**Comment by Kdisimone** [comment]
dev branch, yes?

**Comment by scottleibrand** [comment]
Yeah, best to start off of autotune-patch, and then we'll merge that back into dev afterward.

**Comment by Kdisimone** [comment]
BTW, works great!  👍

**Comment by bdr1177** [comment]
Is this intended to work for one off on a VM?  If so, I haven't been able to get it to work on google VM.  Because there's no /src/oref0/ directory, the first command fails.

**Comment by diabeticdude2** [comment]
What I did to fix that problem was use SCP to copy the SRC folder from my rig to my mac
  

  
  
  Reference link   https://superuser.com/questions/449348/copy-a-whole-folder-from-a-remote-computer
  
  
>

**Comment by danamlewis** [comment]
The lack of src/oref0 is if you follow the above solely for testing and don't already have a repo in place (which you'll get by following the Phase C one-off instructions). So that won't be an issue once this gets merged.

**Pull request merged**
