### PR TITLE
Preparing 0.1.2 release

### PR DESCRIPTION
**Pull request by scottleibrand**
Not ready to merge yet.

### CODE REVIEW

**Comment by scottleibrand** [comment]
I've now tested this enough to consider it a release candidate.  Would like to get opinions from a few other testers on whether this is overall an improvement from the previous BGI/2 algorithm, and whether there are any behaviors that need fixing before we release to master.

**Comment by bewest** [comment]
Looking good to me, but my development environment fell apart... still rebuilding it and haven't tested this personally, but I like the changes overall. Very nice.

**Comment by scottleibrand** [comment]
Anything else we need before merging this to master and cutting a release?  Any reason not to do that tonight?

**Comment by jasoncalabrese** [comment]
:+1: to release

**Pull request merged**
