### PR TITLE
Automate the steps to install flask as a service

### PR DESCRIPTION
**Pull request by cduarte**
Automate the steps to install flask as a service so can monitoring your rig OFFLINE with an Offline web page

IPHONE USERS To access this from an iphone browser, enter something like the following: http://172.20.10:5000

ex : http://IP_address__rig:5000

### CODE REVIEW

**Comment by scottleibrand** [comment]
LGTM.  Will merge, probably tomorrow, if no objections.

**Comment by efidoman** [comment]
should we specify -p 5000 in the crontab command line for flask? I tested this manually and it only worked if I specify -p and the port number when running flask.

**Comment by efidoman** [comment]
Also, any objections to adding a 60 second refresh into index.html? Use case is when I'm in a hotel, no wifi and just want to leave my phone or laptop on this page all night and glance at it from the bed to see BG.

**Comment by scottleibrand** [comment]
Feel free to PR either/both of those.

**Comment by scottleibrand** [comment]
Merging this to a new `flask` branch for easier PR targeting.

**Comment by PieterGit** [comment]
Two remarks:

1. I think users should be asked if they want to have a flask webserver installed on their rig.  Having a local webserver running on the rig should be optional.  

2. Running `/root/myopenaps/enact/regenerate-index.sh` every minute seems a waste of cpu resources, why not generate it upon user request?

**Comment by scottleibrand** [comment]
Feel free to PR improvements.  I'm generally going to favor merging people's work to dev rather than holding it up for hypothetical further changes, but would have no objection to merging further work to make it more secure and user-friendly.

**Pull request merged**
