### PR TITLE
Tzachi share node ns status

### PR DESCRIPTION
**Pull request by tzachi-dar**
This version includes oref0-shared code + the code of upload-status-when-possible.

It is based on the current head version.
I'll only be able to test it tonight.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
Please note that this assumes that " oref0-shared-node-loop" is in the path.
Try running "which  oref0-shared-node-loop".
It should be in /usr/local/bin/oref0-shared-node-loop

this is a symbolic link. See output of the following command. 
ls -l /usr/local/bin/oref0-shared-node-loop
lrwxrwxrwx 1 root root 55 Jan 13 00:04 /usr/local/bin/oref0-shared-node-loop -> ../lib/node_modules/oref0/bin/oref0-shared-node-loop.sh

**Comment by tzachi-dar** [comment]
I have run with it tonight and it seems to work fine.
Please try this version.

**Comment by scottleibrand** [comment]
Looks like the problem is `bash: socat: command not found` - we'll need to add an install step for that.

**Comment by scottleibrand** [comment]
I've been running this successfully on a couple of rigs for a few months now, so I think it's good to merge. Anything else we should do/test before doing so?

**Comment by tzachi-dar** [comment]
I think this one was replaced by 1361.
I think that the next one to be merges is https://github.com/openaps/oref0/pull/1370

**Comment by scottleibrand** [comment]
Is this a subset of #1370? If so, I’d prefer to merge this first, as it’s been tested, and then see what’s left in 1370 and test that.

**Comment by tzachi-dar** [comment]
No #1370 is a PR by itself that should be viewed against dev branch.

**Pull request closed without merging**
