### PR TITLE
Fix whitespaces issue for pull request 54 Extended last glucose reading date validation

### PR DESCRIPTION
**Pull request by eyim**

### CODE REVIEW

**Comment by scottleibrand** [comment]
Calling all Medtronic CGM users (and anyone else) for some testing. @eyim just created this PR to pull in @ktomy's openaps/oref0#54 changes. would like to have a few people check out @eyim's oref0 dev branch (https://github.com/eyim/oref0/tree/dev) and see if it works in all the different old-BG situations you can think of (and doesn't break anything in normal usage)

**Comment by eyim** [comment]
Hmm still didn't fix the issue I am having with old bg info.  Hopefully it fixes errors for other folks

**Comment by scottleibrand** [comment]
@eyim want to open an issue with details on what you're seeing?  we should be able to update these checks to catch it.

**Comment by bewest** [comment]
Couple of notes:
Does this cover https://github.com/openaps/oref0/issues/104 or need to?

* `Date.parse(isoformat)` generates a timestamp in ms... many formatted date strings can be converted to js date using `new Date(Date.parse(isoformatish))`.
* using http://sugarjs.com/dates is wonderful.

I see that some of the fixes I came up with conflict, I've posted a resolution to the conflicts here: https://github.com/openaps/oref0/pull/103.  Would love to see some of the `sugarjs` date stuff come into play.  Should we enable a `--dateField` switch to allow oref0 to select which field to read the date from?

**Comment by scottleibrand** [comment]
So where are we with this now that fix-cli has been merged to dev?

**Comment by eyim** [comment]
Sorry I am not qualified to pass judgement on this.  I simply fixed the white space issue. I can only say that it didn't fix my particular issue.  

Edward

**Pull request closed without merging**
