### PR TITLE
don't require a BG for a Meal Bolus event type

### PR DESCRIPTION
**Pull request by jasoncalabrese**

### CODE REVIEW

**Comment by scottleibrand** [comment]
Have you tested this in production yet? Should we merge to AMA first?

**Comment by jasoncalabrese** [comment]
Running it in production now, and saw it fix the bug that prevented a pushover since there was no event type

Thought I'd PR it to dev so others can get the fix a little sooner if they aren't ready for AMA.

**Comment by scottleibrand** [comment]
Ok, I'll merge to dev. Was this already fixed in AMA, or do we need to PR it there too?

**Comment by jasoncalabrese** [comment]
I was thinking we'd merge dev back to AMA

**Comment by scottleibrand** [comment]
:+1: sounds good.

**Pull request merged**
